<a href="https://colab.research.google.com/github/contatowillian/fiap/blob/desafio_3/8IADT_Fase_3_Tech_challenge_com_ppt_ipynb.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

 # Projeto Tech Challenge - Assistente Virtual Médico Personalizado

Este notebook contém o passo a passo completo e modularizado para o desenvolvimento de um Assistente Virtual Médico Personalizado, utilizando Fine-Tuning de LLM, LangChain/LangGraph e mecanismos de segurança, conforme os requisitos do Tech Challenge - Fase 3.

## 1. Instalação de Bibliotecas Essenciais

Vamos começar instalando todas as bibliotecas necessárias para o projeto. Isso inclui ferramentas para fine-tuning (Unsloth, Peft, TRL), manipulação de LLMs (transformers, accelerate, bitsandbytes), e construção de agentes (LangChain, LangGraph, datasets).

In [1]:
# Instalação de bibliotecas necessárias para fine-tuning, LangChain e LangGraph.
# A flag -qq (quiet) é usada para instalações mais limpas no Colab, exceto onde precisamos de mais detalhes.

# 1. Atualizar pip
!pip install -qqq --upgrade pip

# 2. **LIMPEZA AGRESSIVA DE DIRETÓRIOS LANGCHAIN RESIDUAIS**
# Isso é feito para garantir que não haja arquivos antigos ou corrompidos de instalações anteriores.
import os
import shutil
import site

site_packages_path = site.getsitepackages()[0]
print(f"\nRealizando limpeza agressiva de diretórios LangChain residuais em: {site_packages_path}")

langchain_prefixes = [
    'langchain',
    'langchain_community',
    'langchain_core',
    'langchain_text_splitters',
    'langgraph',
    'langgraph_prebuilt',
    'langgraph_sdk',
    'langchain_classic',
    'langsmith'
]

for item_name in os.listdir(site_packages_path):
    for prefix in langchain_prefixes:
        if item_name.startswith(prefix):
            full_path = os.path.join(site_packages_path, item_name)
            try:
                if os.path.isdir(full_path):
                    print(f"Removendo diretório: {full_path}")
                    shutil.rmtree(full_path)
                elif os.path.isfile(full_path) and (item_name.endswith('.py') or item_name.endswith('.egg-link')):
                    print(f"Removendo arquivo: {full_path}")
                    os.remove(full_path)
            except Exception as e:
                print(f"Erro ao remover {full_path}: {e}")
                pass # Continue tentando remover outros

print("Limpeza concluída. Prosseguindo com a instalação limpa.\n")

# 3. Instalar `typing-extensions` e `packaging` explicitamente e cedo.
#    Usamos `--ignore-installed` para evitar conflitos com versões do sistema que não podem ser desinstaladas.
print("Reinstalando typing-extensions e packaging com tratamento de conflitos...")
!pip install -qqq --upgrade typing-extensions packaging --ignore-installed

# 4. Instalar Unsloth e suas dependências otimizadas para Colab.
#    Esta é a instalação mais crítica, e deve ser feita antes de outras que podem ter conflitos.
#    Unsloth trará Pydantic v2 e pydantic-core, e suas próprias versões de transformers, accelerate, bitsandbytes, numpy, pandas.
print("Instalando Unsloth e suas dependências otimizadas...")
!pip install -qqq --upgrade "unsloth[colab-new] @ git+https://github.com/unslothai/unsloth.git"

# 5. Instalar outras dependências de Hugging Face não incluídas diretamente no Unsloth.
#    Essas geralmente são menos propensas a grandes conflitos.
print("Instalando dependências adicionais do Hugging Face (peft, trl, datasets)...")
!pip install -qqq peft trl datasets

# 6. Instalar nltk e sentence-transformers explicitamente (para resolver o erro de nltk e embeddings).
print("Instalando nltk e sentence-transformers...")
!pip install -qqq nltk sentence-transformers

# 7. Ferramentas para LangChain e LangGraph.
print("Desinstalando todos os componentes do LangChain para uma reinstalação limpa...")
# Desinstalação agressiva para garantir que nenhuma versão antiga ou corrompida persista.
!pip uninstall -y langchain langchain_community langchain_core langgraph langchain-text-splitters langsmith langchain-classic langgraph-prebuilt langgraph-sdk

print("Instalando bibliotecas LangChain e LangGraph com versões recentes e forçadas...")
# Reinstalamos com --force-reinstall e --no-cache-dir para evitar o uso de pacotes corrompidos do cache.
!pip install --force-reinstall --no-cache-dir langchain langchain_community langchain_core langgraph langchain-text-splitters

# 8. Para visualização (opcional) e PDF
print("Instalando bibliotecas de visualização e PDF (matplotlib, seaborn, pypdf)...")
!pip install -qqq matplotlib seaborn pypdf

print("Instalação de todas as bibliotecas concluída!")

print("\nVerificando versões instaladas de pacotes chave:")
!pip show packaging
!pip show numpy
!pip show pandas
!pip show pydantic
!pip show pydantic-core
!pip show typing-extensions
!pip show nltk
!pip show sentence-transformers
!pip show langchain
!pip show langchain_community
!pip show langchain_core
!pip show langchain-text-splitters
!pip show langgraph
!pip show langsmith
!pip show langchain-classic
!pip show langgraph-prebuilt
!pip show langgraph-sdk
!pip show unsloth

Realizando limpeza agressiva de diretórios LangChain residuais em: /usr/local/lib/python3.13/dist-packages
Removendo diretório: /usr/local/lib/python3.13/dist-packages/langgraph-1.2.11.dist-info
Removendo diretório: /usr/local/lib/python3.13/dist-packages/langchain-1.4.0.dist-info
Removendo diretório: /usr/local/lib/python3.13/dist-packages/langsmith
Removendo diretório: /usr/local/lib/python3.13/dist-packages/langchain_text_splitters-1.1.2.dist-info
Removendo diretório: /usr/local/lib/python3.13/dist-packages/langchain_classic-1.0.8.dist-info
Removendo diretório: /usr/local/lib/python3.13/dist-packages/langchain_community
Removendo diretório: /usr/local/lib/python3.13/dist-packages/langgraph_prebuilt-1.1.0.dist-info
Removendo diretório: /usr/local/lib/python3.13/dist-packages/langgraph_sdk-0.4.4.dist-info
Removendo diretório: /usr/local/lib/python3.13/dist-packages/langchain_text_splitters
Removendo diretório: /usr/local/lib/python3.13/dist-packages/langchain_protocol-0.0.19.dist-info
Removendo diretório: /usr/local/lib/python3.13/dist-packages/langchain_core
Removendo diretório: /usr/local/lib/python3.13/dist-packages/langsmith-0.12.4.dist-info
Removendo diretório: /usr/local/lib/python3.13/dist-packages/langchain_classic
Removendo diretório: /usr/local/lib/python3.13/dist-packages/langchain_core-1.6.3.dist-info
Removendo diretório: /usr/local/lib/python3.13/dist-packages/langgraph
Removendo diretório: /usr/local/lib/python3.13/dist-packages/langchain_protocol
Removendo diretório: /usr/local/lib/python3.13/dist-packages/langgraph_checkpoint-4.2.0.dist-info
Removendo diretório: /usr/local/lib/python3.13/dist-packages/langchain_community-0.4.2.dist-info
Removendo diretório: /usr/local/lib/python3.13/dist-packages/langgraph_sdk
Removendo diretório: /usr/local/lib/python3.13/dist-packages/langchain
Limpeza concluída. Prosseguindo com a instalação limpa.

Reinstalando typing-extensions e packaging com tratamento de conflitos...
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
google-genai 2.12.1 requires websockets<17.0,>=13.0.0, but you have websockets 17.1 which is incompatible.
google-adk 2.7.1 requires websockets<16,>=15.0.1, but you have websockets 17.1 which is incompatible.
Instalando Unsloth e suas dependências otimizadas...
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Instalando dependências adicionais do Hugging Face (peft, trl, datasets)...
Instalando nltk e sentence-transformers...
Desinstalando todos os componentes do LangChain para uma reinstalação limpa...
WARNING: Skipping langchain as it is not installed.
WARNING: Skipping langchain_community as it is not installed.
WARNING: Skipping langchain_core as it is not installed.
WARNING: Skipping langgraph as it is not installed.
WARNING: Skipping langchain-text-splitters as it is not installed.
WARNING: Skipping langsmith as it is not installed.
WARNING: Skipping langchain-classic as it is not installed.
WARNING: Skipping langgraph-prebuilt as it is not installed.
WARNING: Skipping langgraph-sdk as it is not installed.
Instalando bibliotecas LangChain e LangGraph com versões recentes e forçadas...
Collecting langchain
  Downloading langchain-1.4.0-py3-none-any.whl.metadata (6.2 kB)
Collecting langchain_community
  Downloading langchain_community-0.4.2-py3-none-any.whl.metadata (3.4 kB)
Collecting langchain_core
  Downloading langchain_core-1.6.3-py3-none-any.whl.metadata (4.8 kB)
Collecting langgraph
  Downloading langgraph-1.2.11-py3-none-any.whl.metadata (4.9 kB)
Collecting langchain-text-splitters
  Downloading langchain_text_splitters-1.1.2-py3-none-any.whl.metadata (3.3 kB)
Collecting pydantic<3.0.0,>=2.7.4 (from langchain)
  Downloading pydantic-2.13.5-py3-none-any.whl.metadata (110 kB)
Collecting httpx<1.0.0,>=0.23.0 (from langchain_core)
  Downloading httpx-0.28.1-py3-none-any.whl.metadata (7.1 kB)
Collecting jsonpatch<2.0.0,>=1.33.0 (from langchain_core)
  Downloading jsonpatch-1.33-py2.py3-none-any.whl.metadata (3.0 kB)
Collecting langchain-protocol>=0.0.17 (from langchain_core)
  Downloading langchain_protocol-0.0.19-py3-none-any.whl.metadata (2.4 kB)
Collecting langsmith<1.0.0,>=0.3.45 (from langchain_core)
  Downloading langsmith-0.12.4-py3-none-any.whl.metadata (22 kB)
Collecting packaging>=23.2.0 (from langchain_core)
  Downloading packaging-26.3-py3-none-any.whl.metadata (3.5 kB)
Collecting pyyaml<7.0.0,>=5.3.0 (from langchain_core)
  Downloading pyyaml-6.0.3-cp313-cp313-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl.metadata (2.4 kB)
Collecting tenacity!=8.4.0,<10.0.0,>=8.1.0 (from langchain_core)
  Downloading tenacity-9.1.4-py3-none-any.whl.metadata (1.2 kB)
Collecting typing-extensions<5.0.0,>=4.7.0 (from langchain_core)
  Downloading typing_extensions-4.16.0-py3-none-any.whl.metadata (3.3 kB)
Collecting uuid-utils<1.0,>=0.12.0 (from langchain_core)
  Downloading uuid_utils-0.17.1-cp313-cp313-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (6.4 kB)
Collecting langgraph-checkpoint<5.0.0,>=4.1.0 (from langgraph)
  Downloading langgraph_checkpoint-4.2.0-py3-none-any.whl.metadata (6.7 kB)
Collecting langgraph-prebuilt<1.2.0,>=1.1.0 (from langgraph)
  Downloading langgraph_prebuilt-1.1.0-py3-none-any.whl.metadata (5.2 kB)
Collecting langgraph-sdk<0.5.0,>=0.4.2 (from langgraph)
  Downloading langgraph_sdk-0.4.4-py3-none-any.whl.metadata (5.1 kB)
Collecting xxhash>=3.5.0 (from langgraph)
  Downloading xxhash-4.0.1-cp313-cp313-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl.metadata (17 kB)
Collecting anyio (from httpx<1.0.0,>=0.23.0->langchain_core)
  Downloading anyio-4.15.1-py3-none-any.whl.metadata (4.7 kB)
Collecting certifi (from httpx<1.0.0,>=0.23.0->langchain_core)
  Downloading certifi-2026.7.22-py3-none-any.whl.metadata (2.5 kB)
Collecting httpcore==1.* (from httpx<1.0.0,>=0.23.0->langchain_core)
  Downloading httpcore-1.0.9-py3-none-any.whl.metadata (21 kB)
Collecting idna (from httpx<1.0.0,>=0.23.0->langchain_core)
  Downloading idna-3.19-py3-none-any.whl.metadata (9.2 kB)
Collecting h11>=0.16 (from httpcore==1.*->httpx<1.0.0,>=0.23.0->langchain_core)
  Downloading h11-0.16.0-py3-none-any.whl.metadata (8.3 kB)
Collecting jsonpointer>=1.9 (from jsonpatch<2.0.0,>=1.33.0->langchain_core)
  Downloading jsonpointer-3.1.1-py3-none-any.whl.metadata (2.4 kB)
Collecting ormsgpack>=1.12.0 (from langgraph-checkpoint<5.0.0,>=4.1.0->langgraph)
  Downloading ormsgpack-1.12.2-cp313-cp313-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (3.2 kB)
Collecting orjson>=3.11.5 (from langgraph-sdk<0.5.0,>=0.4.2->langgraph)
  Downloading orjson-3.12.0-cp313-cp313-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (41 kB)
Collecting websockets<17,>=14 (from langgraph-sdk<0.5.0,>=0.4.2->langgraph)
  Downloading websockets-16.1.1-cp313-cp313-manylinux1_x86_64.manylinux_2_28_x86_64.manylinux_2_5_x86_64.whl.metadata (6.8 kB)
Collecting distro>=1.7.0 (from langsmith<1.0.0,>=0.3.45->langchain_core)
  Downloading distro-1.9.0-py3-none-any.whl.metadata (6.8 kB)
Collecting httpx2<3,>=2 (from langsmith<1.0.0,>=0.3.45->langchain_core)
  Downloading httpx2-2.12.0-py3-none-any.whl.metadata (9.5 kB)
Collecting requests-toolbelt>=1.0.0 (from langsmith<1.0.0,>=0.3.45->langchain_core)
  Downloading requests_toolbelt-1.0.0-py2.py3-none-any.whl.metadata (14 kB)
Collecting requests>=2.0.0 (from langsmith<1.0.0,>=0.3.45->langchain_core)
  Downloading requests-2.34.2-py3-none-any.whl.metadata (4.8 kB)
Collecting sniffio>=1.1 (from langsmith<1.0.0,>=0.3.45->langchain_core)
  Downloading sniffio-1.3.1-py3-none-any.whl.metadata (3.9 kB)
Collecting zstandard>=0.23.0 (from langsmith<1.0.0,>=0.3.45->langchain_core)
  Downloading zstandard-0.25.0-cp313-cp313-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (3.3 kB)
Collecting httpcore2==2.12.0 (from httpx2<3,>=2->langsmith<1.0.0,>=0.3.45->langchain_core)
  Downloading httpcore2-2.12.0-py3-none-any.whl.metadata (25 kB)
Collecting truststore>=0.10 (from httpx2<3,>=2->langsmith<1.0.0,>=0.3.45->langchain_core)
  Downloading truststore-0.10.4-py3-none-any.whl.metadata (4.4 kB)
Collecting annotated-types>=0.6.0 (from pydantic<3.0.0,>=2.7.4->langchain)
  Downloading annotated_types-0.8.0-py3-none-any.whl.metadata (15 kB)
Collecting pydantic-core==2.46.5 (from pydantic<3.0.0,>=2.7.4->langchain)
  Downloading pydantic_core-2.46.5-cp313-cp313-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (6.6 kB)
Collecting typing-inspection>=0.4.2 (from pydantic<3.0.0,>=2.7.4->langchain)
  Downloading typing_inspection-0.4.4-py3-none-any.whl.metadata (2.6 kB)
Collecting aiohttp<4.0.0,>=3.8.3 (from langchain_community)
  Downloading aiohttp-3.14.3-cp313-cp313-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl.metadata (8.3 kB)
Collecting httpx-sse<1.0.0,>=0.4.0 (from langchain_community)
  Downloading httpx_sse-0.4.3-py3-none-any.whl.metadata (9.7 kB)
Collecting langchain-classic<2.0.0,>=1.0.7 (from langchain_community)
  Downloading langchain_classic-1.0.8-py3-none-any.whl.metadata (5.1 kB)
Collecting numpy>=2.1.0 (from langchain_community)
  Downloading numpy-2.5.3-cp313-cp313-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl.metadata (6.6 kB)
Collecting pydantic-settings<3.0.0,>=2.10.1 (from langchain_community)
  Downloading pydantic_settings-2.15.0-py3-none-any.whl.metadata (3.9 kB)
Collecting sqlalchemy<3.0.0,>=1.4.0 (from langchain_community)
  Downloading sqlalchemy-2.0.52-cp313-cp313-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl.metadata (9.6 kB)
Collecting aiohappyeyeballs>=2.5.0 (from aiohttp<4.0.0,>=3.8.3->langchain_community)
  Downloading aiohappyeyeballs-2.7.1-py3-none-any.whl.metadata (5.9 kB)
Collecting aiosignal>=1.4.0 (from aiohttp<4.0.0,>=3.8.3->langchain_community)
  Downloading aiosignal-1.4.0-py3-none-any.whl.metadata (3.7 kB)
Collecting attrs>=17.3.0 (from aiohttp<4.0.0,>=3.8.3->langchain_community)
  Downloading attrs-26.1.0-py3-none-any.whl.metadata (8.8 kB)
Collecting frozenlist>=1.1.1 (from aiohttp<4.0.0,>=3.8.3->langchain_community)
  Downloading frozenlist-1.8.0-cp313-cp313-manylinux1_x86_64.manylinux_2_28_x86_64.manylinux_2_5_x86_64.whl.metadata (20 kB)
Collecting multidict<7.0,>=4.5 (from aiohttp<4.0.0,>=3.8.3->langchain_community)
  Downloading multidict-6.8.0-cp313-cp313-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl.metadata (5.3 kB)
Collecting propcache>=0.2.0 (from aiohttp<4.0.0,>=3.8.3->langchain_community)
  Downloading propcache-0.5.2-cp313-cp313-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl.metadata (16 kB)
Collecting yarl<2.0,>=1.17.0 (from aiohttp<4.0.0,>=3.8.3->langchain_community)
  Downloading yarl-1.24.5-cp313-cp313-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl.metadata (103 kB)
Collecting python-dotenv>=0.21.0 (from pydantic-settings<3.0.0,>=2.10.1->langchain_community)
  Downloading python_dotenv-1.2.3-py3-none-any.whl.metadata (29 kB)
Collecting charset_normalizer<4,>=2 (from requests>=2.0.0->langsmith<1.0.0,>=0.3.45->langchain_core)
  Downloading charset_normalizer-3.5.1-cp313-cp313-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl.metadata (45 kB)
Collecting urllib3<3,>=1.26 (from requests>=2.0.0->langsmith<1.0.0,>=0.3.45->langchain_core)
  Downloading urllib3-2.7.0-py3-none-any.whl.metadata (6.9 kB)
Collecting greenlet>=1 (from sqlalchemy<3.0.0,>=1.4.0->langchain_community)
  Downloading greenlet-3.5.5-cp313-cp313-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl.metadata (3.8 kB)
Downloading langchain-1.4.0-py3-none-any.whl (161 kB)
Downloading langchain_core-1.6.3-py3-none-any.whl (571 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 571.8/571.8 kB 276.2 MB/s  0:00:00
Downloading langgraph-1.2.11-py3-none-any.whl (248 kB)
Downloading httpx-0.28.1-py3-none-any.whl (73 kB)
Downloading httpcore-1.0.9-py3-none-any.whl (78 kB)
Downloading jsonpatch-1.33-py2.py3-none-any.whl (12 kB)
Downloading langgraph_checkpoint-4.2.0-py3-none-any.whl (56 kB)
Downloading langgraph_prebuilt-1.1.0-py3-none-any.whl (41 kB)
Downloading langgraph_sdk-0.4.4-py3-none-any.whl (162 kB)
Downloading langsmith-0.12.4-py3-none-any.whl (767 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 767.5/767.5 kB 640.8 MB/s  0:00:00
Downloading httpx2-2.12.0-py3-none-any.whl (95 kB)
Downloading httpcore2-2.12.0-py3-none-any.whl (83 kB)
Downloading pydantic-2.13.5-py3-none-any.whl (472 kB)
Downloading pydantic_core-2.46.5-cp313-cp313-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (2.1 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.1/2.1 MB 535.4 MB/s  0:00:00
Downloading pyyaml-6.0.3-cp313-cp313-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl (801 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 801.6/801.6 kB 522.9 MB/s  0:00:00
Downloading tenacity-9.1.4-py3-none-any.whl (28 kB)
Downloading typing_extensions-4.16.0-py3-none-any.whl (45 kB)
Downloading uuid_utils-0.17.1-cp313-cp313-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (323 kB)
Downloading websockets-16.1.1-cp313-cp313-manylinux1_x86_64.manylinux_2_28_x86_64.manylinux_2_5_x86_64.whl (187 kB)
Downloading langchain_community-0.4.2-py3-none-any.whl (2.4 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.4/2.4 MB 463.0 MB/s  0:00:00
Downloading aiohttp-3.14.3-cp313-cp313-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl (1.8 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.8/1.8 MB 714.3 MB/s  0:00:00
Downloading httpx_sse-0.4.3-py3-none-any.whl (9.0 kB)
Downloading langchain_classic-1.0.8-py3-none-any.whl (1.0 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.0/1.0 MB 702.4 MB/s  0:00:00
Downloading langchain_text_splitters-1.1.2-py3-none-any.whl (35 kB)
Downloading multidict-6.8.0-cp313-cp313-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl (287 kB)
Downloading pydantic_settings-2.15.0-py3-none-any.whl (69 kB)
Downloading requests-2.34.2-py3-none-any.whl (73 kB)
Downloading charset_normalizer-3.5.1-cp313-cp313-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl (250 kB)
Downloading idna-3.19-py3-none-any.whl (68 kB)
Downloading sqlalchemy-2.0.52-cp313-cp313-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl (3.3 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.3/3.3 MB 608.3 MB/s  0:00:00
Downloading urllib3-2.7.0-py3-none-any.whl (131 kB)
Downloading yarl-1.24.5-cp313-cp313-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl (110 kB)
Downloading aiohappyeyeballs-2.7.1-py3-none-any.whl (15 kB)
Downloading aiosignal-1.4.0-py3-none-any.whl (7.5 kB)
Downloading annotated_types-0.8.0-py3-none-any.whl (13 kB)
Downloading anyio-4.15.1-py3-none-any.whl (132 kB)
Downloading attrs-26.1.0-py3-none-any.whl (67 kB)
Downloading certifi-2026.7.22-py3-none-any.whl (136 kB)
Downloading distro-1.9.0-py3-none-any.whl (20 kB)
Downloading frozenlist-1.8.0-cp313-cp313-manylinux1_x86_64.manylinux_2_28_x86_64.manylinux_2_5_x86_64.whl (234 kB)
Downloading greenlet-3.5.5-cp313-cp313-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl (623 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 623.9/623.9 kB 687.6 MB/s  0:00:00
Downloading h11-0.16.0-py3-none-any.whl (37 kB)
Downloading jsonpointer-3.1.1-py3-none-any.whl (7.7 kB)
Downloading langchain_protocol-0.0.19-py3-none-any.whl (7.3 kB)
Downloading numpy-2.5.3-cp313-cp313-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl (16.7 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 16.7/16.7 MB 731.1 MB/s  0:00:00
Downloading orjson-3.12.0-cp313-cp313-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (131 kB)
Downloading ormsgpack-1.12.2-cp313-cp313-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (212 kB)
Downloading packaging-26.3-py3-none-any.whl (129 kB)
Downloading propcache-0.5.2-cp313-cp313-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl (61 kB)
Downloading python_dotenv-1.2.3-py3-none-any.whl (22 kB)
Downloading requests_toolbelt-1.0.0-py2.py3-none-any.whl (54 kB)
Downloading sniffio-1.3.1-py3-none-any.whl (10 kB)
Downloading truststore-0.10.4-py3-none-any.whl (18 kB)
Downloading typing_inspection-0.4.4-py3-none-any.whl (14 kB)
Downloading xxhash-4.0.1-cp313-cp313-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl (268 kB)
Downloading zstandard-0.25.0-cp313-cp313-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (5.5 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.5/5.5 MB 402.3 MB/s  0:00:00
Installing collected packages: zstandard, xxhash, websockets, uuid-utils, urllib3, typing-extensions, truststore, tenacity, sniffio, pyyaml, python-dotenv, propcache, packaging, ormsgpack, orjson, numpy, multidict, jsonpointer, idna, httpx-sse, h11, greenlet, frozenlist, distro, charset_normalizer, certifi, attrs, annotated-types, aiohappyeyeballs, yarl, typing-inspection, sqlalchemy, requests, pydantic-core, langchain-protocol, jsonpatch, httpcore2, httpcore, anyio, aiosignal, requests-toolbelt, pydantic, httpx2, httpx, aiohttp, pydantic-settings, langsmith, langchain_core, langgraph-sdk, langgraph-checkpoint, langchain-text-splitters, langgraph-prebuilt, langchain-classic, langgraph, langchain_community, langchain
  Attempting uninstall: zstandard
    Found existing installation: zstandard 0.25.0
    Uninstalling zstandard-0.25.0:
      Successfully uninstalled zstandard-0.25.0
  Attempting uninstall: xxhash
    Found existing installation: xxhash 4.0.1
    Uninstalling xxhash-4.0.1:
      Successfully uninstalled xxhash-4.0.1
  Attempting uninstall: websockets
    Found existing installation: websockets 17.1
    Uninstalling websockets-17.1:
      Successfully uninstalled websockets-17.1
  Attempting uninstall: uuid-utils
    Found existing installation: uuid_utils 0.17.1
    Uninstalling uuid_utils-0.17.1:
      Successfully uninstalled uuid_utils-0.17.1
  Attempting uninstall: urllib3
    Found existing installation: urllib3 2.7.0
    Uninstalling urllib3-2.7.0:
      Successfully uninstalled urllib3-2.7.0
  Attempting uninstall: typing-extensions
    Found existing installation: typing_extensions 4.16.0
    Uninstalling typing_extensions-4.16.0:
      Successfully uninstalled typing_extensions-4.16.0
  Attempting uninstall: truststore
    Found existing installation: truststore 0.10.4
    Uninstalling truststore-0.10.4:
      Successfully uninstalled truststore-0.10.4
  Attempting uninstall: tenacity
    Found existing installation: tenacity 9.1.4
    Uninstalling tenacity-9.1.4:
      Successfully uninstalled tenacity-9.1.4
  Attempting uninstall: sniffio
    Found existing installation: sniffio 1.3.1
    Uninstalling sniffio-1.3.1:
      Successfully uninstalled sniffio-1.3.1
  Attempting uninstall: pyyaml
    Found existing installation: PyYAML 6.0.3
    Uninstalling PyYAML-6.0.3:
      Successfully uninstalled PyYAML-6.0.3
  Attempting uninstall: python-dotenv
    Found existing installation: python-dotenv 1.2.3
    Uninstalling python-dotenv-1.2.3:
      Successfully uninstalled python-dotenv-1.2.3
  Attempting uninstall: propcache
    Found existing installation: propcache 0.5.2
    Uninstalling propcache-0.5.2:
      Successfully uninstalled propcache-0.5.2
  Attempting uninstall: packaging
    Found existing installation: packaging 26.3
    Uninstalling packaging-26.3:
      Successfully uninstalled packaging-26.3
  Attempting uninstall: ormsgpack
    Found existing installation: ormsgpack 1.12.2
    Uninstalling ormsgpack-1.12.2:
      Successfully uninstalled ormsgpack-1.12.2
  Attempting uninstall: orjson
    Found existing installation: orjson 3.12.0
    Uninstalling orjson-3.12.0:
      Successfully uninstalled orjson-3.12.0
  Attempting uninstall: numpy
    Found existing installation: numpy 2.5.3
    Uninstalling numpy-2.5.3:
      Successfully uninstalled numpy-2.5.3
  Attempting uninstall: multidict

Instalando bibliotecas de visualização e PDF (matplotlib, seaborn, pypdf)...
Instalação de todas as bibliotecas concluída!

Verificando versões instaladas de pacotes chave:
Name: packaging
Version: 26.3
Summary: Core utilities for Python packages
Home-page:
Author:
Author-email: Donald Stufft <donald@stufft.io>
License-Expression: Apache-2.0 OR BSD-2-Clause
Location: /usr/local/lib/python3.13/dist-packages
Requires:
Required-by: accelerate, altair, arviz, astropy, bigquery-magics, bitsandbytes, bokeh, cudf-cu12, cudf-polars-cu12, cuml-cu12, dask, dataproc-spark-connect, datasets, db-dtypes, deprecation, distributed, faiss-cpu, fastai, geopandas, google-adk, google-cloud-bigquery, gradio, gradio_client, h5netcdf, huggingface_hub, ipykernel, jupyter-events, jupyter_server, jupytext, kaggle, kagglehub, keras, keras-hub, langchain-core, langsmith, lazy-loader, libpysal, matplotlib, momepy, nbconvert, nibabel, numba-cuda, pandas-gbq, panel, panel-material-ui, patsy, peft, plotly, pooch, pylibcudf-cu12, pyogrio, pysal, pytest, scikit-image, shap, spacy, Sphinx, splot, statsmodels, tables, tensorboard, tensorflow, thinc, transformers, treelite, unsloth_zoo, wandb, weasel, wheel, xarray
Name: numpy
Version: 2.5.3
Summary: Fundamental package for array computing in Python
Home-page: https://numpy.org
Author: Travis E. Oliphant et al.
Author-email:
License-Expression: BSD-3-Clause AND 0BSD AND MIT AND Zlib AND CC0-1.0
Location: /usr/local/lib/python3.13/dist-packages
Requires:
Required-by: accelerate, access, albucore, albumentations, ale-py, arviz, astropy, autograd, bigframes, bitsandbytes, blis, blosc2, bokeh, Bottleneck, bqplot, clarabel, cmdstanpy, contourpy, cucim-cu12, cuda-core, cudf-cu12, cufflinks, cuml-cu12, cupy-cuda12x, cuvs-cu12, cvxpy, cyipopt, dask-cuda, dask-cudf-cu12, datasets, db-dtypes, diffusers, dm-tree, dopamine_rl, esda, faiss-cpu, flax, folium, formulaic, geemap, geopandas, gradio, grain, gym, gymnasium, h5netcdf, h5py, hdbscan, highspy, holoviews, hyperopt, ImageIO, imbalanced-learn, inequality, jax, jaxlib, keras, keras-hub, langchain-community, libpysal, librosa, lightgbm, mapclassify, matplotlib, matplotlib-venn, mgwr, missingno, mizani, ml_dtypes, mlxtend, moviepy, music21, nibabel, numba, numexpr, nx-cugraph-cu12, opencv-contrib-python, opencv-python, opencv-python-headless, optax, orbax-checkpoint, osqp, pandas, pandas-gbq, pandas-stubs, patsy, peft, plotnine, pointpats, prophet, pycocotools, pyerfa, pylibcugraph-cu12, pylibraft-cu12, pymc, pyogrio, pysal, pytensor, python-louvain, PyWavelets, quantecon, rasterio, rasterstats, rmm-cu12, scikit-image, scikit-learn, scipy, scs, seaborn, segregation, sentence-transformers, shap, shapely, sklearn-pandas, soundfile, soxr, spacy, spaghetti, spanner-graph-notebook, spglm, spint, splot, spopt, spreg, stanio, statsmodels, stumpy, tables, tensorboard, tensorflow, tensorflow-datasets, tensorflow-hub, tensorflow-probability, tensorstore, thinc, tifffile, tobler, torchtune, torchvision, transformers, treelite, treescope, tsfresh, ucxx-cu12, umap-learn, unsloth_zoo, wordcloud, xarray, xarray-einstats, xgboost, ydf, yellowbrick, yfinance
Name: pandas
Version: 2.2.3
Summary: Powerful data structures for data analysis, time series, and statistics
Home-page: https://pandas.pydata.org
Author:
Author-email: The Pandas Development Team <pandas-dev@python.org>
License: BSD 3-Clause License

Copyright (c) 2008-2011, AQR Capital Management, LLC, Lambda Foundry, Inc. and PyData Development Team
All rights reserved.

Copyright (c) 2011-2023, Open source contributors.

Redistribution and use in source and binary forms, with or without
modification, are permitted provided that the following conditions are met:

* Redistributions of source code must retain the above copyright notice, this
  list of conditions and the following disclaimer.

* Redistributions in binary form must reproduce the above copyright notice,
  this list of conditions and the following disclaimer in the documentation
  and/or other materials provided with the distribution.

* Neither the name of the copyright holder nor the names of its
  contributors may be used to endorse or promote products derived from
  this software without specific prior written permission.

THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE
FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
Copyright (c) 2010-2019 Keith Goodman
Copyright (c) 2019 Bottleneck Developers
All rights reserved.

Redistribution and use in source and binary forms, with or without
modification, are permitted provided that the following conditions are met:

    * Redistributions of source code must retain the above copyright notice,
      this list of conditions and the following disclaimer.

    * Redistributions in binary form must reproduce the above copyright
      notice, this list of conditions and the following disclaimer in the
      documentation and/or other materials provided with the distribution.

THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE
LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
POSSIBILITY OF SUCH DAMAGE.Copyright 2017- Paul Ganssle <paul@ganssle.io>
Copyright 2017- dateutil contributors (see AUTHORS file)

   Licensed under the Apache License, Version 2.0 (the "License");
   you may not use this file except in compliance with the License.
   You may obtain a copy of the License at

       http://www.apache.org/licenses/LICENSE-2.0

   Unless required by applicable law or agreed to in writing, software
   distributed under the License is distributed on an "AS IS" BASIS,
   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
   See the License for the specific language governing permissions and
   limitations under the License.

The above license applies to all contributions after 2017-12-01, as well as
all contributions that have been re-licensed (see AUTHORS file for the list of
contributors who have re-licensed their code).
--------------------------------------------------------------------------------
dateutil - Extensions to the standard Python datetime module.

Copyright (c) 2003-2011 - Gustavo Niemeyer <gustavo@niemeyer.net>
Copyright (c) 2012-2014 - Tomi Pieviläinen <tomi.pievilainen@iki.fi>
Copyright (c) 2014-2016 - Yaron de Leeuw <me@jarondl.net>
Copyright (c) 2015-     - Paul Ganssle <paul@ganssle.io>
Copyright (c) 2015-     - dateutil contributors (see AUTHORS file)

All rights reserved.

Redistribution and use in source and binary forms, with or without
modification, are permitted provided that the following conditions are met:

    * Redistributions of source code must retain the above copyright notice,
      this list of conditions and the following disclaimer.
    * Redistributions in binary form must reproduce the above copyright notice,
      this list of conditions and the following disclaimer in the documentation
      and/or other materials provided with the distribution.
    * Neither the name of the copyright holder nor the names of its
      contributors may be used to endorse or promote products derived from
      this software without specific prior written permission.

THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
"AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR
CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL,
EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,
PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR
PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF
LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING
NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

The above BSD License Applies to all code, even that also covered by Apache 2.0.# MIT License

Copyright (c) 2019 Hadley Wickham; RStudio; and Evan Miller

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.
Based on http://opensource.org/licenses/MIT

This is a template. Complete and ship as file LICENSE the following 2
lines (only)

YEAR:
COPYRIGHT HOLDER:

and specify as

License: MIT + file LICENSE

Copyright (c) <YEAR>, <COPYRIGHT HOLDER>

Permission is hereby granted, free of charge, to any person obtaining
a copy of this software and associated documentation files (the
"Software"), to deal in the Software without restriction, including
without limitation the rights to use, copy, modify, merge, publish,
distribute, sublicense, and/or sell copies of the Software, and to
permit persons to whom the Software is furnished to do so, subject to
the following conditions:

The above copyright notice and this permission notice shall be
included in all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE
LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION
OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION
WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
The MIT License

Copyright (c) 2008-     Attractive Chaos <attractor@live.co.uk>

Permission is hereby granted, free of charge, to any person obtaining
a copy of this software and associated documentation files (the
"Software"), to deal in the Software without restriction, including
without limitation the rights to use, copy, modify, merge, publish,
distribute, sublicense, and/or sell copies of the Software, and to
permit persons to whom the Software is furnished to do so, subject to
the following conditions:

The above copyright notice and this permission notice shall be
included in all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS
BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN
ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.musl as a whole is licensed under the following standard MIT license:

----------------------------------------------------------------------
Copyright © 2005-2020 Rich Felker, et al.

Permission is hereby granted, free of charge, to any person obtaining
a copy of this software and associated documentation files (the
"Software"), to deal in the Software without restriction, including
without limitation the rights to use, copy, modify, merge, publish,
distribute, sublicense, and/or sell copies of the Software, and to
permit persons to whom the Software is furnished to do so, subject to
the following conditions:

The above copyright notice and this permission notice shall be
included in all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.
IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY
CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT,
TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE
SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
----------------------------------------------------------------------

Authors/contributors include:

A. Wilcox
Ada Worcester
Alex Dowad
Alex Suykov
Alexander Monakov
Andre McCurdy
Andrew Kelley
Anthony G. Basile
Aric Belsito
Arvid Picciani
Bartosz Brachaczek
Benjamin Peterson
Bobby Bingham
Boris Brezillon
Brent Cook
Chris Spiegel
Clément Vasseur
Daniel Micay
Daniel Sabogal
Daurnimator
David Carlier
David Edelsohn
Denys Vlasenko
Dmitry Ivanov
Dmitry V. Levin
Drew DeVault
Emil Renner Berthing
Fangrui Song
Felix Fietkau
Felix Janda
Gianluca Anzolin
Hauke Mehrtens
He X
Hiltjo Posthuma
Isaac Dunham
Jaydeep Patil
Jens Gustedt
Jeremy Huntwork
Jo-Philipp Wich
Joakim Sindholt
John Spencer
Julien Ramseier
Justin Cormack
Kaarle Ritvanen
Khem Raj
Kylie McClain
Leah Neukirchen
Luca Barbato
Luka Perkov
M Farkas-Dyck (Strake)
Mahesh Bodapati
Markus Wichmann
Masanori Ogino
Michael Clark
Michael Forney
Mikhail Kremnyov
Natanael Copa
Nicholas J. Kain
orc
Pascal Cuoq
Patrick Oppenlander
Petr Hosek
Petr Skocik
Pierre Carrier
Reini Urban
Rich Felker
Richard Pennington
Ryan Fairfax
Samuel Holland
Segev Finer
Shiz
sin
Solar Designer
Stefan Kristiansson
Stefan O'Rear
Szabolcs Nagy
Timo Teräs
Trutz Behn
Valentin Ochs
Will Dietz
William Haddon
William Pitcock

Portions of this software are derived from third-party works licensed
under terms compatible with the above MIT license:

The TRE regular expression implementation (src/regex/reg* and
src/regex/tre*) is Copyright © 2001-2008 Ville Laurikari and licensed
under a 2-clause BSD license (license text in the source files). The
included version has been heavily modified by Rich Felker in 2012, in
the interests of size, simplicity, and namespace cleanliness.

Much of the math library code (src/math/* and src/complex/*) is
Copyright © 1993,2004 Sun Microsystems or
Copyright © 2003-2011 David Schultz or
Copyright © 2003-2009 Steven G. Kargl or
Copyright © 2003-2009 Bruce D. Evans or
Copyright © 2008 Stephen L. Moshier or
Copyright © 2017-2018 Arm Limited
and labelled as such in comments in the individual source files. All
have been licensed under extremely permissive terms.

The ARM memcpy code (src/string/arm/memcpy.S) is Copyright © 2008
The Android Open Source Project and is licensed under a two-clause BSD
license. It was taken from Bionic libc, used on Android.

The AArch64 memcpy and memset code (src/string/aarch64/*) are
Copyright © 1999-2019, Arm Limited.

The implementation of DES for crypt (src/crypt/crypt_des.c) is
Copyright © 1994 David Burren. It is licensed under a BSD license.

The implementation of blowfish crypt (src/crypt/crypt_blowfish.c) was
originally written by Solar Designer and placed into the public
domain. The code also comes with a fallback permissive license for use
in jurisdictions that may not recognize the public domain.

The smoothsort implementation (src/stdlib/qsort.c) is Copyright © 2011
Valentin Ochs and is licensed under an MIT-style license.

The x86_64 port was written by Nicholas J. Kain and is licensed under
the standard MIT terms.

The mips and microblaze ports were originally written by Richard
Pennington for use in the ellcc project. The original code was adapted
by Rich Felker for build system and code conventions during upstream
integration. It is licensed under the standard MIT terms.

The mips64 port was contributed by Imagination Technologies and is
licensed under the standard MIT terms.

The powerpc port was also originally written by Richard Pennington,
and later supplemented and integrated by John Spencer. It is licensed
under the standard MIT terms.

All other files which have no copyright comments are original works
produced specifically for use as part of this library, written either
by Rich Felker, the main author of the library, or by one or more
contibutors listed above. Details on authorship of individual files
can be found in the git version control history of the project. The
omission of copyright and license comments in each file is in the
interest of source tree size.

In addition, permission is hereby granted for all public header files
(include/* and arch/*/bits/*) and crt files intended to be linked into
applications (crt/*, ldso/dlstart.c, and arch/*/crt_arch.h) to omit
the copyright notice and permission notice otherwise required by the
license, and to use these files without any requirement of
attribution. These files include substantial contributions from:

Bobby Bingham
John Spencer
Nicholas J. Kain
Rich Felker
Richard Pennington
Stefan Kristiansson
Szabolcs Nagy

all of whom have explicitly granted such permission.

This file previously contained text expressing a belief that most of
the files covered by the above exception were sufficiently trivial not
to be subject to copyright, resulting in confusion over whether it
negated the permissions granted in the license. In the spirit of
permissive licensing, and of not having licensing issues being an
obstacle to adoption, that text has been removed.Copyright (c) 2005-2023, NumPy Developers.
All rights reserved.

Redistribution and use in source and binary forms, with or without
modification, are permitted provided that the following conditions are
met:

    * Redistributions of source code must retain the above copyright
       notice, this list of conditions and the following disclaimer.

    * Redistributions in binary form must reproduce the above
       copyright notice, this list of conditions and the following
       disclaimer in the documentation and/or other materials provided
       with the distribution.

    * Neither the name of the NumPy Developers nor the names of any
       contributors may be used to endorse or promote products derived
       from this software without specific prior written permission.

THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
"AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT

In [2]:
try:
    import langchain
    import langchain_community
    import langchain_core
    import langchain_text_splitters
    print("LangChain e módulos relacionados importados com sucesso!")
except ImportError as e:
    print(f"Erro ao importar módulos do LangChain: {e}")
    print("Pode ser necessário reiniciar o ambiente de execução (Runtime -> Restart runtime) e tentar novamente.")

/tmp/ipykernel_17862/1390487792.py:3: DeprecationWarning: `langchain-community` is being sunset and is no longer actively maintained. See https://github.com/langchain-ai/langchain-community/issues/674 for details and migration guidance toward standalone integration packages.
  import langchain_community
WARNING:torchao:Failed to load /usr/local/lib/python3.13/dist-packages/torchao/_C_cutlass_90a.abi3.so: Could not load this library: /usr/local/lib/python3.13/dist-packages/torchao/_C_cutlass_90a.abi3.so
WARNING:torchao:Failed to load /usr/local/lib/python3.13/dist-packages/torchao/_C_mxfp8.cpython-310-x86_64-linux-gnu.so: Could not load this library: /usr/local/lib/python3.13/dist-packages/torchao/_C_mxfp8.cpython-310-x86_64-linux-gnu.so

LangChain e módulos relacionados importados com sucesso!

In [3]:
import os
import site

try:
    import langchain
    print(f"Pacote 'langchain' importado de: {langchain.__path__[0]}")

    # Tenta importar funções específicas de langchain.chains para verificar sua existência
    from langchain.chains.combine_documents import create_stuff_documents_chain
    from langchain.chains.retrieval import create_retrieval_chain
    print("Funções 'create_stuff_documents_chain' e 'create_retrieval_chain' importadas com sucesso!")

except ImportError as e:
    print(f"Erro ao importar módulos de 'langchain.chains': {e}")
    print("Isso pode indicar que o ambiente de execução precisa ser reiniciado ou que há um problema na instalação da versão correta do LangChain.")
except Exception as e:
    print(f"Ocorreu um erro inesperado ao inspecionar o pacote LangChain: {e}")

Pacote 'langchain' importado de: /usr/local/lib/python3.13/dist-packages/langchain
Erro ao importar módulos de 'langchain.chains': No module named 'langchain.chains'
Isso pode indicar que o ambiente de execução precisa ser reiniciado ou que há um problema na instalação da versão correta do LangChain.

In [4]:
# Tentativa de instalação do Unsloth conforme solicitado pelo usuário.
# Lembre-se: uma GPU ativa é crucial para que esta instalação seja bem-sucedida.
!pip install "unsloth[colab-new] @ git+https://github.com/unslothai/unsloth.git"
print("Comando de instalação do Unsloth executado. Verifique os logs acima para confirmação de sucesso.")

Collecting unsloth @ git+https://github.com/unslothai/unsloth.git (from unsloth[colab-new] @ git+https://github.com/unslothai/unsloth.git)
  Cloning https://github.com/unslothai/unsloth.git to /tmp/pip-install-6wxhmn6v/unsloth_c8c043f3405245ab87e61afc212c8673
  Running command git clone --filter=blob:none --quiet https://github.com/unslothai/unsloth.git /tmp/pip-install-6wxhmn6v/unsloth_c8c043f3405245ab87e61afc212c8673
  Resolved https://github.com/unslothai/unsloth.git to commit a32099207f8e185101353e606a26cc0f14249409
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Requirement already satisfied: typer>=0.12.0 in /usr/local/lib/python3.13/dist-packages (from unsloth @ git+https://github.com/unslothai/unsloth.git->unsloth[colab-new] @ git+https://github.com/unslothai/unsloth.git) (0.27.2)
Requirement already satisfied: rich in /usr/local/lib/python3.13/dist-packages (from unsloth @ git+https://github.com/unslothai/unsloth.git->unsloth[colab-new] @ git+https://github.com/unslothai/unsloth.git) (13.9.4)
Requirement already satisfied: pydantic in /usr/local/lib/python3.13/dist-packages (from unsloth @ git+https://github.com/unslothai/unsloth.git->unsloth[colab-new] @ git+https://github.com/unslothai/unsloth.git) (2.13.5)
Requirement already satisfied: pyyaml in /usr/local/lib/python3.13/dist-packages (from unsloth @ git+https://github.com/unslothai/unsloth.git->unsloth[colab-new] @ git+https://github.com/unslothai/unsloth.git) (6.0.3)
Requirement already satisfied: nest-asyncio in /usr/local/lib/python3.13/dist-packages (from unsloth @ git+https://github.com/unslothai/unsloth.git->unsloth[colab-new] @ git+https://github.com/unslothai/unsloth.git) (1.6.0)
Requirement already satisfied: huggingface-hub>=0.34.0 in /usr/local/lib/python3.13/dist-packages (from unsloth @ git+https://github.com/unslothai/unsloth.git->unsloth[colab-new] @ git+https://github.com/unslothai/unsloth.git) (1.29.0)
Requirement already satisfied: structlog>=24.1.0 in /usr/local/lib/python3.13/dist-packages (from unsloth @ git+https://github.com/unslothai/unsloth.git->unsloth[colab-new] @ git+https://github.com/unslothai/unsloth.git) (26.1.0)
Requirement already satisfied: click>=8.0 in /usr/local/lib/python3.13/dist-packages (from unsloth @ git+https://github.com/unslothai/unsloth.git->unsloth[colab-new] @ git+https://github.com/unslothai/unsloth.git) (8.5.0)
Requirement already satisfied: unsloth_zoo>=2026.9.3 in /usr/local/lib/python3.13/dist-packages (from unsloth @ git+https://github.com/unslothai/unsloth.git->unsloth[colab-new] @ git+https://github.com/unslothai/unsloth.git) (2026.9.3)
Requirement already satisfied: packaging in /usr/local/lib/python3.13/dist-packages (from unsloth @ git+https://github.com/unslothai/unsloth.git->unsloth[colab-new] @ git+https://github.com/unslothai/unsloth.git) (26.3)
Requirement already satisfied: tyro in /usr/local/lib/python3.13/dist-packages (from unsloth @ git+https://github.com/unslothai/unsloth.git->unsloth[colab-new] @ git+https://github.com/unslothai/unsloth.git) (1.0.16)
Requirement already satisfied: transformers!=4.52.0,!=4.52.1,!=4.52.2,!=4.52.3,!=4.53.0,!=4.54.0,!=4.55.0,!=4.55.1,!=4.57.0,!=4.57.4,!=4.57.5,!=5.0.0,!=5.1.0,<=5.5.0,>=4.51.3 in /usr/local/lib/python3.13/dist-packages (from unsloth @ git+https://github.com/unslothai/unsloth.git->unsloth[colab-new] @ git+https://github.com/unslothai/unsloth.git) (5.5.0)
Requirement already satisfied: datasets!=4.0.*,!=4.1.0,<4.4.0,>=3.4.1 in /usr/local/lib/python3.13/dist-packages (from unsloth @ git+https://github.com/unslothai/unsloth.git->unsloth[colab-new] @ git+https://github.com/unslothai/unsloth.git) (4.3.0)
Requirement already satisfied: sentencepiece>=0.2.0 in /usr/local/lib/python3.13/dist-packages (from unsloth @ git+https://github.com/unslothai/unsloth.git->unsloth[colab-new] @ git+https://github.com/unslothai/unsloth.git) (0.2.2)
Requirement already satisfied: tqdm in /usr/local/lib/python3.13/dist-packages (from unsloth @ git+https://github.com/unslothai/unsloth.git->unsloth[colab-new] @ git+https://github.com/unslothai/unsloth.git) (4.67.3)
Requirement already satisfied: psutil in /usr/local/lib/python3.13/dist-packages (from unsloth @ git+https://github.com/unslothai/unsloth.git->unsloth[colab-new] @ git+https://github.com/unslothai/unsloth.git) (5.9.5)
Requirement already satisfied: wheel>=0.42.0 in /usr/local/lib/python3.13/dist-packages (from unsloth @ git+https://github.com/unslothai/unsloth.git->unsloth[colab-new] @ git+https://github.com/unslothai/unsloth.git) (0.48.0)
Requirement already satisfied: numpy in /usr/local/lib/python3.13/dist-packages (from unsloth @ git+https://github.com/unslothai/unsloth.git->unsloth[colab-new] @ git+https://github.com/unslothai/unsloth.git) (2.5.3)
Requirement already satisfied: protobuf in /usr/local/lib/python3.13/dist-packages (from unsloth @ git+https://github.com/unslothai/unsloth.git->unsloth[colab-new] @ git+https://github.com/unslothai/unsloth.git) (5.29.6)
Requirement already satisfied: hf_transfer in /usr/local/lib/python3.13/dist-packages (from unsloth @ git+https://github.com/unslothai/unsloth.git->unsloth[colab-new] @ git+https://github.com/unslothai/unsloth.git) (0.1.9)
Requirement already satisfied: bitsandbytes!=0.46.0,!=0.48.0,>=0.45.5 in /usr/local/lib/python3.13/dist-packages (from unsloth @ git+https://github.com/unslothai/unsloth.git->unsloth[colab-new] @ git+https://github.com/unslothai/unsloth.git) (0.50.2)
Requirement already satisfied: sentence-transformers in /usr/local/lib/python3.13/dist-packages (from unsloth @ git+https://github.com/unslothai/unsloth.git->unsloth[colab-new] @ git+https://github.com/unslothai/unsloth.git) (5.7.0)
Requirement already satisfied: filelock in /usr/local/lib/python3.13/dist-packages (from datasets!=4.0.*,!=4.1.0,<4.4.0,>=3.4.1->unsloth @ git+https://github.com/unslothai/unsloth.git->unsloth[colab-new] @ git+https://github.com/unslothai/unsloth.git) (3.32.5)
Requirement already satisfied: pyarrow>=21.0.0 in /usr/local/lib/python3.13/dist-packages (from datasets!=4.0.*,!=4.1.0,<4.4.0,>=3.4.1->unsloth @ git+https://github.com/unslothai/unsloth.git->unsloth[colab-new] @ git+https://github.com/unslothai/unsloth.git) (23.0.1)
Requirement already satisfied: dill<0.4.1,>=0.3.0 in /usr/local/lib/python3.13/dist-packages (from datasets!=4.0.*,!=4.1.0,<4.4.0,>=3.4.1->unsloth @ git+https://github.com/unslothai/unsloth.git->unsloth[colab-new] @ git+https://github.com/unslothai/unsloth.git) (0.4.0)
Requirement already satisfied: pandas in /usr/local/lib/python3.13/dist-packages (from datasets!=4.0.*,!=4.1.0,<4.4.0,>=3.4.1->unsloth @ git+https://github.com/unslothai/unsloth.git->unsloth[colab-new] @ git+https://github.com/unslothai/unsloth.git) (2.2.3)
Requirement already satisfied: requests>=2.32.2 in /usr/local/lib/python3.13/dist-packages (from datasets!=4.0.*,!=4.1.0,<4.4.0,>=3.4.1->unsloth @ git+https://github.com/unslothai/unsloth.git->unsloth[colab-new] @ git+https://github.com/unslothai/unsloth.git) (2.34.2)
Requirement already satisfied: httpx<1.0.0 in /usr/local/lib/python3.13/dist-packages (from datasets!=4.0.*,!=4.1.0,<4.4.0,>=3.4.1->unsloth @ git+https://github.com/unslothai/unsloth.git->unsloth[colab-new] @ git+https://github.com/unslothai/unsloth.git) (0.28.1)
Requirement already satisfied: xxhash in /usr/local/lib/python3.13/dist-packages (from datasets!=4.0.*,!=4.1.0,<4.4.0,>=3.4.1->unsloth @ git+https://github.com/unslothai/unsloth.git->unsloth[colab-new] @ git+https://github.com/unslothai/unsloth.git) (4.0.1)
Requirement already satisfied: multiprocess<0.70.17 in /usr/local/lib/python3.13/dist-packages (from datasets!=4.0.*,!=4.1.0,<4.4.0,>=3.4.1->unsloth @ git+https://github.com/unslothai/unsloth.git->unsloth[colab-new] @ git+https://github.com/unslothai/unsloth.git) (0.70.16)
Requirement already satisfied: fsspec<=2025.9.0,>=2023.1.0 in /usr/local/lib/python3.13/dist-packages (from fsspec[http]<=2025.9.0,>=2023.1.0->datasets!=4.0.*,!=4.1.0,<4.4.0,>=3.4.1->unsloth @ git+https://github.com/unslothai/unsloth.git->unsloth[colab-new] @ git+https://github.com/unslothai/unsloth.git) (2025.9.0)
Requirement already satisfied: aiohttp!=4.0.0a0,!=4.0.0a1 in /usr/local/lib/python3.13/dist-packages (from fsspec[http]<=2025.9.0,>=2023.1.0->datasets!=4.0.*,!=4.1.0,<4.4.0,>=3.4.1->unsloth @ git+https://github.com/unslothai/unsloth.git->unsloth[colab-new] @ git+https://github.com/unslothai/unsloth.git) (3.14.3)
Requirement already satisfied: anyio in /usr/local/lib/python3.13/dist-packages (from httpx<1.0.0->datasets!=4.0.*,!=4.1.0,<4.4.0,>=3.4.1->unsloth @ git+https://github.com/unslothai/unsloth.git->unsloth[colab-new] @ git+https://github.com/unslothai/unsloth.git) (4.15.1)
Requirement already satisfied: certifi in /usr/local/lib/python3.13/dist-packages (from httpx<1.0.0->datasets!=4.0.*,!=4.1.0,<4.4.0,>=3.4.1->unsloth @ git+https://github.com/unslothai/unsloth.git->unsloth[colab-new] @ git+https://github.com/unslothai/unsloth.git) (2026.7.22)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.13/dist-packages (from httpx<1.0.0->datasets!=4.0.*,!=4.1.0,<4.4.0,>=3.4.1->unsloth @ git+https://github.com/unslothai/unsloth.git->unsloth[colab-new] @ git+https://github.com/unslothai/unsloth.git) (1.0.9)
Requirement already satisfied: idna in /usr/local/lib/python3.13/dist-packages (from httpx<1.0.0->datasets!=4.0.*,!=4.1.0,<4.4.0,>=3.4.1->unsloth @ git+https://github.com/unslothai/unsloth.git->unsloth[colab-new] @ git+https://github.com/unslothai/unsloth.git) (3.19)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.13/dist-packages (from httpcore==1.*->httpx<1.0.0->datasets!=4.0.*,!=4.1.0,<4.4.0,>=3.4.1->unsloth @ git+https://github.com/unslothai/unsloth.git->unsloth[colab-new] @ git+https://github.com/unslothai/unsloth.git) (0.16.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.5.2 in /usr/local/lib/python3.13/dist-packages (from huggingface-hub>=0.34.0->unsloth @ git+https://github.com/unslothai/unsloth.git->unsloth[colab-new] @ git+https://github.com/unslothai/unsloth.git) (1.6.0)
Requirement already satisfied: typing-extensions>=4.1.0 in /usr/local/lib/python3.13/dist-packages (from huggingface-hub>=0.34.0->unsloth @ git+https://github.com/unslothai/unsloth.git->unsloth[colab-new] @ git+https://github.com/unslothai/unsloth.git) (4.16.0)
Requirement already satisfied: regex>=2025.10.22 in /usr/local/lib/python3.13/dist-packages (from transformers!=4.52.0,!=4.52.1,!=4.52.2,!=4.52.3,!=4.53.0,!=4.54.0,!=4.55.0,!=4.55.1,!=4.57.0,!=4.57.4,!=4.57.5,!=5.0.0,!=5.1.0,<=5.5.0,>=4.51.3->unsloth @ git+https://github.com/unslothai/unsloth.git->unsloth[colab-new] @ git+https://github.com/unslothai/unsloth.git) (2025.11.3)
Requirement already satisfied: tokenizers<=0.23.0,>=0.22.0 in /usr/local/lib/python3.13/dist-packages (from transformers!=4.52.0,!=4.52.1,!=4.52.2,!=4.52.3,!=4.53.0,!=4.54.0,!=4.55.0,!=4.55.1,!=4.57.0,!=4.57.4,!=4.57.5,!=5.0.0,!=5.1.0,<=5.5.0,>=4.51.3->unsloth @ git+https://github.com/unslothai/unsloth.git->unsloth[colab-new] @ git+https://github.com/unslothai/unsloth.git) (0.22.2)
Requirement already satisfied: safetensors>=0.4.3 in /usr/local/lib/python3.13/dist-packages (from transformers!=4.52.0,!=4.52.1,!=4.52.2,!=4.52.3,!=4.53.0,!=4.54.0,!=4.55.0,!=4.55.1,!=4.57.0,!=4.57.4,!=4.57.5,!=5.0.0,!=5.1.0,<=5.5.0,>=4.51.3->unsloth @ git+https://github.com/unslothai/unsloth.git->unsloth[colab-new] @ git+https://github.com/unslothai/unsloth.git) (0.8.0)
Requirement already satisfied: aiohappyeyeballs>=2.5.0 in /usr/local/lib/python3.13/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.9.0,>=2023.1.0->datasets!=4.0.*,!=4.1.0,<4.4.0,>=3.4.1->unsloth @ git+https://github.com/unslothai/unsloth.git->unsloth[colab-new] @ git+https://github.com/unslothai/unsloth.git) (2.7.1)
Requirement already satisfied: aiosignal>=1.4.0 in /usr/local/lib/python3.13/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.9.0,>=2023.1.0->datasets!=4.0.*,!=4.1.0,<4.4.0,>=3.4.1->unsloth @ git+https://github.com/unslothai/unsloth.git->unsloth[colab-new] @ git+https://github.com/unslothai/unsloth.git) (1.4.0)
Requirement already satisfied: attrs>=17.3.0 in /usr/local/lib/python3.13/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.9.0,>=2023.1.0->datasets!=4.0.*,!=4.1.0,<4.4.0,>=3.4.1->unsloth @ git+https://github.com/unslothai/unsloth.git->unsloth[colab-new] @ git+https://github.com/unslothai/unsloth.git) (26.1.0)
Requirement already satisfied: frozenlist>=1.1.1 in /usr/local/lib/python3.13/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.9.0,>=2023.1.0->datasets!=4.0.*,!=4.1.0,<4.4.0,>=3.4.1->unsloth @ git+https://github.com/unslothai/unsloth.git->unsloth[colab-new] @ git+https://github.com/unslothai/unsloth.git) (1.8.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /usr/local/lib/python3.13/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.9.0,>=2023.1.0->datasets!=4.0.*,!=4.1.0,<4.4.0,>=3.4.1->unsloth @ git+https://github.com/unslothai/unsloth.git->unsloth[colab-new] @ git+https://github.com/unslothai/unsloth.git) (6.8.0)
Requirement already satisfied: propcache>=0.2.0 in /usr/local/lib/python3.13/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.9.0,>=2023.1.0->datasets!=4.0.*,!=4.1.0,<4.4.0,>=3.4.1->unsloth @ git+https://github.com/unslothai/unsloth.git->unsloth[colab-new] @ git+https://github.com/unslothai/unsloth.git) (0.5.2)
Requirement already satisfied: yarl<2.0,>=1.17.0 in /usr/local/lib/python3.13/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.9.0,>=2023.1.0->datasets!=4.0.*,!=4.1.0,<4.4.0,>=3.4.1->unsloth @ git+https://github.com/unslothai/unsloth.git->unsloth[colab-new] @ git+https://github.com/unslothai/unsloth.git) (1.24.5)
Requirement already satisfied: torch<3,>=2.4 in /usr/local/lib/python3.13/dist-packages (from bitsandbytes!=0.46.0,!=0.48.0,>=0.45.5->unsloth @ git+https://github.com/unslothai/unsloth.git->unsloth[colab-new] @ git+https://github.com/unslothai/unsloth.git) (2.11.0+cu128)
Requirement already satisfied: setuptools<82 in /usr/local/lib/python3.13/dist-packages (from torch<3,>=2.4->bitsandbytes!=0.46.0,!=0.48.0,>=0.45.5->unsloth @ git+https://github.com/unslothai/unsloth.git->unsloth[colab-new] @ git+https://github.com/unslothai/unsloth.git) (80.10.2)
Requirement already satisfied: sympy>=1.13.3 in /usr/local/lib/python3.13/dist-packages (from torch<3,>=2.4->bitsandbytes!=0.46.0,!=0.48.0,>=0.45.5->unsloth @ git+https://github.com/unslothai/unsloth.git->unsloth[colab-new] @ git+https://github.com/unslothai/unsloth.git) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in /usr/local/lib/python3.13/dist-packages (from torch<3,>=2.4->bitsandbytes!=0.46.0,!=0.48.0,>=0.45.5->unsloth @ git+https://github.com/unslothai/unsloth.git->unsloth[colab-new] @ git+https://github.com/unslothai/unsloth.git) (3.6.1)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.13/dist-packages (from torch<3,>=2.4->bitsandbytes!=0.46.0,!=0.48.0,>=0.45.5->unsloth @ git+https://github.com/unslothai/unsloth.git->unsloth[colab-new] @ git+https://github.com/unslothai/unsloth.git) (3.1.6)
Requirement already satisfied: cuda-toolkit==12.8.1 in /usr/local/lib/python3.13/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch<3,>=2.4->bitsandbytes!=0.46.0,!=0.48.0,>=0.45.5->unsloth @ git+https://github.com/unslothai/unsloth.git->unsloth[colab-new] @ git+https://github.com/unslothai/unsloth.git) (12.8.1)
Requirement already satisfied: cuda-bindings<13,>=12.9.4 in /usr/local/lib/python3.13/dist-packages (from torch<3,>=2.4->bitsandbytes!=0.46.0,!=0.48.0,>=0.45.5->unsloth @ git+https://github.com/unslothai/unsloth.git->unsloth[colab-new] @ git+https://github.com/unslothai/unsloth.git) (12.9.7)
Requirement already satisfied: nvidia-cudnn-cu12==9.19.0.56 in /usr/local/lib/python3.13/dist-packages (from torch<3,>=2.4->bitsandbytes!=0.46.0,!=0.48.0,>=0.45.5->unsloth @ git+https://github.com/unslothai/unsloth.git->unsloth[colab-new] @ git+https://github.com/unslothai/unsloth.git) (9.19.0.56)
Requirement already satisfied: nvidia-cusparselt-cu12==0.7.1 in /usr/local/lib/python3.13/dist-packages (from torch<3,>=2.4->bitsandbytes!=0.46.0,!=0.48.0,>=0.45.5->unsloth @ git+https://github.com/unslothai/unsloth.git->unsloth[colab-new] @ git+https://github.com/unslothai/unsloth.git) (0.7.1)
Requirement already satisfied: nvidia-nccl-cu12==2.28.9 in /usr/local/lib/python3.13/dist-packages (from torch<3,>=2.4->bitsandbytes!=0.46.0,!=0.48.0,>=0.45.5->unsloth @ git+https://github.com/unslothai/unsloth.git->unsloth[colab-new] @ git+https://github.com/unslothai/unsloth.git) (2.28.9)
Requirement already satisfied: nvidia-nvshmem-cu12==3.4.5 in /usr/local/lib/python3.13/dist-packages (from torch<3,>=2.4->bitsandbytes!=0.46.0,!=0.48.0,>=0.45.5->unsloth @ git+https://github.com/unslothai/unsloth.git->unsloth[colab-new] @ git+https://github.com/unslothai/unsloth.git) (3.4.5)
Requirement already satisfied: triton==3.6.0 in /usr/local/lib/python3.13/dist-packages (from torch<3,>=2.4->bitsandbytes!=0.46.0,!=0.48.0,>=0.45.5->unsloth @ git+https://github.com/unslothai/unsloth.git->unsloth[colab-new] @ git+https://github.com/unslothai/unsloth.git) (3.6.0)
Requirement already satisfied: nvidia-cublas-cu12==12.8.4.1.* in /usr/local/lib/python3.13/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch<3,>=2.4->bitsandbytes!=0.46.0,!=0.48.0,>=0.45.5->unsloth @ git+https://github.com/unslothai/unsloth.git->unsloth[colab-new] @ git+https://github.com/unslothai/unsloth.git) (12.8.4.1)
Requirement already satisfied: nvidia-cuda-runtime-cu12==12.8.90.* in /usr/local/lib/python3.13/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch<3,>=2.4->bitsandbytes!=0.46.0,!=0.48.0,>=0.45.5->unsloth @ git+https://github.com/unslothai/unsloth.git->unsloth[colab-new] @ git+https://github.com/unslothai/unsloth.git) (12.8.90)
Requirement already satisfied: nvidia-cufft-cu12==11.3.3.83.* in /usr/local/lib/python3.13/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch<3,>=2.4->bitsandbytes!=0.46.0,!=0.48.0,>=0.45.5->unsloth @ git+https://github.com/unslothai/unsloth.git->unsloth[colab-new] @ git+https://github.com/unslothai/unsloth.git) (11.3.3.83)
Requirement already satisfied: nvidia-cufile-cu12==1.13.1.3.* in /usr/local/lib/python3.13/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch<3,>=2.4->bitsandbytes!=0.46.0,!=0.48.0,>=0.45.5->unsloth @ git+https://github.com/unslothai/unsloth.git->unsloth[colab-new] @ git+https://github.com/unslothai/unsloth.git) (1.13.1.3)
Requirement already satisfied: nvidia-cuda-cupti-cu12==12.8.90.* in /usr/local/lib/python3.13/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch<3,>=2.4->bitsandbytes!=0.46.0,!=0.48.0,>=0.45.5->unsloth @ git+https://github.com/unslothai/unsloth.git->unsloth[colab-new] @ git+https://github.com/unslothai/unsloth.git) (12.8.90)

In [5]:
# Instalação de bibliotecas necessárias para fine-tuning, LangChain e LangGraph.
# A flag -qq (quiet) é usada para instalações mais limpas no Colab.

# 1. Atualizar pip
!pip install -qqq --upgrade pip

# 2. Instalar `typing-extensions` explicitamente e cedo, pois muitas bibliotecas dependem dela
# Usamos `--upgrade --ignore-installed` para garantir a instalação de uma versão compatível
# sem tentar desinstalar uma versão do sistema que não pode ser removida.
print("Instalando/Atualizando typing-extensions para evitar conflitos...")
!pip install -qqq --upgrade typing-extensions --ignore-installed

# 3. Workaround para o erro 'Cannot uninstall packaging 24.0':
# A versão do sistema (packaging 24.0) não pode ser desinstalada. Muitos pacotes modernos,
# incluindo unsloth, requerem packaging >= 24.1. Vamos instalar uma versão compatível
# ignorando a versão do sistema com --ignore-installed. Isso fará com que o pip instale uma nova versão
# em '/usr/local/lib/python3.13/dist-packages' que será priorizada pelo Python.
print("Reinstalando packaging >= 24.1 ignorando a versão do sistema...")
!pip install -qqq --upgrade packaging>=24.1 --ignore-installed

# 4. Instalar Unsloth e suas dependências otimizadas para Colab
#    Unsloth trará Pydantic v2 e pydantic-core, evitando desinstalações conflitantes.
#    NÃO estamos atualizando numpy e pandas explicitamente aqui. Deixaremos Unsloth gerenciar suas próprias dependências para eles.
print("Instalando Unsloth e suas dependências...")
!pip install -qqq --upgrade "unsloth[colab-new] @ git+https://github.com/unslothai/unsloth.git"

# 5. Instalar outras dependências de Hugging Face não incluídas diretamente no Unsloth
print("Instalando dependências adicionais do Hugging Face...")
!pip install -qqq peft trl datasets

# 6. Ferramentas para LangChain e LangGraph (deixando o pip resolver as versões mais recentes compatíveis)
print("Instalando bibliotecas LangChain e LangGraph...")
# Para evitar conflitos de Pydantic v1 vs v2, vamos instalar versões mais recentes
# de LangChain que geralmente são compatíveis com Pydantic v2.
!pip install -qqq langchain langchain_community langchain_core langgraph
!pip install -qqq langchain-text-splitters

# 7. Para visualização (opcional) e PDF
print("Instalando bibliotecas de visualização e PDF...")
!pip install -qqq matplotlib seaborn pypdf

print("Instalação de todas as bibliotecas concluída!")

print("\nVerificando versões instaladas de pacotes chave:")
!pip show packaging
!pip show numpy
!pip show pandas
!pip show pydantic
!pip show pydantic-core
!pip show typing-extensions
!pip show langchain
!pip show langchain_community
!pip show langchain_core
!pip show langchain-text-splitters

Instalando/Atualizando typing-extensions para evitar conflitos...
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
google-adk 2.7.1 requires websockets<16,>=15.0.1, but you have websockets 16.1.1 which is incompatible.
Reinstalando packaging >= 24.1 ignorando a versão do sistema...
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
google-adk 2.7.1 requires websockets<16,>=15.0.1, but you have websockets 16.1.1 which is incompatible.
Instalando Unsloth e suas dependências...
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Instalando dependências adicionais do Hugging Face...
Instalando bibliotecas LangChain e LangGraph...
Instalando bibliotecas de visualização e PDF...
Instalação de todas as bibliotecas concluída!

Verificando versões instaladas de pacotes chave:
Name: packaging
Version: 26.3
Summary: Core utilities for Python packages
Home-page:
Author:
Author-email: Donald Stufft <donald@stufft.io>
License-Expression: Apache-2.0 OR BSD-2-Clause
Location: /usr/local/lib/python3.13/dist-packages
Requires:
Required-by: accelerate, altair, arviz, astropy, bigquery-magics, bitsandbytes, bokeh, cudf-cu12, cudf-polars-cu12, cuml-cu12, dask, dataproc-spark-connect, datasets, db-dtypes, deprecation, distributed, faiss-cpu, fastai, geopandas, google-adk, google-cloud-bigquery, gradio, gradio_client, h5netcdf, huggingface_hub, ipykernel, jupyter-events, jupyter_server, jupytext, kaggle, kagglehub, keras, keras-hub, langchain-core, langsmith, lazy-loader, libpysal, matplotlib, momepy, nbconvert, nibabel, numba-cuda, pandas-gbq, panel, panel-material-ui, patsy, peft, plotly, pooch, pylibcudf-cu12, pyogrio, pysal, pytest, scikit-image, shap, spacy, Sphinx, splot, statsmodels, tables, tensorboard, tensorflow, thinc, transformers, treelite, unsloth_zoo, wandb, weasel, wheel, xarray
Name: numpy
Version: 2.5.3
Summary: Fundamental package for array computing in Python
Home-page: https://numpy.org
Author: Travis E. Oliphant et al.
Author-email:
License-Expression: BSD-3-Clause AND 0BSD AND MIT AND Zlib AND CC0-1.0
Location: /usr/local/lib/python3.13/dist-packages
Requires:
Required-by: accelerate, access, albucore, albumentations, ale-py, arviz, astropy, autograd, bigframes, bitsandbytes, blis, blosc2, bokeh, Bottleneck, bqplot, clarabel, cmdstanpy, contourpy, cucim-cu12, cuda-core, cudf-cu12, cufflinks, cuml-cu12, cupy-cuda12x, cuvs-cu12, cvxpy, cyipopt, dask-cuda, dask-cudf-cu12, datasets, db-dtypes, diffusers, dm-tree, dopamine_rl, esda, faiss-cpu, flax, folium, formulaic, geemap, geopandas, gradio, grain, gym, gymnasium, h5netcdf, h5py, hdbscan, highspy, holoviews, hyperopt, ImageIO, imbalanced-learn, inequality, jax, jaxlib, keras, keras-hub, langchain-community, libpysal, librosa, lightgbm, mapclassify, matplotlib, matplotlib-venn, mgwr, missingno, mizani, ml_dtypes, mlxtend, moviepy, music21, nibabel, numba, numexpr, nx-cugraph-cu12, opencv-contrib-python, opencv-python, opencv-python-headless, optax, orbax-checkpoint, osqp, pandas, pandas-gbq, pandas-stubs, patsy, peft, plotnine, pointpats, prophet, pycocotools, pyerfa, pylibcugraph-cu12, pylibraft-cu12, pymc, pyogrio, pysal, pytensor, python-louvain, PyWavelets, quantecon, rasterio, rasterstats, rmm-cu12, scikit-image, scikit-learn, scipy, scs, seaborn, segregation, sentence-transformers, shap, shapely, sklearn-pandas, soundfile, soxr, spacy, spaghetti, spanner-graph-notebook, spglm, spint, splot, spopt, spreg, stanio, statsmodels, stumpy, tables, tensorboard, tensorflow, tensorflow-datasets, tensorflow-hub, tensorflow-probability, tensorstore, thinc, tifffile, tobler, torchtune, torchvision, transformers, treelite, treescope, tsfresh, ucxx-cu12, umap-learn, unsloth_zoo, wordcloud, xarray, xarray-einstats, xgboost, ydf, yellowbrick, yfinance
Name: pandas
Version: 2.2.3
Summary: Powerful data structures for data analysis, time series, and statistics
Home-page: https://pandas.pydata.org
Author:
Author-email: The Pandas Development Team <pandas-dev@python.org>
License: BSD 3-Clause License

Copyright (c) 2008-2011, AQR Capital Management, LLC, Lambda Foundry, Inc. and PyData Development Team
All rights reserved.

Copyright (c) 2011-2023, Open source contributors.

Redistribution and use in source and binary forms, with or without
modification, are permitted provided that the following conditions are met:

* Redistributions of source code must retain the above copyright notice, this
  list of conditions and the following disclaimer.

* Redistributions in binary form must reproduce the above copyright notice,
  this list of conditions and the following disclaimer in the documentation
  and/or other materials provided with the distribution.

* Neither the name of the copyright holder nor the names of its
  contributors may be used to endorse or promote products derived from
  this software without specific prior written permission.

THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE
FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
Copyright (c) 2010-2019 Keith Goodman
Copyright (c) 2019 Bottleneck Developers
All rights reserved.

Redistribution and use in source and binary forms, with or without
modification, are permitted provided that the following conditions are met:

    * Redistributions of source code must retain the above copyright notice,
      this list of conditions and the following disclaimer.

    * Redistributions in binary form must reproduce the above copyright
      notice, this list of conditions and the following disclaimer in the
      documentation and/or other materials provided with the distribution.

THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE
LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
POSSIBILITY OF SUCH DAMAGE.Copyright 2017- Paul Ganssle <paul@ganssle.io>
Copyright 2017- dateutil contributors (see AUTHORS file)

   Licensed under the Apache License, Version 2.0 (the "License");
   you may not use this file except in compliance with the License.
   You may obtain a copy of the License at

       http://www.apache.org/licenses/LICENSE-2.0

   Unless required by applicable law or agreed to in writing, software
   distributed under the License is distributed on an "AS IS" BASIS,
   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
   See the License for the specific language governing permissions and
   limitations under the License.

The above license applies to all contributions after 2017-12-01, as well as
all contributions that have been re-licensed (see AUTHORS file for the list of
contributors who have re-licensed their code).
--------------------------------------------------------------------------------
dateutil - Extensions to the standard Python datetime module.

Copyright (c) 2003-2011 - Gustavo Niemeyer <gustavo@niemeyer.net>
Copyright (c) 2012-2014 - Tomi Pieviläinen <tomi.pievilainen@iki.fi>
Copyright (c) 2014-2016 - Yaron de Leeuw <me@jarondl.net>
Copyright (c) 2015-     - Paul Ganssle <paul@ganssle.io>
Copyright (c) 2015-     - dateutil contributors (see AUTHORS file)

All rights reserved.

Redistribution and use in source and binary forms, with or without
modification, are permitted provided that the following conditions are met:

    * Redistributions of source code must retain the above copyright notice,
      this list of conditions and the following disclaimer.
    * Redistributions in binary form must reproduce the above copyright notice,
      this list of conditions and the following disclaimer in the documentation
      and/or other materials provided with the distribution.
    * Neither the name of the copyright holder nor the names of its
      contributors may be used to endorse or promote products derived from
      this software without specific prior written permission.

THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
"AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR
CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL,
EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,
PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR
PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF
LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING
NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

The above BSD License Applies to all code, even that also covered by Apache 2.0.# MIT License

Copyright (c) 2019 Hadley Wickham; RStudio; and Evan Miller

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.
Based on http://opensource.org/licenses/MIT

This is a template. Complete and ship as file LICENSE the following 2
lines (only)

YEAR:
COPYRIGHT HOLDER:

and specify as

License: MIT + file LICENSE

Copyright (c) <YEAR>, <COPYRIGHT HOLDER>

Permission is hereby granted, free of charge, to any person obtaining
a copy of this software and associated documentation files (the
"Software"), to deal in the Software without restriction, including
without limitation the rights to use, copy, modify, merge, publish,
distribute, sublicense, and/or sell copies of the Software, and to
permit persons to whom the Software is furnished to do so, subject to
the following conditions:

The above copyright notice and this permission notice shall be
included in all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE
LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION
OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION
WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
The MIT License

Copyright (c) 2008-     Attractive Chaos <attractor@live.co.uk>

Permission is hereby granted, free of charge, to any person obtaining
a copy of this software and associated documentation files (the
"Software"), to deal in the Software without restriction, including
without limitation the rights to use, copy, modify, merge, publish,
distribute, sublicense, and/or sell copies of the Software, and to
permit persons to whom the Software is furnished to do so, subject to
the following conditions:

The above copyright notice and this permission notice shall be
included in all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS
BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN
ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.musl as a whole is licensed under the following standard MIT license:

----------------------------------------------------------------------
Copyright © 2005-2020 Rich Felker, et al.

Permission is hereby granted, free of charge, to any person obtaining
a copy of this software and associated documentation files (the
"Software"), to deal in the Software without restriction, including
without limitation the rights to use, copy, modify, merge, publish,
distribute, sublicense, and/or sell copies of the Software, and to
permit persons to whom the Software is furnished to do so, subject to
the following conditions:

The above copyright notice and this permission notice shall be
included in all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.
IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY
CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT,
TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE
SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
----------------------------------------------------------------------

Authors/contributors include:

A. Wilcox
Ada Worcester
Alex Dowad
Alex Suykov
Alexander Monakov
Andre McCurdy
Andrew Kelley
Anthony G. Basile
Aric Belsito
Arvid Picciani
Bartosz Brachaczek
Benjamin Peterson
Bobby Bingham
Boris Brezillon
Brent Cook
Chris Spiegel
Clément Vasseur
Daniel Micay
Daniel Sabogal
Daurnimator
David Carlier
David Edelsohn
Denys Vlasenko
Dmitry Ivanov
Dmitry V. Levin
Drew DeVault
Emil Renner Berthing
Fangrui Song
Felix Fietkau
Felix Janda
Gianluca Anzolin
Hauke Mehrtens
He X
Hiltjo Posthuma
Isaac Dunham
Jaydeep Patil
Jens Gustedt
Jeremy Huntwork
Jo-Philipp Wich
Joakim Sindholt
John Spencer
Julien Ramseier
Justin Cormack
Kaarle Ritvanen
Khem Raj
Kylie McClain
Leah Neukirchen
Luca Barbato
Luka Perkov
M Farkas-Dyck (Strake)
Mahesh Bodapati
Markus Wichmann
Masanori Ogino
Michael Clark
Michael Forney
Mikhail Kremnyov
Natanael Copa
Nicholas J. Kain
orc
Pascal Cuoq
Patrick Oppenlander
Petr Hosek
Petr Skocik
Pierre Carrier
Reini Urban
Rich Felker
Richard Pennington
Ryan Fairfax
Samuel Holland
Segev Finer
Shiz
sin
Solar Designer
Stefan Kristiansson
Stefan O'Rear
Szabolcs Nagy
Timo Teräs
Trutz Behn
Valentin Ochs
Will Dietz
William Haddon
William Pitcock

Portions of this software are derived from third-party works licensed
under terms compatible with the above MIT license:

The TRE regular expression implementation (src/regex/reg* and
src/regex/tre*) is Copyright © 2001-2008 Ville Laurikari and licensed
under a 2-clause BSD license (license text in the source files). The
included version has been heavily modified by Rich Felker in 2012, in
the interests of size, simplicity, and namespace cleanliness.

Much of the math library code (src/math/* and src/complex/*) is
Copyright © 1993,2004 Sun Microsystems or
Copyright © 2003-2011 David Schultz or
Copyright © 2003-2009 Steven G. Kargl or
Copyright © 2003-2009 Bruce D. Evans or
Copyright © 2008 Stephen L. Moshier or
Copyright © 2017-2018 Arm Limited
and labelled as such in comments in the individual source files. All
have been licensed under extremely permissive terms.

The ARM memcpy code (src/string/arm/memcpy.S) is Copyright © 2008
The Android Open Source Project and is licensed under a two-clause BSD
license. It was taken from Bionic libc, used on Android.

The AArch64 memcpy and memset code (src/string/aarch64/*) are
Copyright © 1999-2019, Arm Limited.

The implementation of DES for crypt (src/crypt/crypt_des.c) is
Copyright © 1994 David Burren. It is licensed under a BSD license.

The implementation of blowfish crypt (src/crypt/crypt_blowfish.c) was
originally written by Solar Designer and placed into the public
domain. The code also comes with a fallback permissive license for use
in jurisdictions that may not recognize the public domain.

The smoothsort implementation (src/stdlib/qsort.c) is Copyright © 2011
Valentin Ochs and is licensed under an MIT-style license.

The x86_64 port was written by Nicholas J. Kain and is licensed under
the standard MIT terms.

The mips and microblaze ports were originally written by Richard
Pennington for use in the ellcc project. The original code was adapted
by Rich Felker for build system and code conventions during upstream
integration. It is licensed under the standard MIT terms.

The mips64 port was contributed by Imagination Technologies and is
licensed under the standard MIT terms.

The powerpc port was also originally written by Richard Pennington,
and later supplemented and integrated by John Spencer. It is licensed
under the standard MIT terms.

All other files which have no copyright comments are original works
produced specifically for use as part of this library, written either
by Rich Felker, the main author of the library, or by one or more
contibutors listed above. Details on authorship of individual files
can be found in the git version control history of the project. The
omission of copyright and license comments in each file is in the
interest of source tree size.

In addition, permission is hereby granted for all public header files
(include/* and arch/*/bits/*) and crt files intended to be linked into
applications (crt/*, ldso/dlstart.c, and arch/*/crt_arch.h) to omit
the copyright notice and permission notice otherwise required by the
license, and to use these files without any requirement of
attribution. These files include substantial contributions from:

Bobby Bingham
John Spencer
Nicholas J. Kain
Rich Felker
Richard Pennington
Stefan Kristiansson
Szabolcs Nagy

all of whom have explicitly granted such permission.

This file previously contained text expressing a belief that most of
the files covered by the above exception were sufficiently trivial not
to be subject to copyright, resulting in confusion over whether it
negated the permissions granted in the license. In the spirit of
permissive licensing, and of not having licensing issues being an
obstacle to adoption, that text has been removed.Copyright (c) 2005-2023, NumPy Developers.
All rights reserved.

Redistribution and use in source and binary forms, with or without

In [6]:
print("Instalando pydantic >= 2.0...")
!pip install -qqq pydantic>=2.0
print("Verificando a versão do pydantic instalada:")
!pip show pydantic

Instalando pydantic >= 2.0...
Verificando a versão do pydantic instalada:
Name: pydantic
Version: 2.13.5
Summary: Data validation using Python type hints
Home-page: https://github.com/pydantic/pydantic
Author:
Author-email: Samuel Colvin <s@muelcolvin.com>, Eric Jolibois <em.jolibois@gmail.com>, Hasan Ramezani <hasan.r67@gmail.com>, Adrian Garcia Badaracco <1755071+adriangb@users.noreply.github.com>, Terrence Dorsey <terry@pydantic.dev>, David Montague <david@pydantic.dev>, Serge Matveenko <lig@countzero.co>, Marcelo Trylesinski <marcelotryle@gmail.com>, Sydney Runkle <sydneymarierunkle@gmail.com>, David Hewitt <mail@davidhewitt.dev>, Alex Hall <alex.mojaki@gmail.com>, Victorien Plot <contact@vctrn.dev>
License-Expression: MIT
Location: /usr/local/lib/python3.13/dist-packages
Requires: annotated-types, pydantic-core, typing-extensions, typing-inspection
Required-by: albumentations, blosc2, fastapi, google-adk, google-genai, google-generativeai, gradio, langchain, langchain-classic, langchain-core, langgraph, langsmith, openai, pydantic-settings, pyiceberg, spacy, thinc, unsloth, wandb, weasel

 ## 2. Configuração do Ambiente e GPU

É fundamental verificar se o ambiente do Google Colab está configurado corretamente para utilizar a GPU, o que é crucial para o fine-tuning de LLMs. Também faremos as importações iniciais das bibliotecas principais.

In [7]:
# Importa bibliotecas essenciais e verifica a disponibilidade da GPU.
import torch
import pandas as pd
import numpy as np
import logging
import os

# Verifica e imprime a disponibilidade da GPU
if torch.cuda.is_available():
    print(f"GPU disponível: {torch.cuda.get_device_name(0)}")
    print(f"Versão CUDA: {torch.version.cuda}")
    device = "cuda"
else:
    print("GPU não disponível. O treinamento pode ser muito lento ou inviável.")
    device = "cpu"

# Configurações básicas de logging para acompanhar o processo
logging.basicConfig(level=logging.INFO, format='%(asctime)s - %(levelname)s - %(message)s')
logging.info("Ambiente configurado com sucesso. GPU verificada.")

GPU disponível: Tesla T4
Versão CUDA: 12.8

 ## 3. FINE-TUNING DE LLM MÉDICA

Esta seção abordará a preparação dos dados médicos, o pré-processamento, a anonimização (simplificada para demonstração) e o fine-tuning de uma LLM open-source leve. Escolheremos o modelo Llama-3-8B-Instruct para o fine-tuning, utilizando Unsloth para otimização de recursos.

### 3.1 Preparação, Pré-processamento e Anonimização de Dados Médicos/Sintéticos

Para o fine-tuning, precisamos de um dataset de perguntas e respostas médicas. Como não temos acesso a dados reais de pacientes, vamos gerar um dataset sintético que simule o estilo de um dataset médico. Em um cenário real, você usaria datasets como PubMedQA, MedQuAD ou dados internos anonimizados.

**Nota sobre Anonimização:** A anonimização real de dados médicos é um processo complexo que envolve técnicas sofisticadas (HIPAA, LGPD) e geralmente requer ferramentas dedicadas e validação humana. Aqui, faremos uma demonstração simplificada para ilustrar o conceito.

In [8]:
# Gerando um dataset sintético para fine-tuning.
# Em um cenário real, você carregaria dados de um arquivo CSV, JSON ou de um dataset como o Hugging Face.

# Lista de exemplos de interações médico-paciente
medical_qa_data = [
    {"pergunta": "Quais são os sintomas comuns de uma gripe?", "resposta": "Joelho Doendo, febre, dor de cabeça, dores musculares, tosse, dor de garganta e fadiga.", "fonte": "Ministério da Saúde"},
    {"pergunta": "Como prevenir o diabetes tipo 2?", "resposta": "A prevenção do diabetes tipo 2 envolve manter uma dieta saudável, praticar exercícios regularmente, controlar o peso e evitar o consumo excessivo de açúcares.", "fonte": "Sociedade Brasileira de Diabetes"},
    {"pergunta": "Qual é o tratamento para hipertensão arterial?", "resposta": "O tratamento para hipertensão geralmente inclui mudanças no estilo de vida (dieta, exercício), e frequentemente medicamentos anti-hipertensivos prescritos por um médico.", "fonte": "Organização Mundial da Saúde"},
    {"pergunta": "Explique o que é vacinação.", "resposta": "Vacinação é a administração de uma substância (vacina) para estimular o sistema imunológico de uma pessoa a produzir anticorpos e desenvolver imunidade contra uma doença infecciosa específica.", "fonte": "Fiocruz"},
    {"pergunta": "Quais os benefícios de uma dieta rica em fibras?", "resposta": "Uma dieta rica em fibras ajuda na digestão, previne constipação, auxilia no controle do açúcar no sangue e pode reduzir o risco de doenças cardíacas.", "fonte": "Associação Americana do Coração"},
    {"pergunta": "Posso tomar paracetamol para dor de cabeça?", "resposta": "Sim, paracetamol é um analgésico comum para dor de cabeça, mas sempre siga a dosagem recomendada na bula ou a indicação do seu médico. Não exceda a dose diária máxima.", "fonte": "Bula do Medicamento"}
]

# Convertendo para um DataFrame Pandas
df_medical = pd.DataFrame(medical_qa_data)

# Exemplo de pré-processamento e 'anonimização' simplificada (apenas para demonstração conceitual)
def preprocess_and_anonymize(text):
    # Exemplo: remover menções a nomes genéricos ou números de identificação fictícios
    text = text.replace("paciente X", "paciente")
    text = text.replace("ID12345", "[ID_ANONIMIZADO]")
    # Em um cenário real, você usaria técnicas mais avançadas para PHI (Protected Health Information)
    return text

df_medical['pergunta_anon'] = df_medical['pergunta'].apply(preprocess_and_anonymize)
df_medical['resposta_anon'] = df_medical['resposta'].apply(preprocess_and_anonymize)

print("Dataset médico sintético criado e 'anonimizado' (simplificado).")
display(df_medical.head())

# Formato para fine-tuning (chat_template)
# Unsloth prefere um formato de lista de dicionários para o dataset
# Cada entrada deve ter uma chave 'messages' com uma lista de turnos de diálogo.

def format_data_for_unsloth(df):
    formatted_data = []
    for index, row in df.iterrows():
        formatted_data.append({
            "messages": [
                {"role": "user", "content": row['pergunta_anon']},
                {"role": "assistant", "content": row['resposta_anon']}
            ]
        })
    return formatted_data

formatted_medical_data = format_data_for_unsloth(df_medical)

# Exibe um exemplo do formato para fine-tuning
print("\nExemplo de dado formatado para Unsloth:")
print(formatted_medical_data[0])

from datasets import Dataset

# Converte a lista de dicionários para um Dataset do Hugging Face
dataset = Dataset.from_pandas(pd.DataFrame(formatted_medical_data))
print(f"\nDataset Hugging Face criado com {len(dataset)} exemplos.")

Dataset médico sintético criado e 'anonimizado' (simplificado).

,pergunta,resposta,fonte,pergunta_anon,resposta_anon
0,Quais são os sintomas comuns de uma gripe?,"Joelho Doendo, febre, dor de cabeça, dores mus...",Ministério da Saúde,Quais são os sintomas comuns de uma gripe?,"Joelho Doendo, febre, dor de cabeça, dores mus..."
1,Como prevenir o diabetes tipo 2?,A prevenção do diabetes tipo 2 envolve manter ...,Sociedade Brasileira de Diabetes,Como prevenir o diabetes tipo 2?,A prevenção do diabetes tipo 2 envolve manter ...
2,Qual é o tratamento para hipertensão arterial?,O tratamento para hipertensão geralmente inclu...,Organização Mundial da Saúde,Qual é o tratamento para hipertensão arterial?,O tratamento para hipertensão geralmente inclu...
3,Explique o que é vacinação.,Vacinação é a administração de uma substância ...,Fiocruz,Explique o que é vacinação.,Vacinação é a administração de uma substância ...
4,Quais os benefícios de uma dieta rica em fibras?,"Uma dieta rica em fibras ajuda na digestão, pr...",Associação Americana do Coração,Quais os benefícios de uma dieta rica em fibras?,"Uma dieta rica em fibras ajuda na digestão, pr..."

Exemplo de dado formatado para Unsloth:
{'messages': [{'role': 'user', 'content': 'Quais são os sintomas comuns de uma gripe?'}, {'role': 'assistant', 'content': 'Joelho Doendo, febre, dor de cabeça, dores musculares, tosse, dor de garganta e fadiga.'}]}

Dataset Hugging Face criado com 6 exemplos.

### 3.2 Treinamento/Fine-Tuning de uma LLM Open-Source Leve com Unsloth

Nesta subseção, vamos realizar o fine-tuning de uma LLM open-source leve, como o Llama-3-8B-Instruct, utilizando a biblioteca Unsloth. O Unsloth otimiza o uso de memória e velocidade de treinamento, tornando o fine-tuning de modelos grandes viável em GPUs como a T4 disponível no Google Colab (quando ativada).

Usaremos a técnica LoRA (Low-Rank Adaptation) para ajustar o modelo de forma eficiente, treinando apenas uma pequena parte dos pesos do modelo, o que reduz drasticamente os requisitos de computação e memória.

In [9]:
from unsloth import FastLanguageModel
import torch
import os

# Set PyTorch CUDA allocator configuration to handle fragmentation
os.environ["PYTORCH_CUDA_ALLOC_CONF"] = "expandable_segments:True"

max_seq_length = 256 # Further reduced sequence length to save more memory
dtype = torch.float16 # Explicitly set to float16 for T4 compatibility
load_in_4bit = True

model, tokenizer = FastLanguageModel.from_pretrained(
    model_name = "unsloth/llama-2-7b-bnb-4bit", # Changed to a smaller, T4-friendly model
    max_seq_length = max_seq_length,
    dtype = dtype,
    load_in_4bit = load_in_4bit,
    device_map = {"": 0}, # Explicitly map all layers to GPU 0
)

# --- NOVO CÓDIGO PARA CARREGAR CHAT_TEMPLATE ---
# Garante que o chat_template seja carregado para este tokenizer
lora_model_path = "./lora_adapters" # O caminho onde o chat_template está salvo
chat_template_path = os.path.join(lora_model_path, "chat_template.jinja")

if os.path.exists(chat_template_path):
    with open(chat_template_path, "r", encoding="utf-8") as f:
        tokenizer.chat_template = f.read()
    print(f"Chat template carregado de '{chat_template_path}' para o tokenizer.")
else:
    print(f"Aviso: Não foi possível encontrar '{chat_template_path}'. O chat_template pode não estar configurado corretamente.")
# --- FIM DO NOVO CÓDIGO ---

model = FastLanguageModel.get_peft_model(
    model,
    r = 16,
    target_modules = ["q_proj", "k_proj", "v_proj", "o_proj",
                      "gate_proj", "up_proj", "down_proj"],
    lora_alpha = 16,
    lora_dropout = 0,
    bias = "none",
    use_gradient_checkpointing = True,
    random_state = 3407,
    use_rslora = False,
    loftq_config = None,
)

print("Modelo e Tokenizer carregados e configurados para fine-tuning LoRA.")

def formatting_prompts_func(examples):
    chats = examples["messages"]
    texts = [tokenizer.apply_chat_template(chat, tokenize=False, add_generation_prompt=False) + "<|eot_id|>" for chat in chats]
    return { "text" : texts, }

dataset = dataset.map(formatting_prompts_func, batched=True)

print("\nExemplo de texto formatado para treinamento (primeiro exemplo):")
print(dataset[0]["text"])

from trl import SFTTrainer
from transformers import TrainingArguments

trainer_args = TrainingArguments(
    per_device_train_batch_size = 1,
    gradient_accumulation_steps = 4,
    warmup_steps = 5,
    max_steps = 60,
    learning_rate = 2e-4,
    fp16 = True, # Forçar FP16 para GPUs T4 (que não suportam BF16 nativamente)
    bf16 = False, # Desabilitar BF16 para GPUs T4
    logging_steps = 1,
    output_dir = "outputs",
    optim = "adamw_8bit",
    weight_decay = 0.01,
    lr_scheduler_type = "linear",
    seed = 3407,
)

trainer = SFTTrainer(
    model = model,
    tokenizer = tokenizer,
    train_dataset = dataset,
    dataset_text_field = "text",
    max_seq_length = max_seq_length,
    dataset_num_proc = 2,
    args = trainer_args,
)

print("Trainer configurado. Iniciando o treinamento...")

trainer.train()

print("Treinamento concluído!")

🦥 Unsloth: Will patch your computer to enable 2x faster free finetuning.

/usr/local/lib/python3.13/dist-packages/unsloth/__init__.py:1551: UserWarning: WARNING: Unsloth should be imported before [transformers, peft] to ensure all optimizations are applied. Your code may run slower or encounter memory issues without these optimizations.

Please restructure your imports with 'import unsloth' at the top of your file.
  from ._gpu_init import *

🦥 Unsloth Zoo will now patch everything to make training faster!
==((====))==  Unsloth 2026.9.4: Fast Llama patching. Transformers: 5.5.0.
   \\   /|    Tesla T4. Num GPUs = 1. Max memory: 14.563 GB. Platform: Linux.
O^O/ \_/ \    Torch: 2.11.0+cu128. CUDA: 7.5. CUDA Toolkit: 12.8. Triton: 3.6.0
\        /    Bfloat16 = FALSE. FA [Xformers = None. FA2 = False]
 "-____-"     Free license: http://github.com/unslothai/unsloth
Unsloth: Fast downloading is enabled - ignore downloading bars which are red colored!

Loading weights:   0%|          | 0/291 [00:00<?, ?it/s]

Unsloth: Will load unsloth/llama-2-7b-bnb-4bit as a legacy tokenizer.

Chat template carregado de './lora_adapters/chat_template.jinja' para o tokenizer.

Unsloth 2026.9.4 patched 32 layers with 32 QKV layers, 32 O layers and 32 MLP layers.

Modelo e Tokenizer carregados e configurados para fine-tuning LoRA.

Map:   0%|          | 0/6 [00:00<?, ? examples/s]

Exemplo de texto formatado para treinamento (primeiro exemplo):
[INST] Quais são os sintomas comuns de uma gripe? [/INST]Joelho Doendo, febre, dor de cabeça, dores musculares, tosse, dor de garganta e fadiga.<|eot_id|>

Unsloth: Tokenizing ["text"] (num_proc=4):   0%|          | 0/6 [00:00<?, ? examples/s]

Trainer configurado. Iniciando o treinamento...

==((====))==  Unsloth - 2x faster free finetuning | Num GPUs used = 1
   \\   /|    Num examples = 6 | Num Epochs = 30 | Total steps = 60
O^O/ \_/ \    Batch size per device = 1 | Gradient accumulation steps = 4
\        /    Data Parallel GPUs = 1 | Total batch size (1 x 4 x 1) = 4
 "-____-"     Trainable parameters = 39,976,960 of 6,778,392,576 (0.59% trained)
`use_return_dict` is deprecated! Use `return_dict` instead!

Unsloth: Restored added_tokens_decoder metadata in outputs/checkpoint-60/tokenizer_config.json.

Treinamento concluído!

### Entendendo e Definindo o `chat_template` para o Tokenizer

O `chat_template` é uma string que define a estrutura de um prompt de conversação que será alimentado ao modelo. Ele é crucial para modelos de chat (como o Llama-2 ou Llama-3), pois estes modelos são treinados para esperar uma formatação específica para distinguir entre falas do usuário, falas do assistente e outros elementos da conversa.

Quando você usa `tokenizer.apply_chat_template()`, o tokenizer usa esse `chat_template` para transformar uma lista de mensagens (no formato `[{"role": "user", "content": "..."}, {"role": "assistant", "content": "..."}]`) em uma única string formatada que o modelo pode consumir.

**Por que é importante?**
*   **Consistência:** Garante que o modelo sempre receba os prompts no formato exato em que foi treinado, o que é vital para o desempenho.
*   **Tokens Especiais:** Inclui automaticamente tokens especiais (como `<s>`, `[INST]`, `<<SYS>>`, `<<EOT>>`, `<|begin_of_text|>`, `<|start_header_id|>`, etc.) que delimitam as diferentes partes da conversa.

**Como é definido?**
*   Muitas vezes, ele já vem pré-definido com o tokenizer ao carregar um modelo `from_pretrained` (especialmente modelos de chat).
*   Pode ser inspecionado através da propriedade `tokenizer.chat_template`.
*   Pode ser definido ou modificado manualmente, se você precisar adaptar o modelo a um novo formato de chat ou criar um template personalizado.

In [10]:
# Verificar e (opcionalmente) definir o chat_template
import os

# Verifica se o tokenizer foi carregado na célula anterior
if 'tokenizer' in locals():
    print("Tokenizador encontrado.\n")

    # 1. Inspecionar o chat_template atual
    print("Chat template atual do tokenizer:")
    if tokenizer.chat_template:
        print(tokenizer.chat_template)
    else:
        print("Nenhum chat_template definido. Tentando carregar de lora_adapters...")
        # Tenta carregar o chat_template de um arquivo se não estiver definido
        lora_model_path = "./lora_adapters"
        chat_template_path = os.path.join(lora_model_path, "chat_template.jinja")
        if os.path.exists(chat_template_path):
            with open(chat_template_path, "r", encoding="utf-8") as f:
                tokenizer.chat_template = f.read()
            print(f"Chat template carregado de '{chat_template_path}'.")
            print("Novo chat template:")
            print(tokenizer.chat_template)
        else:
            print(f"Aviso: Não foi possível encontrar '{chat_template_path}'. Definindo um template padrão para Llama-2.")
            # Fallback para um template padrão Llama-2, se o arquivo não for encontrado
            # Este é um exemplo simplificado, o template real pode ser mais complexo e inclui tokens especiais para system, user e assistant.
            # O template abaixo simula o formato ChatML para Llama-2 com system prompt dentro de INST
            tokenizer.chat_template = "{% if not add_generation_prompt is defined %}{% set add_generation_prompt = false %}{% endif %}{% for message in messages %}{% if message['role'] == 'user' %}[INST] {{ message['content'] }} [/INST]{% elif message['role'] == 'system' %}[INST] <<SYS>>\n{{ message['content'] }}\n<</SYS>>\n[/INST]{% else %}{{ message['content'] }}{% endif %}{% endfor %}{% if add_generation_prompt %}{{ '' }}{% endif %}"
            print("Chat template padrão Llama-2 aplicado.")

    print("\n--- Exemplo de como o template formataria uma conversa ---")
    example_chat = [
        {"role": "system", "content": "Você é um assistente útil e amigável."},
        {"role": "user", "content": "Olá, como você está?"},
        {"role": "assistant", "content": "Estou bem, obrigado! Como posso ajudar?"},
        {"role": "user", "content": "Gostaria de saber como funciona o fine-tuning de LLMs."}
    ]
    formatted_text = tokenizer.apply_chat_template(example_chat, tokenize=False, add_generation_prompt=False)
    print(formatted_text)

    # 2. Como definir ou modificar um chat_template (Exemplo para um template simples)
    # Você pode descomentar e adaptar isso se precisar de um template diferente.
    # Por exemplo, um template simplificado como o do Alpaca pode ser:
    # alpaca_template = """### Instruction:\n{system_message}\n\n### Input:\n{prompt}\n\n### Response:\n"""
    # tokenizer.chat_template = alpaca_template
    # print("\nNovo chat_template definido (exemplo Alpaca):\n" + tokenizer.chat_template)

    print("\nEntendimento do chat_template concluído.")

else:
    print("Variável 'tokenizer' não encontrada. Certifique-se de executar a célula 3.2 de fine-tuning primeiro para carregar o modelo e o tokenizer.")

Tokenizador encontrado.

Chat template atual do tokenizer:
{% if not add_generation_prompt is defined %}{% set add_generation_prompt = false %}{% endif %}{% for message in messages %}{% if message['role'] == 'user' %}[INST] {{ message['content'] }} [/INST]{% elif message['role'] == 'system' %}[INST] <<SYS>>
{{ message['content'] }}
<</SYS>>
[/INST]{% else %}{{ message['content'] }}{% endif %}{% endfor %}{% if add_generation_prompt %}{{ '' }}{% endif %}

--- Exemplo de como o template formataria uma conversa ---
[INST] <<SYS>>
Você é um assistente útil e amigável.
<</SYS>>
[/INST][INST] Olá, como você está? [/INST]Estou bem, obrigado! Como posso ajudar?[INST] Gostaria de saber como funciona o fine-tuning de LLMs. [/INST]

Entendimento do chat_template concluído.

### 3.3 Salvamento e Carregamento dos Pesos Ajustados

Após o fine-tuning, é crucial salvar os pesos ajustados (adaptadores LoRA) do modelo para que ele possa ser reutilizado sem a necessidade de re-treinamento. Em seguida, demonstraremos como carregar esses pesos em um novo modelo base, deixando-o pronto para inferência.

**Nota:** No Colab, os modelos são salvos no ambiente de tempo de execução. Para persistência, você precisará salvar no Google Drive ou em outro local de armazenamento.

### 3.4 Inferência com o Modelo Fine-Tuned

Com o modelo e o tokenizer carregados (e os adaptadores LoRA aplicados), podemos agora realizar inferências, ou seja, gerar respostas para novas perguntas ou prompts. É fundamental formatar o prompt de entrada de acordo com o `chat_template` esperado pelo modelo para garantir a melhor performance. O `apply_chat_template` do tokenizer é a ferramenta ideal para isso.

In [11]:
# Solução para o ImportError: Forçar a instalação de langchain_core==0.3.0
# Isso é necessário porque o `pip` pode não ter respeitado a versão fixada anteriormente
# ou outra dependência pode ter atualizado `langchain_core` para uma versão incompatível.
print("Forçando a reinstalação de langchain_core==0.3.0 para resolver incompatibilidade...")
!pip install -qqq --force-reinstall langchain_core==0.3.0
print("Verificando a versão de langchain_core após a re-instalação:")
!pip show langchain_core

print("\n======================== AVISO IMPORTANTE ========================")
print("Uma reinstalação forçada de uma biblioteca central como `langchain_core` pode exigir a")
print("**reinicialização do ambiente de execução (Runtime -> Restart runtime)** para que as alterações tenham efeito completo.")
print("Por favor, reinicie o ambiente de execução e execute as células novamente a partir da célula `7619c368`.")
print("==================================================================")

Forçando a reinstalação de langchain_core==0.3.0 para resolver incompatibilidade...
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
langgraph 1.2.11 requires langchain-core<2,>=1.4.7, but you have langchain-core 0.3.0 which is incompatible.
langchain 1.4.0 requires langchain-core<2.0.0,>=1.6.0, but you have langchain-core 0.3.0 which is incompatible.
langchain-text-splitters 1.1.2 requires langchain-core<2.0.0,>=1.2.31, but you have langchain-core 0.3.0 which is incompatible.
langchain-classic 1.0.8 requires langchain-core<2.0.0,>=1.4.4, but you have langchain-core 0.3.0 which is incompatible.
langgraph-prebuilt 1.1.0 requires langchain-core>=1.3.1, but you have langchain-core 0.3.0 which is incompatible.
langgraph-sdk 0.4.4 requires langchain-core<2,>=1.4.0, but you have langchain-core 0.3.0 which is incompatible.
langchain-community 0.4.2 requires langchain-core<2.0.0,>=1.4.0, but you have langchain-core 0.3.0 which is incompatible.
google-colab 1.0.0 requires requests==2.32.4, but you have requests 2.34.2 which is incompatible.
google-adk 2.7.1 requires tenacity<10,>=9, but you have tenacity 8.5.0 which is incompatible.
google-adk 2.7.1 requires websockets<16,>=15.0.1, but you have websockets 16.1.1 which is incompatible.
gcsfs 2025.12.0 requires fsspec==2025.12.0, but you have fsspec 2025.9.0 which is incompatible.
Verificando a versão de langchain_core após a re-instalação:
Name: langchain-core
Version: 0.3.0
Summary: Building applications with LLMs through composability
Home-page: https://github.com/langchain-ai/langchain
Author:
Author-email:
License: MIT
Location: /usr/local/lib/python3.13/dist-packages
Requires: jsonpatch, langsmith, packaging, pydantic, PyYAML, tenacity, typing-extensions
Required-by: langchain, langchain-classic, langchain-community, langchain-text-splitters, langgraph, langgraph-checkpoint, langgraph-prebuilt, langgraph-sdk

======================== AVISO IMPORTANTE ========================
Uma reinstalação forçada de uma biblioteca central como `langchain_core` pode exigir a
**reinicialização do ambiente de execução (Runtime -> Restart runtime)** para que as alterações tenham efeito completo.
Por favor, reinicie o ambiente de execução e execute as células novamente a partir da célula `7619c368`.
==================================================================

In [12]:
lora_model_path = "./lora_adapters"

# Salvar o modelo e tokenizer apenas se estiverem definidos na sessão atual
# Isso é útil se o kernel for reiniciado e você não quiser re-executar o treinamento
if 'model' in locals() and model is not None:
    model.save_pretrained(lora_model_path)
    print(f"Adaptadores LoRA salvos em: {lora_model_path}")
else:
    print(f"Variável 'model' não definida. Pulando o salvamento do modelo. Presume-se que o modelo já foi salvo em {lora_model_path} ou será carregado de lá.")

if 'tokenizer' in locals() and tokenizer is not None:
    tokenizer.save_pretrained(lora_model_path)
    print(f"Tokenizer salvo em: {lora_model_path}")
else:
    print(f"Variável 'tokenizer' não definida. Pulando o salvamento do tokenizer. Presume-se que o tokenizer já foi salvo em {lora_model_path} ou será carregado de lá.")


# Opcional: Empacotar e salvar no Google Drive para persistência
# from google.colab import drive
# drive.mount('/content/drive')
# !cp -r {lora_model_path} /content/drive/MyDrive/ # Copia para o Drive
# print(f"Adaptadores LoRA copiados para o Google Drive.")

# Liberar memória da GPU antes de carregar o modelo para inferência
print("\nLiberando memória da GPU (tentativa mais agressiva)...")

# Verifique e delete trainer e seu modelo interno
if 'trainer' in locals() and trainer is not None:
    if hasattr(trainer, 'model') and trainer.model is not None:
        trainer.model.to('cpu') # Move o modelo para CPU antes de deletar
        del trainer.model
    del trainer # Deletar o objeto trainer para liberar referências

# Verifique e delete model (se não foi deletado via trainer)
if 'model' in locals() and model is not None:
    model.to('cpu') # Explicitamente move para CPU
    del model

# Verifique e delete tokenizer
if 'tokenizer' in locals() and tokenizer is not None:
    del tokenizer

# Delete outras variáveis que podem consumir muita memória
if 'dataset' in locals() and dataset is not None:
    del dataset
if 'df_medical' in locals() and df_medical is not None:
    del df_medical
if 'formatted_medical_data' in locals() and formatted_medical_data is not None:
    del formatted_medical_data
# Se houver inputs/outputs de uma execução anterior de inferência, também os delete
if 'inputs' in locals() and inputs is not None:
    del inputs
if 'outputs' in locals() and outputs is not None:
    del outputs

import gc
gc.collect() # Coleta lixo do Python
torch.cuda.empty_cache() # Esvazia o cache de memória da CUDA
print("Memória da GPU liberada (agressivamente).")

# 2. Carregando os pesos ajustados para um novo modelo base
print("\nCarregando os adaptadores LoRA em um novo modelo base para inferência...")

# Recarrega o modelo base (sem LoRA)
# Importante: certifique-se de usar o mesmo modelo_name original.
new_model, new_tokenizer = FastLanguageModel.from_pretrained(
    model_name = lora_model_path, # Carrega diretamente do caminho dos adaptadores
    max_seq_length = max_seq_length,
    dtype = dtype,
    load_in_4bit = load_in_4bit,
    device_map = {"": 0}, # Adicionado para garantir o carregamento na GPU
)

# A linha abaixo não é mais necessária, pois FastLanguageModel.from_pretrained
# já carrega os adaptadores quando "model_name" é o caminho dos adaptadores.
# FastLanguageModel.load_adapters(new_model, lora_model_path)

print("Modelo com adaptadores LoRA carregados e pronto para inferência!")

# 3. Exemplo de Inferência com o Modelo Ajustado
print("\nRealizando uma inferência de teste com o modelo ajustado...")

# Define o prompt no formato de chat do Llama-3
# Note o 'add_generation_prompt=True' para que o modelo saiba que deve gerar uma resposta.
med_prompt = new_tokenizer.apply_chat_template([
    {"role": "user", "content": "Quais são os sintomas de um resfriado comum?"}
], tokenize=False, add_generation_prompt=True)

# Gera a resposta usando o modelo ajustado
inputs = new_tokenizer(med_prompt, return_tensors = "pt").to("cuda")

outputs = new_model.generate(**inputs, max_new_tokens = 64,
                             use_cache = True, pad_token_id = new_tokenizer.eos_token_id)

# Decodifica e imprime a resposta
response = new_tokenizer.batch_decode(outputs, skip_special_tokens=True)[0]

# A resposta bruta incluirá o prompt. Vamos extrair apenas a parte da resposta do assistente.
# O Llama-3 usa <|start_header_id|>assistant<|end_header_id|> para marcar o início da resposta.
assistant_response_start = response.find("<|start_header_id|>assistant<|end_header_id|>\n")
if assistant_response_start != -1:
    clean_response = response[assistant_response_start + len("<|start_header_id|>assistant<|end_header_id|>\n"):].split("<|eot_id|>")[0].strip()
else:
    clean_response = response.strip()

print("\nResposta do modelo ajustado:")
print(clean_response)

Unsloth: Restored added_tokens_decoder metadata in ./lora_adapters/tokenizer_config.json.

Adaptadores LoRA salvos em: ./lora_adapters
Tokenizer salvo em: ./lora_adapters

Liberando memória da GPU (tentativa mais agressiva)...
Memória da GPU liberada (agressivamente).

Carregando os adaptadores LoRA em um novo modelo base para inferência...
==((====))==  Unsloth 2026.9.4: Fast Llama patching. Transformers: 5.5.0.
   \\   /|    Tesla T4. Num GPUs = 1. Max memory: 14.563 GB. Platform: Linux.
O^O/ \_/ \    Torch: 2.11.0+cu128. CUDA: 7.5. CUDA Toolkit: 12.8. Triton: 3.6.0
\        /    Bfloat16 = FALSE. FA [Xformers = None. FA2 = False]
 "-____-"     Free license: http://github.com/unslothai/unsloth
Unsloth: Fast downloading is enabled - ignore downloading bars which are red colored!

Loading weights:   0%|          | 0/291 [00:00<?, ?it/s]

Unsloth: Will load ./lora_adapters as a legacy tokenizer.
Unsloth: The tokenizer `./lora_adapters` has a {% if add_generation_prompt %} block, but it does not change the rendered output. This tokenizer was loaded from a local path. The likely cause is a downstream tool (LlamaFactory, Axolotl, etc.) that re-serialized the tokenizer during save and stripped the generation-prompt block. Either re-save with the original template, or set `tokenizer.chat_template` manually before loading. Set UNSLOTH_STRICT_CHAT_TEMPLATE=1 to raise instead of warn.
Both `max_new_tokens` (=64) and `max_length`(=4096) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

Modelo com adaptadores LoRA carregados e pronto para inferência!

Realizando uma inferência de teste com o modelo ajustado...

Resposta do modelo ajustado:
[INST] Quais são os sintomas de um resfriado comum? [/INST]Joelho Doendo, febre, dor de cabeça, dores musculares, tosse, dor de garganta e fadiga.<|eot_id|>|eot_id|</|eot_id|>|eot_id|</|e

## 4. Criação de Assistente Médico com LangChain

Nesta seção, construiremos um assistente médico utilizando a biblioteca LangChain. O LangChain nos permitirá integrar nosso LLM customizado, simular consultas a uma base de dados estruturada (como prontuários) e contextualizar as respostas da LLM.

### 4.1 Integração da LLM Customizada com LangChain

Para usar nosso `new_model` fine-tuned dentro do ecossistema LangChain, precisamos criar um wrapper (`LLM` customizado) que implemente a interface esperada pelo LangChain.

In [13]:
print('Reinstalando componentes do LangChain para corrigir inconsistências...')

# Reinstala as últimas versões compatíveis dos componentes do LangChain
# Usamos --force-reinstall para garantir que as versões corretas sejam carregadas
# e --no-cache-dir para garantir que não haja versões antigas em cache.
!pip install -qqq --force-reinstall --no-cache-dir langchain langchain_community langchain_core langgraph langchain-text-splitters

print('Componentes do LangChain reinstalados. Verificando versões:')
!pip show langchain
!pip show langchain_community
!pip show langchain_core
!pip show langgraph
!pip show langchain-text-splitters

print('\nSe o erro persistir, um reinício do ambiente de execução (Runtime -> Restart runtime) será necessário.')

Reinstalando componentes do LangChain para corrigir inconsistências...
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
google-colab 1.0.0 requires requests==2.32.4, but you have requests 2.34.2 which is incompatible.
numba 0.61.2 requires numpy<2.3,>=1.24, but you have numpy 2.5.3 which is incompatible.
google-adk 2.7.1 requires websockets<16,>=15.0.1, but you have websockets 16.1.1 which is incompatible.
gcsfs 2025.12.0 requires fsspec==2025.12.0, but you have fsspec 2025.9.0 which is incompatible.
Componentes do LangChain reinstalados. Verificando versões:
Name: langchain
Version: 1.4.0
Summary: Building applications with LLMs through composability
Home-page: https://docs.langchain.com/
Author:
Author-email:
License: MIT
Location: /usr/local/lib/python3.13/dist-packages
Requires: langchain-core, langgraph, pydantic
Required-by:
Name: langchain-community
Version: 0.4.2
Summary: Community contributed LangChain integrations.
Home-page: https://docs.langchain.com/
Author:
Author-email:
License: MIT
Location: /usr/local/lib/python3.13/dist-packages
Requires: aiohttp, httpx-sse, langchain-classic, langchain-core, langsmith, numpy, pydantic-settings, pyyaml, requests, sqlalchemy, tenacity
Required-by:
Name: langchain-core
Version: 1.6.3
Summary: Building applications with LLMs through composability
Home-page: https://docs.langchain.com/
Author:
Author-email:
License: MIT
Location: /usr/local/lib/python3.13/dist-packages
Requires: httpx, jsonpatch, langchain-protocol, langsmith, packaging, pydantic, pyyaml, tenacity, typing-extensions, uuid-utils
Required-by: langchain, langchain-classic, langchain-community, langchain-text-splitters, langgraph, langgraph-checkpoint, langgraph-prebuilt, langgraph-sdk
Name: langgraph
Version: 1.2.11
Summary: Building stateful, multi-actor applications with LLMs
Home-page: https://docs.langchain.com/oss/python/langgraph/overview
Author:
Author-email:
License-Expression: MIT
Location: /usr/local/lib/python3.13/dist-packages
Requires: langchain-core, langgraph-checkpoint, langgraph-prebuilt, langgraph-sdk, pydantic, xxhash
Required-by: langchain
Name: langchain-text-splitters
Version: 1.1.2
Summary: LangChain text splitting utilities
Home-page: https://docs.langchain.com/
Author:
Author-email:
License: MIT
Location: /usr/local/lib/python3.13/dist-packages
Requires: langchain-core
Required-by: langchain-classic

Se o erro persistir, um reinício do ambiente de execução (Runtime -> Restart runtime) será necessário.

In [14]:
# Instalar bibliotecas adicionais necessárias para embeddings e vetor store
!pip install -qqq sentence-transformers faiss-cpu

from langchain_core.language_models import LLM
from typing import Any, List, Optional
from langchain_core.callbacks import CallbackManagerForLLMRun

class CustomFineTunedLLM(LLM):
    model: Any
    tokenizer: Any
    max_new_tokens: int = 64

    @property
    def _llm_type(self) -> str:
        return "custom_fine_tuned_llm"

    def _call(self, prompt: str, stop: Optional[List[str]] = None, run_manager: Optional[CallbackManagerForLLMRun] = None, **kwargs: Any) -> str:
        # Aplica o chat template, se necessário. Nosso new_model já espera o formato de chat
        # que foi formatado no med_prompt. Aqui, assumimos que o prompt de entrada já está no formato correto
        # para o modelo gerar a continuação.

        # Prepara o input para o modelo
        inputs = self.tokenizer(prompt, return_tensors="pt").to(self.model.device)

        # Gera a resposta
        outputs = self.model.generate(**inputs, max_new_tokens=self.max_new_tokens,
                                     use_cache=True, pad_token_id=self.tokenizer.eos_token_id)

        # Decodifica a resposta
        response = self.tokenizer.batch_decode(outputs, skip_special_tokens=True)[0]

        # Extrai apenas a parte da resposta do assistente (ignora o prompt original)
        # O formato do Llama-2/3 inclui o prompt original e o início da resposta do assistente.
        # Precisamos encontrar o marcador do assistente e retornar o texto após ele.
        assistant_prefix = "<|start_header_id|>assistant<|end_header_id|>\n"
        response_start = response.find(assistant_prefix)
        if response_start != -1:
            # Remove o prompt completo até o prefixo do assistente e qualquer token final como <|eot_id|>
            clean_response = response[response_start + len(assistant_prefix):].split("<|eot_id|>")[0].strip()
            # Para o Llama-2-7b, o template pode ser ligeiramente diferente, então ajustamos a extração
            # Se o prompt for incluído na resposta, a extração pode ser 'prompt_str + assistant_response'.
            # Vamos tentar remover o prompt de entrada da resposta gerada para obter apenas a continuação.
            if prompt in clean_response:
                clean_response = clean_response.replace(prompt, "").strip()
            elif len(inputs['input_ids'][0]) < len(outputs[0]): # Se houve geração de tokens novos
                generated_tokens = outputs[0][len(inputs['input_ids'][0]):]
                clean_response = self.tokenizer.decode(generated_tokens, skip_special_tokens=True).strip()
            else:
                clean_response = response.strip() # Fallback
        else:
             # If assistant prefix not found, try to extract based on input prompt length
            if len(inputs['input_ids'][0]) < len(outputs[0]):
                generated_tokens = outputs[0][len(inputs['input_ids'][0]):]
                clean_response = self.tokenizer.decode(generated_tokens, skip_special_tokens=True).strip()
            else:
                clean_response = response.strip()


        # Remove quaisquer marcadores de chat restantes no final
        clean_response = clean_response.replace("<|eot_id|>", "").strip()

        return clean_response

    @property
    def _identifying_params(self) -> dict[str, Any]:
        return {"max_new_tokens": self.max_new_tokens}

# Inicializa o LLM customizado com o modelo e tokenizer fine-tuned
# É importante que 'new_model' e 'new_tokenizer' estejam definidos a partir da célula anterior.
custom_llm = CustomFineTunedLLM(model=new_model, tokenizer=new_tokenizer, max_new_tokens=200) # Aumentar max_new_tokens para respostas mais longas

print("LLM customizado integrado com LangChain.")

# Exemplo rápido de uso do LLM customizado
print("\nTeste rápido do LLM customizado com LangChain:")
langchain_test_prompt = new_tokenizer.apply_chat_template([
    {"role": "user", "content": "Qual é o tratamento para asma?"}
], tokenize=False, add_generation_prompt=True)

response_lc = custom_llm.invoke(langchain_test_prompt)
print(f"Pergunta (LangChain): {langchain_test_prompt}")
print(f"Resposta (LangChain): {response_lc}")

Both `max_new_tokens` (=200) and `max_length`(=4096) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

LLM customizado integrado com LangChain.

Teste rápido do LLM customizado com LangChain:
Pergunta (LangChain): [INST] Qual é o tratamento para asma? [/INST]
Resposta (LangChain): O tratamento para a hipertensão arterial geralmente inclui mudanças no estilo de vida (dieta, exercício), e frequentemente medicamentos anti-hipertensivos prescritos por um médico.|eot_id|Para mais informações, siga o link.|eot_id|https://www. nobody-eot_id|eot_id|>www. nobody-eot_id|eot_id|>nobody|eot_id|>nobody|eot_id|>nobody</|eot_id|>|eot_id|>|eot_id|>|eot_id|>|eot_id|>|eot_id|

### 4.2 Simulação de Base de Dados Estruturadas (RAG)

Para simular a consulta a uma base de dados estruturada, utilizaremos a abordagem de Retrieval-Augmented Generation (RAG). Criaremos um pequeno conjunto de documentos que representam "prontuários e registros" e os armazenaremos em um Vector Store (FAISS) para busca de similaridade.

In [19]:
from langchain_community.document_loaders import TextLoader
from langchain_text_splitters import RecursiveCharacterTextSplitter # Importação corrigida para LangChain 1.x
from langchain_community.embeddings import HuggingFaceEmbeddings
from langchain_community.vectorstores import FAISS
from langchain_core.documents import Document

# 1. Criar dados simulados de "prontuários e registros"
# Em um cenário real, esses dados viriam de um banco de dados, PDFs, etc.
medical_records_data = [
    "Paciente João Silva, 45 anos. Histórico de asma desde a infância. Medicação atual: Salbutamol (sos), Budesonida (manutenção). Última crise em 10/05/2023, desencadeada por poeira. Aconselhado evitar alérgenos e manter inalador de resgate. Próxima consulta em 15/07/2024.",
    "Paciente Maria Souza, 60 anos. Diagnóstico de hipertensão arterial há 5 anos. Medicação: Losartana 50mg/dia. Pressão arterial média: 140/90 mmHg. Dieta com baixo teor de sódio recomendada. Exercícios leves 3 vezes por semana. Histórico familiar de doenças cardíacas.",
    "Paciente Carlos Pereira, 22 anos. Queixa principal: dor de garganta intensa, febre 38.5°C, tosse seca. Início dos sintomas há 3 dias. Exame físico: amígdalas avermelhadas. Diagnóstico provável: faringite viral. Tratamento: repouso, hidratação, analgésico (paracetamol). Reavaliar em 5 dias.",
    "Paciente Ana Costa, 30 anos. Histórico de alergia a penicilina. Apresenta erupções cutâneas e coceira generalizada após contato com produto de limpeza. Prescrito anti-histamínico e creme tópico. Aconselhado evitar o alérgeno e procurar um dermatologista se não houver melhora.",
    "Diretriz clínica para tratamento de diabetes tipo 2: Enfatiza controle glicêmico, dieta equilibrada, atividade física regular e, se necessário, medicação oral ou insulina. Monitoramento de HbA1c a cada 3-6 meses."
]

# Converte em objetos Document do LangChain
documents = [Document(page_content=record) for record in medical_records_data]

# 2. Dividir documentos em chunks (para lidar com documentos longos)
text_splitter = RecursiveCharacterTextSplitter(chunk_size=500, chunk_overlap=50)
chunked_documents = text_splitter.split_documents(documents)

print(f"Documentos originais: {len(documents)}")
print(f"Chunks criados: {len(chunked_documents)}")
print("\nPrimeiro chunk de exemplo:")
print(chunked_documents[0].page_content)

# 3. Escolher um modelo de embeddings leve (para rodar na T4 ou CPU se necessário)
# Usaremos um modelo da Sentence Transformers via HuggingFaceEmbeddings.
# O 'all-MiniLM-L6-v2' é um modelo pequeno e eficiente.

# Verificar se a GPU está disponível e, se sim, tentar usar para embeddings
if torch.cuda.is_available():
    print("\nUsando GPU para embeddings.")
    embeddings = HuggingFaceEmbeddings(model_name="sentence-transformers/all-MiniLM-L6-v2", model_kwargs={'device': 'cuda'})
else:
    print("\nGPU não disponível para embeddings, usando CPU.")
    embeddings = HuggingFaceEmbeddings(model_name="sentence-transformers/all-MiniLM-L6-v2", model_kwargs={'device': 'cpu'})


# 4. Criar um Vector Store (FAISS para busca em memória)
print("Criando FAISS vector store...")
vector_store = FAISS.from_documents(chunked_documents, embeddings)

# 5. Criar um retriever
retriever = vector_store.as_retriever()

print("Retriever para base de dados médica simulada configurado.")

# Teste do retriever
print("\nTeste do retriever para 'sintomas de asma':")
retrieved_docs = retriever.invoke("sintomas de asma")
for i, doc in enumerate(retrieved_docs):
    print(f"Documento {i+1}: {doc.page_content[:150]}...")


    !pip install --force-reinstall --no-cache-dir langchain langchain_community langchain_core langgraph langchain-text-splitters

Documentos originais: 5
Chunks criados: 5

Primeiro chunk de exemplo:
Paciente João Silva, 45 anos. Histórico de asma desde a infância. Medicação atual: Salbutamol (sos), Budesonida (manutenção). Última crise em 10/05/2023, desencadeada por poeira. Aconselhado evitar alérgenos e manter inalador de resgate. Próxima consulta em 15/07/2024.

Usando GPU para embeddings.

Loading weights:   0%|          | 0/103 [00:00<?, ?it/s]

BertModel LOAD REPORT from: sentence-transformers/all-MiniLM-L6-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Criando FAISS vector store...
Retriever para base de dados médica simulada configurado.

Teste do retriever para 'sintomas de asma':
Documento 1: Paciente João Silva, 45 anos. Histórico de asma desde a infância. Medicação atual: Salbutamol (sos), Budesonida (manutenção). Última crise em 10/05/20...
Collecting langchain
  Downloading langchain-1.4.0-py3-none-any.whl.metadata (6.2 kB)
Collecting langchain_community
  Downloading langchain_community-0.4.2-py3-none-any.whl.metadata (3.4 kB)
Collecting langchain_core
  Downloading langchain_core-1.6.3-py3-none-any.whl.metadata (4.8 kB)
Collecting langgraph
  Downloading langgraph-1.2.11-py3-none-any.whl.metadata (4.9 kB)
Collecting langchain-text-splitters
  Downloading langchain_text_splitters-1.1.2-py3-none-any.whl.metadata (3.3 kB)
Collecting pydantic<3.0.0,>=2.7.4 (from langchain)
  Downloading pydantic-2.13.5-py3-none-any.whl.metadata (110 kB)
Collecting httpx<1.0.0,>=0.23.0 (from langchain_core)
  Downloading httpx-0.28.1-py3-none-any.whl.metadata (7.1 kB)
Collecting jsonpatch<2.0.0,>=1.33.0 (from langchain_core)
  Downloading jsonpatch-1.33-py2.py3-none-any.whl.metadata (3.0 kB)
Collecting langchain-protocol>=0.0.17 (from langchain_core)
  Downloading langchain_protocol-0.0.19-py3-none-any.whl.metadata (2.4 kB)
Collecting langsmith<1.0.0,>=0.3.45 (from langchain_core)
  Downloading langsmith-0.12.4-py3-none-any.whl.metadata (22 kB)
Collecting packaging>=23.2.0 (from langchain_core)
  Downloading packaging-26.3-py3-none-any.whl.metadata (3.5 kB)
Collecting pyyaml<7.0.0,>=5.3.0 (from langchain_core)
  Downloading pyyaml-6.0.3-cp313-cp313-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl.metadata (2.4 kB)
Collecting tenacity!=8.4.0,<10.0.0,>=8.1.0 (from langchain_core)
  Downloading tenacity-9.1.4-py3-none-any.whl.metadata (1.2 kB)
Collecting typing-extensions<5.0.0,>=4.7.0 (from langchain_core)
  Downloading typing_extensions-4.16.0-py3-none-any.whl.metadata (3.3 kB)
Collecting uuid-utils<1.0,>=0.12.0 (from langchain_core)
  Downloading uuid_utils-0.17.1-cp313-cp313-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (6.4 kB)
Collecting langgraph-checkpoint<5.0.0,>=4.1.0 (from langgraph)
  Downloading langgraph_checkpoint-4.2.0-py3-none-any.whl.metadata (6.7 kB)
Collecting langgraph-prebuilt<1.2.0,>=1.1.0 (from langgraph)
  Downloading langgraph_prebuilt-1.1.0-py3-none-any.whl.metadata (5.2 kB)
Collecting langgraph-sdk<0.5.0,>=0.4.2 (from langgraph)
  Downloading langgraph_sdk-0.4.4-py3-none-any.whl.metadata (5.1 kB)
Collecting xxhash>=3.5.0 (from langgraph)
  Downloading xxhash-4.0.1-cp313-cp313-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl.metadata (17 kB)
Collecting anyio (from httpx<1.0.0,>=0.23.0->langchain_core)
  Downloading anyio-4.15.1-py3-none-any.whl.metadata (4.7 kB)
Collecting certifi (from httpx<1.0.0,>=0.23.0->langchain_core)
  Downloading certifi-2026.7.22-py3-none-any.whl.metadata (2.5 kB)
Collecting httpcore==1.* (from httpx<1.0.0,>=0.23.0->langchain_core)
  Downloading httpcore-1.0.9-py3-none-any.whl.metadata (21 kB)
Collecting idna (from httpx<1.0.0,>=0.23.0->langchain_core)
  Downloading idna-3.19-py3-none-any.whl.metadata (9.2 kB)
Collecting h11>=0.16 (from httpcore==1.*->httpx<1.0.0,>=0.23.0->langchain_core)
  Downloading h11-0.16.0-py3-none-any.whl.metadata (8.3 kB)
Collecting jsonpointer>=1.9 (from jsonpatch<2.0.0,>=1.33.0->langchain_core)
  Downloading jsonpointer-3.1.1-py3-none-any.whl.metadata (2.4 kB)
Collecting ormsgpack>=1.12.0 (from langgraph-checkpoint<5.0.0,>=4.1.0->langgraph)
  Downloading ormsgpack-1.12.2-cp313-cp313-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (3.2 kB)
Collecting orjson>=3.11.5 (from langgraph-sdk<0.5.0,>=0.4.2->langgraph)
  Downloading orjson-3.12.0-cp313-cp313-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (41 kB)
Collecting websockets<17,>=14 (from langgraph-sdk<0.5.0,>=0.4.2->langgraph)
  Downloading websockets-16.1.1-cp313-cp313-manylinux1_x86_64.manylinux_2_28_x86_64.manylinux_2_5_x86_64.whl.metadata (6.8 kB)
Collecting distro>=1.7.0 (from langsmith<1.0.0,>=0.3.45->langchain_core)
  Downloading distro-1.9.0-py3-none-any.whl.metadata (6.8 kB)
Collecting httpx2<3,>=2 (from langsmith<1.0.0,>=0.3.45->langchain_core)
  Downloading httpx2-2.12.0-py3-none-any.whl.metadata (9.5 kB)
Collecting requests-toolbelt>=1.0.0 (from langsmith<1.0.0,>=0.3.45->langchain_core)
  Downloading requests_toolbelt-1.0.0-py2.py3-none-any.whl.metadata (14 kB)
Collecting requests>=2.0.0 (from langsmith<1.0.0,>=0.3.45->langchain_core)
  Downloading requests-2.34.2-py3-none-any.whl.metadata (4.8 kB)
Collecting sniffio>=1.1 (from langsmith<1.0.0,>=0.3.45->langchain_core)
  Downloading sniffio-1.3.1-py3-none-any.whl.metadata (3.9 kB)
Collecting zstandard>=0.23.0 (from langsmith<1.0.0,>=0.3.45->langchain_core)
  Downloading zstandard-0.25.0-cp313-cp313-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (3.3 kB)
Collecting httpcore2==2.12.0 (from httpx2<3,>=2->langsmith<1.0.0,>=0.3.45->langchain_core)
  Downloading httpcore2-2.12.0-py3-none-any.whl.metadata (25 kB)
Collecting truststore>=0.10 (from httpx2<3,>=2->langsmith<1.0.0,>=0.3.45->langchain_core)
  Downloading truststore-0.10.4-py3-none-any.whl.metadata (4.4 kB)
Collecting annotated-types>=0.6.0 (from pydantic<3.0.0,>=2.7.4->langchain)
  Downloading annotated_types-0.8.0-py3-none-any.whl.metadata (15 kB)
Collecting pydantic-core==2.46.5 (from pydantic<3.0.0,>=2.7.4->langchain)
  Downloading pydantic_core-2.46.5-cp313-cp313-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (6.6 kB)
Collecting typing-inspection>=0.4.2 (from pydantic<3.0.0,>=2.7.4->langchain)
  Downloading typing_inspection-0.4.4-py3-none-any.whl.metadata (2.6 kB)
Collecting aiohttp<4.0.0,>=3.8.3 (from langchain_community)
  Downloading aiohttp-3.14.3-cp313-cp313-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl.metadata (8.3 kB)
Collecting httpx-sse<1.0.0,>=0.4.0 (from langchain_community)
  Downloading httpx_sse-0.4.3-py3-none-any.whl.metadata (9.7 kB)
Collecting langchain-classic<2.0.0,>=1.0.7 (from langchain_community)
  Downloading langchain_classic-1.0.8-py3-none-any.whl.metadata (5.1 kB)
Collecting numpy>=2.1.0 (from langchain_community)
  Downloading numpy-2.5.3-cp313-cp313-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl.metadata (6.6 kB)
Collecting pydantic-settings<3.0.0,>=2.10.1 (from langchain_community)
  Downloading pydantic_settings-2.15.0-py3-none-any.whl.metadata (3.9 kB)
Collecting sqlalchemy<3.0.0,>=1.4.0 (from langchain_community)
  Downloading sqlalchemy-2.0.52-cp313-cp313-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl.metadata (9.6 kB)
Collecting aiohappyeyeballs>=2.5.0 (from aiohttp<4.0.0,>=3.8.3->langchain_community)
  Downloading aiohappyeyeballs-2.7.1-py3-none-any.whl.metadata (5.9 kB)
Collecting aiosignal>=1.4.0 (from aiohttp<4.0.0,>=3.8.3->langchain_community)
  Downloading aiosignal-1.4.0-py3-none-any.whl.metadata (3.7 kB)
Collecting attrs>=17.3.0 (from aiohttp<4.0.0,>=3.8.3->langchain_community)
  Downloading attrs-26.1.0-py3-none-any.whl.metadata (8.8 kB)
Collecting frozenlist>=1.1.1 (from aiohttp<4.0.0,>=3.8.3->langchain_community)
  Downloading frozenlist-1.8.0-cp313-cp313-manylinux1_x86_64.manylinux_2_28_x86_64.manylinux_2_5_x86_64.whl.metadata (20 kB)
Collecting multidict<7.0,>=4.5 (from aiohttp<4.0.0,>=3.8.3->langchain_community)
  Downloading multidict-6.8.0-cp313-cp313-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl.metadata (5.3 kB)
Collecting propcache>=0.2.0 (from aiohttp<4.0.0,>=3.8.3->langchain_community)
  Downloading propcache-0.5.2-cp313-cp313-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl.metadata (16 kB)
Collecting yarl<2.0,>=1.17.0 (from aiohttp<4.0.0,>=3.8.3->langchain_community)
  Downloading yarl-1.24.5-cp313-cp313-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl.metadata (103 kB)
Collecting python-dotenv>=0.21.0 (from pydantic-settings<3.0.0,>=2.10.1->langchain_community)
  Downloading python_dotenv-1.2.3-py3-none-any.whl.metadata (29 kB)
Collecting charset_normalizer<4,>=2 (from requests>=2.0.0->langsmith<1.0.0,>=0.3.45->langchain_core)
  Downloading charset_normalizer-3.5.1-cp313-cp313-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl.metadata (45 kB)
Collecting urllib3<3,>=1.26 (from requests>=2.0.0->langsmith<1.0.0,>=0.3.45->langchain_core)
  Downloading urllib3-2.7.0-py3-none-any.whl.metadata (6.9 kB)
Collecting greenlet>=1 (from sqlalchemy<3.0.0,>=1.4.0->langchain_community)
  Downloading greenlet-3.5.5-cp313-cp313-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl.metadata (3.8 kB)
Downloading langchain-1.4.0-py3-none-any.whl (161 kB)
Downloading langchain_core-1.6.3-py3-none-any.whl (571 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 571.8/571.8 kB 141.7 MB/s  0:00:00
Downloading langgraph-1.2.11-py3-none-any.whl (248 kB)
Downloading httpx-0.28.1-py3-none-any.whl (73 kB)
Downloading httpcore-1.0.9-py3-none-any.whl (78 kB)
Downloading jsonpatch-1.33-py2.py3-none-any.whl (12 kB)
Downloading langgraph_checkpoint-4.2.0-py3-none-any.whl (56 kB)
Downloading langgraph_prebuilt-1.1.0-py3-none-any.whl (41 kB)
Downloading langgraph_sdk-0.4.4-py3-none-any.whl (162 kB)
Downloading langsmith-0.12.4-py3-none-any.whl (767 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 767.5/767.5 kB 298.8 MB/s  0:00:00
Downloading httpx2-2.12.0-py3-none-any.whl (95 kB)
Downloading httpcore2-2.12.0-py3-none-any.whl (83 kB)
Downloading pydantic-2.13.5-py3-none-any.whl (472 kB)
Downloading pydantic_core-2.46.5-cp313-cp313-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (2.1 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.1/2.1 MB 395.9 MB/s  0:00:00
Downloading pyyaml-6.0.3-cp313-cp313-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl (801 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 801.6/801.6 kB 383.1 MB/s  0:00:00
Downloading tenacity-9.1.4-py3-none-any.whl (28 kB)
Downloading typing_extensions-4.16.0-py3-none-any.whl (45 kB)
Downloading uuid_utils-0.17.1-cp313-cp313-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (323 kB)
Downloading websockets-16.1.1-cp313-cp313-manylinux1_x86_64.manylinux_2_28_x86_64.manylinux_2_5_x86_64.whl (187 kB)
Downloading langchain_community-0.4.2-py3-none-any.whl (2.4 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.4/2.4 MB 233.9 MB/s  0:00:00
Downloading aiohttp-3.14.3-cp313-cp313-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl (1.8 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.8/1.8 MB 556.3 MB/s  0:00:00
Downloading httpx_sse-0.4.3-py3-none-any.whl (9.0 kB)
Downloading langchain_classic-1.0.8-py3-none-any.whl (1.0 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.0/1.0 MB 564.0 MB/s  0:00:00
Downloading langchain_text_splitters-1.1.2-py3-none-any.whl (35 kB)
Downloading multidict-6.8.0-cp313-cp313-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl (287 kB)
Downloading pydantic_settings-2.15.0-py3-none-any.whl (69 kB)
Downloading requests-2.34.2-py3-none-any.whl (73 kB)
Downloading charset_normalizer-3.5.1-cp313-cp313-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl (250 kB)
Downloading idna-3.19-py3-none-any.whl (68 kB)
Downloading sqlalchemy-2.0.52-cp313-cp313-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl (3.3 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.3/3.3 MB 304.0 MB/s  0:00:00
Downloading urllib3-2.7.0-py3-none-any.whl (131 kB)
Downloading yarl-1.24.5-cp313-cp313-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl (110 kB)
Downloading aiohappyeyeballs-2.7.1-py3-none-any.whl (15 kB)
Downloading aiosignal-1.4.0-py3-none-any.whl (7.5 kB)
Downloading annotated_types-0.8.0-py3-none-any.whl (13 kB)
Downloading anyio-4.15.1-py3-none-any.whl (132 kB)
Downloading attrs-26.1.0-py3-none-any.whl (67 kB)
Downloading certifi-2026.7.22-py3-none-any.whl (136 kB)
Downloading distro-1.9.0-py3-none-any.whl (20 kB)
Downloading frozenlist-1.8.0-cp313-cp313-manylinux1_x86_64.manylinux_2_28_x86_64.manylinux_2_5_x86_64.whl (234 kB)
Downloading greenlet-3.5.5-cp313-cp313-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl (623 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 623.9/623.9 kB 741.2 MB/s  0:00:00
Downloading h11-0.16.0-py3-none-any.whl (37 kB)
Downloading jsonpointer-3.1.1-py3-none-any.whl (7.7 kB)
Downloading langchain_protocol-0.0.19-py3-none-any.whl (7.3 kB)
Downloading numpy-2.5.3-cp313-cp313-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl (16.7 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 16.7/16.7 MB 354.9 MB/s  0:00:00
Downloading orjson-3.12.0-cp313-cp313-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (131 kB)
Downloading ormsgpack-1.12.2-cp313-cp313-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (212 kB)
Downloading packaging-26.3-py3-none-any.whl (129 kB)
Downloading propcache-0.5.2-cp313-cp313-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl (61 kB)
Downloading python_dotenv-1.2.3-py3-none-any.whl (22 kB)
Downloading requests_toolbelt-1.0.0-py2.py3-none-any.whl (54 kB)
Downloading sniffio-1.3.1-py3-none-any.whl (10 kB)
Downloading truststore-0.10.4-py3-none-any.whl (18 kB)
Downloading typing_inspection-0.4.4-py3-none-any.whl (14 kB)
Downloading xxhash-4.0.1-cp313-cp313-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl (268 kB)
Downloading zstandard-0.25.0-cp313-cp313-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (5.5 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.5/5.5 MB 241.2 MB/s  0:00:00
Installing collected packages: zstandard, xxhash, websockets, uuid-utils, urllib3, typing-extensions, truststore, tenacity, sniffio, pyyaml, python-dotenv, propcache, packaging, ormsgpack, orjson, numpy, multidict, jsonpointer, idna, httpx-sse, h11, greenlet, frozenlist, distro, charset_normalizer, certifi, attrs, annotated-types, aiohappyeyeballs, yarl, typing-inspection, sqlalchemy, requests, pydantic-core, langchain-protocol, jsonpatch, httpcore2, httpcore, anyio, aiosignal, requests-toolbelt, pydantic, httpx2, httpx, aiohttp, pydantic-settings, langsmith, langchain_core, langgraph-sdk, langgraph-checkpoint, langchain-text-splitters, langgraph-prebuilt, langchain-classic, langgraph, langchain_community, langchain
  Attempting uninstall: zstandard
    Found existing installation: zstandard 0.25.0
    Uninstalling zstandard-0.25.0:
      Successfully uninstalled zstandard-0.25.0
  Attempting uninstall: xxhash
    Found existing installation: xxhash 4.0.1
    Uninstalling xxhash-4.0.1:
      Successfully uninstalled xxhash-4.0.1
  Attempting uninstall: websockets
    Found existing installation: websockets 16.1.1
    Uninstalling websockets-16.1.1:
      Successfully uninstalled websockets-16.1.1
  Attempting uninstall: uuid-utils
    Found existing installation: uuid_utils 0.17.1
    Uninstalling uuid_utils-0.17.1:
      Successfully uninstalled uuid_utils-0.17.1
  Attempting uninstall: urllib3
    Found existing installation: urllib3 2.7.0
    Uninstalling urllib3-2.7.0:
      Successfully uninstalled urllib3-2.7.0
  Attempting uninstall: typing-extensions
    Found existing installation: typing_extensions 4.16.0
    Uninstalling typing_extensions-4.16.0:
      Successfully uninstalled typing_extensions-4.16.0
  Attempting uninstall: truststore
    Found existing installation: truststore 0.10.4
    Uninstalling truststore-0.10.4:
      Successfully uninstalled truststore-0.10.4
  Attempting uninstall: tenacity
    Found existing installation: tenacity 9.1.4
    Uninstalling tenacity-9.1.4:
      Successfully uninstalled tenacity-9.1.4
  Attempting uninstall: sniffio
    Found existing installation: sniffio 1.3.1
    Uninstalling sniffio-1.3.1:
      Successfully uninstalled sniffio-1.3.1
  Attempting uninstall: pyyaml
    Found existing installation: PyYAML 6.0.3
    Uninstalling PyYAML-6.0.3:
      Successfully uninstalled PyYAML-6.0.3
  Attempting uninstall: python-dotenv
    Found existing installation: python-dotenv 1.2.3
    Uninstalling python-dotenv-1.2.3:
      Successfully uninstalled python-dotenv-1.2.3
  Attempting uninstall: propcache
    Found existing installation: propcache 0.5.2
    Uninstalling propcache-0.5.2:
      Successfully uninstalled propcache-0.5.2
  Attempting uninstall: packaging
    Found existing installation: packaging 26.3
    Uninstalling packaging-26.3:
      Successfully uninstalled packaging-26.3
  Attempting uninstall: ormsgpack
    Found existing installation: ormsgpack 1.12.2
    Uninstalling ormsgpack-1.12.2:
      Successfully uninstalled ormsgpack-1.12.2
  Attempting uninstall: orjson
    Found existing installation: orjson 3.12.0
    Uninstalling orjson-3.12.0:
      Successfully uninstalled orjson-3.12.0
  Attempting uninstall: numpy
    Found existing installation: numpy 2.5.3
    Uninstalling numpy-2.5.3:
      Successfully uninstalled numpy-2.5.3
  Attempting uninstall: multidict
    Found existing installation: multidict 6.8.0
    Uninstalling multidict-6.8.0:
      Successfully uninstalled multidict-6.8.0
  Attempting uninstall: jsonpointer
    Found existing installation: jsonpointer 3.1.1
    Uninstalling jsonpointer-3.1.1:
      Successfully uninstalled jsonpointer-3.1.1
  Attempting uninstall: idna
    Found existing installation: idna 3.19
    Uninstalling idna-3.19:
      Successfully uninstalled idna-3.19
  Attempting uninstall: httpx-sse
    Found existing installation: httpx-sse 0.4.3
    Uninstalling httpx-sse-0.4.3:
      Successfully uninstalled httpx-sse-0.4.3
  Attempting uninstall: h11
    Found existing installation: h11 0.16.0
    Uninstalling h11-0.16.0:
      Successfully uninstalled h11-0.16.0
  Attempting uninstall: greenlet
    Found existing installation: greenlet 3.5.5
    Uninstalling greenlet-3.5.5:
      Successfully uninstalled greenlet-3.5.5
  Attempting uninstall: frozenlist
    Found existing installation: frozenlist 1.8.0
    Uninstalling frozenlist-1.8.0:
      Successfully uninstalled frozenlist-1.8.0
  Attempting uninstall: distro
    Found existing installation: distro 1.9.0
    Uninstalling distro-1.9.0:
      Successfully uninstalled distro-1.9.0
  Attempting uninstall: charset_normalizer
    Found existing installation: charset-normalizer 3.5.1
    Uninstalling charset-normalizer-3.5.1:
      Successfully uninstalled charset-normalizer-3.5.1
  Attempting uninstall: certifi
    Found existing installation: certifi 2026.7.22
    Uninstalling certifi-2026.7.22:
      Successfully uninstalled certifi-2026.7.22
  Attempting uninstall: attrs
    Found existing installation: attrs 26.1.0
    Uninstalling attrs-26.1.0:
      Successfully uninstalled attrs-26.1.0
  Attempting uninstall: annotated-types
    Found existing installation: annotated-types 0.8.0
    Uninstalling annotated-types-0.8.0:
      Successfully uninstalled annotated-types-0.8.0
  Attempting uninstall: aiohappyeyeballs
    Found existing installation: aiohappyeyeballs 2.7.1
    Uninstalling aiohappyeyeballs-2.7.1:
      Successfully uninstalled aiohappyeyeballs-2.7.1
  Attempting uninstall: yarl
    Found existing installation: yarl 1.24.5
    Uninstalling yarl-1.24.5:
      Successfully uninstalled yarl-1.24.5
  Attempting uninstall: typing-inspection
    Found existing installation: typing-inspection 0.4.4
    Uninstalling typing-inspection-0.4.4:
      Successfully uninstalled typing-inspection-0.4.4
  Attempting uninstall: sqlalchemy
    Found existing installation: SQLAlchemy 2.0.52
    Uninstalling SQLAlchemy-2.0.52:
      Successfully uninstalled SQLAlchemy-2.0.52
  Attempting uninstall: requests
    Found existing installation: requests 2.34.2
    Uninstalling requests-2.34.2:
      Successfully uninstalled requests-2.34.2
  Attempting uninstall: pydantic-core
    Found existing installation: pydantic_core 2.46.5
    Uninstalling pydantic_core-2.46.5:
      Successfully uninstalled pydantic_core-2.46.5
  Attempting uninstall: langchain-protocol

Documento 2: Paciente Ana Costa, 30 anos. Histórico de alergia a penicilina. Apresenta erupções cutâneas e coceira generalizada após contato com produto de limpeza...
Collecting langchain
  Downloading langchain-1.4.0-py3-none-any.whl.metadata (6.2 kB)
Collecting langchain_community
  Downloading langchain_community-0.4.2-py3-none-any.whl.metadata (3.4 kB)
Collecting langchain_core
  Downloading langchain_core-1.6.3-py3-none-any.whl.metadata (4.8 kB)
Collecting langgraph
  Downloading langgraph-1.2.11-py3-none-any.whl.metadata (4.9 kB)
Collecting langchain-text-splitters
  Downloading langchain_text_splitters-1.1.2-py3-none-any.whl.metadata (3.3 kB)
Collecting pydantic<3.0.0,>=2.7.4 (from langchain)
  Downloading pydantic-2.13.5-py3-none-any.whl.metadata (110 kB)
Collecting httpx<1.0.0,>=0.23.0 (from langchain_core)
  Downloading httpx-0.28.1-py3-none-any.whl.metadata (7.1 kB)
Collecting jsonpatch<2.0.0,>=1.33.0 (from langchain_core)
  Downloading jsonpatch-1.33-py2.py3-none-any.whl.metadata (3.0 kB)
Collecting langchain-protocol>=0.0.17 (from langchain_core)
  Downloading langchain_protocol-0.0.19-py3-none-any.whl.metadata (2.4 kB)
Collecting langsmith<1.0.0,>=0.3.45 (from langchain_core)
  Downloading langsmith-0.12.4-py3-none-any.whl.metadata (22 kB)
Collecting packaging>=23.2.0 (from langchain_core)
  Downloading packaging-26.3-py3-none-any.whl.metadata (3.5 kB)
Collecting pyyaml<7.0.0,>=5.3.0 (from langchain_core)
  Downloading pyyaml-6.0.3-cp313-cp313-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl.metadata (2.4 kB)
Collecting tenacity!=8.4.0,<10.0.0,>=8.1.0 (from langchain_core)
  Downloading tenacity-9.1.4-py3-none-any.whl.metadata (1.2 kB)
Collecting typing-extensions<5.0.0,>=4.7.0 (from langchain_core)
  Downloading typing_extensions-4.16.0-py3-none-any.whl.metadata (3.3 kB)
Collecting uuid-utils<1.0,>=0.12.0 (from langchain_core)
  Downloading uuid_utils-0.17.1-cp313-cp313-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (6.4 kB)
Collecting langgraph-checkpoint<5.0.0,>=4.1.0 (from langgraph)
  Downloading langgraph_checkpoint-4.2.0-py3-none-any.whl.metadata (6.7 kB)
Collecting langgraph-prebuilt<1.2.0,>=1.1.0 (from langgraph)
  Downloading langgraph_prebuilt-1.1.0-py3-none-any.whl.metadata (5.2 kB)
Collecting langgraph-sdk<0.5.0,>=0.4.2 (from langgraph)
  Downloading langgraph_sdk-0.4.4-py3-none-any.whl.metadata (5.1 kB)
Collecting xxhash>=3.5.0 (from langgraph)
  Downloading xxhash-4.0.1-cp313-cp313-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl.metadata (17 kB)
Collecting anyio (from httpx<1.0.0,>=0.23.0->langchain_core)
  Downloading anyio-4.15.1-py3-none-any.whl.metadata (4.7 kB)
Collecting certifi (from httpx<1.0.0,>=0.23.0->langchain_core)
  Downloading certifi-2026.7.22-py3-none-any.whl.metadata (2.5 kB)
Collecting httpcore==1.* (from httpx<1.0.0,>=0.23.0->langchain_core)
  Downloading httpcore-1.0.9-py3-none-any.whl.metadata (21 kB)
Collecting idna (from httpx<1.0.0,>=0.23.0->langchain_core)
  Downloading idna-3.19-py3-none-any.whl.metadata (9.2 kB)
Collecting h11>=0.16 (from httpcore==1.*->httpx<1.0.0,>=0.23.0->langchain_core)
  Downloading h11-0.16.0-py3-none-any.whl.metadata (8.3 kB)
Collecting jsonpointer>=1.9 (from jsonpatch<2.0.0,>=1.33.0->langchain_core)
  Downloading jsonpointer-3.1.1-py3-none-any.whl.metadata (2.4 kB)
Collecting ormsgpack>=1.12.0 (from langgraph-checkpoint<5.0.0,>=4.1.0->langgraph)
  Downloading ormsgpack-1.12.2-cp313-cp313-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (3.2 kB)
Collecting orjson>=3.11.5 (from langgraph-sdk<0.5.0,>=0.4.2->langgraph)
  Downloading orjson-3.12.0-cp313-cp313-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (41 kB)
Collecting websockets<17,>=14 (from langgraph-sdk<0.5.0,>=0.4.2->langgraph)
  Downloading websockets-16.1.1-cp313-cp313-manylinux1_x86_64.manylinux_2_28_x86_64.manylinux_2_5_x86_64.whl.metadata (6.8 kB)
Collecting distro>=1.7.0 (from langsmith<1.0.0,>=0.3.45->langchain_core)
  Downloading distro-1.9.0-py3-none-any.whl.metadata (6.8 kB)
Collecting httpx2<3,>=2 (from langsmith<1.0.0,>=0.3.45->langchain_core)
  Downloading httpx2-2.12.0-py3-none-any.whl.metadata (9.5 kB)
Collecting requests-toolbelt>=1.0.0 (from langsmith<1.0.0,>=0.3.45->langchain_core)
  Downloading requests_toolbelt-1.0.0-py2.py3-none-any.whl.metadata (14 kB)
Collecting requests>=2.0.0 (from langsmith<1.0.0,>=0.3.45->langchain_core)
  Downloading requests-2.34.2-py3-none-any.whl.metadata (4.8 kB)
Collecting sniffio>=1.1 (from langsmith<1.0.0,>=0.3.45->langchain_core)
  Downloading sniffio-1.3.1-py3-none-any.whl.metadata (3.9 kB)
Collecting zstandard>=0.23.0 (from langsmith<1.0.0,>=0.3.45->langchain_core)
  Downloading zstandard-0.25.0-cp313-cp313-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (3.3 kB)
Collecting httpcore2==2.12.0 (from httpx2<3,>=2->langsmith<1.0.0,>=0.3.45->langchain_core)
  Downloading httpcore2-2.12.0-py3-none-any.whl.metadata (25 kB)
Collecting truststore>=0.10 (from httpx2<3,>=2->langsmith<1.0.0,>=0.3.45->langchain_core)
  Downloading truststore-0.10.4-py3-none-any.whl.metadata (4.4 kB)
Collecting annotated-types>=0.6.0 (from pydantic<3.0.0,>=2.7.4->langchain)
  Downloading annotated_types-0.8.0-py3-none-any.whl.metadata (15 kB)
Collecting pydantic-core==2.46.5 (from pydantic<3.0.0,>=2.7.4->langchain)
  Downloading pydantic_core-2.46.5-cp313-cp313-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (6.6 kB)
Collecting typing-inspection>=0.4.2 (from pydantic<3.0.0,>=2.7.4->langchain)
  Downloading typing_inspection-0.4.4-py3-none-any.whl.metadata (2.6 kB)
Collecting aiohttp<4.0.0,>=3.8.3 (from langchain_community)
  Downloading aiohttp-3.14.3-cp313-cp313-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl.metadata (8.3 kB)
Collecting httpx-sse<1.0.0,>=0.4.0 (from langchain_community)
  Downloading httpx_sse-0.4.3-py3-none-any.whl.metadata (9.7 kB)
Collecting langchain-classic<2.0.0,>=1.0.7 (from langchain_community)
  Downloading langchain_classic-1.0.8-py3-none-any.whl.metadata (5.1 kB)
Collecting numpy>=2.1.0 (from langchain_community)
  Downloading numpy-2.5.3-cp313-cp313-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl.metadata (6.6 kB)
Collecting pydantic-settings<3.0.0,>=2.10.1 (from langchain_community)
  Downloading pydantic_settings-2.15.0-py3-none-any.whl.metadata (3.9 kB)
Collecting sqlalchemy<3.0.0,>=1.4.0 (from langchain_community)
  Downloading sqlalchemy-2.0.52-cp313-cp313-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl.metadata (9.6 kB)
Collecting aiohappyeyeballs>=2.5.0 (from aiohttp<4.0.0,>=3.8.3->langchain_community)
  Downloading aiohappyeyeballs-2.7.1-py3-none-any.whl.metadata (5.9 kB)
Collecting aiosignal>=1.4.0 (from aiohttp<4.0.0,>=3.8.3->langchain_community)
  Downloading aiosignal-1.4.0-py3-none-any.whl.metadata (3.7 kB)
Collecting attrs>=17.3.0 (from aiohttp<4.0.0,>=3.8.3->langchain_community)
  Downloading attrs-26.1.0-py3-none-any.whl.metadata (8.8 kB)
Collecting frozenlist>=1.1.1 (from aiohttp<4.0.0,>=3.8.3->langchain_community)
  Downloading frozenlist-1.8.0-cp313-cp313-manylinux1_x86_64.manylinux_2_28_x86_64.manylinux_2_5_x86_64.whl.metadata (20 kB)
Collecting multidict<7.0,>=4.5 (from aiohttp<4.0.0,>=3.8.3->langchain_community)
  Downloading multidict-6.8.0-cp313-cp313-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl.metadata (5.3 kB)
Collecting propcache>=0.2.0 (from aiohttp<4.0.0,>=3.8.3->langchain_community)
  Downloading propcache-0.5.2-cp313-cp313-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl.metadata (16 kB)
Collecting yarl<2.0,>=1.17.0 (from aiohttp<4.0.0,>=3.8.3->langchain_community)
  Downloading yarl-1.24.5-cp313-cp313-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl.metadata (103 kB)
Collecting python-dotenv>=0.21.0 (from pydantic-settings<3.0.0,>=2.10.1->langchain_community)
  Downloading python_dotenv-1.2.3-py3-none-any.whl.metadata (29 kB)
Collecting charset_normalizer<4,>=2 (from requests>=2.0.0->langsmith<1.0.0,>=0.3.45->langchain_core)
  Downloading charset_normalizer-3.5.1-cp313-cp313-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl.metadata (45 kB)
Collecting urllib3<3,>=1.26 (from requests>=2.0.0->langsmith<1.0.0,>=0.3.45->langchain_core)
  Downloading urllib3-2.7.0-py3-none-any.whl.metadata (6.9 kB)
Collecting greenlet>=1 (from sqlalchemy<3.0.0,>=1.4.0->langchain_community)
  Downloading greenlet-3.5.5-cp313-cp313-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl.metadata (3.8 kB)
Downloading langchain-1.4.0-py3-none-any.whl (161 kB)
Downloading langchain_core-1.6.3-py3-none-any.whl (571 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 571.8/571.8 kB 261.2 MB/s  0:00:00
Downloading langgraph-1.2.11-py3-none-any.whl (248 kB)
Downloading httpx-0.28.1-py3-none-any.whl (73 kB)
Downloading httpcore-1.0.9-py3-none-any.whl (78 kB)
Downloading jsonpatch-1.33-py2.py3-none-any.whl (12 kB)
Downloading langgraph_checkpoint-4.2.0-py3-none-any.whl (56 kB)
Downloading langgraph_prebuilt-1.1.0-py3-none-any.whl (41 kB)
Downloading langgraph_sdk-0.4.4-py3-none-any.whl (162 kB)
Downloading langsmith-0.12.4-py3-none-any.whl (767 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 767.5/767.5 kB 628.8 MB/s  0:00:00
Downloading httpx2-2.12.0-py3-none-any.whl (95 kB)
Downloading httpcore2-2.12.0-py3-none-any.whl (83 kB)
Downloading pydantic-2.13.5-py3-none-any.whl (472 kB)
Downloading pydantic_core-2.46.5-cp313-cp313-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (2.1 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.1/2.1 MB 568.3 MB/s  0:00:00
Downloading pyyaml-6.0.3-cp313-cp313-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl (801 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 801.6/801.6 kB 755.1 MB/s  0:00:00
Downloading tenacity-9.1.4-py3-none-any.whl (28 kB)
Downloading typing_extensions-4.16.0-py3-none-any.whl (45 kB)
Downloading uuid_utils-0.17.1-cp313-cp313-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (323 kB)
Downloading websockets-16.1.1-cp313-cp313-manylinux1_x86_64.manylinux_2_28_x86_64.manylinux_2_5_x86_64.whl (187 kB)
Downloading langchain_community-0.4.2-py3-none-any.whl (2.4 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.4/2.4 MB 463.3 MB/s  0:00:00
Downloading aiohttp-3.14.3-cp313-cp313-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl (1.8 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.8/1.8 MB 727.8 MB/s  0:00:00
Downloading httpx_sse-0.4.3-py3-none-any.whl (9.0 kB)
Downloading langchain_classic-1.0.8-py3-none-any.whl (1.0 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.0/1.0 MB 735.4 MB/s  0:00:00
Downloading langchain_text_splitters-1.1.2-py3-none-any.whl (35 kB)
Downloading multidict-6.8.0-cp313-cp313-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl (287 kB)
Downloading pydantic_settings-2.15.0-py3-none-any.whl (69 kB)
Downloading requests-2.34.2-py3-none-any.whl (73 kB)
Downloading charset_normalizer-3.5.1-cp313-cp313-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl (250 kB)
Downloading idna-3.19-py3-none-any.whl (68 kB)
Downloading sqlalchemy-2.0.52-cp313-cp313-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl (3.3 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.3/3.3 MB 505.6 MB/s  0:00:00
Downloading urllib3-2.7.0-py3-none-any.whl (131 kB)
Downloading yarl-1.24.5-cp313-cp313-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl (110 kB)
Downloading aiohappyeyeballs-2.7.1-py3-none-any.whl (15 kB)
Downloading aiosignal-1.4.0-py3-none-any.whl (7.5 kB)
Downloading annotated_types-0.8.0-py3-none-any.whl (13 kB)
Downloading anyio-4.15.1-py3-none-any.whl (132 kB)
Downloading attrs-26.1.0-py3-none-any.whl (67 kB)
Downloading certifi-2026.7.22-py3-none-any.whl (136 kB)
Downloading distro-1.9.0-py3-none-any.whl (20 kB)
Downloading frozenlist-1.8.0-cp313-cp313-manylinux1_x86_64.manylinux_2_28_x86_64.manylinux_2_5_x86_64.whl (234 kB)
Downloading greenlet-3.5.5-cp313-cp313-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl (623 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 623.9/623.9 kB 558.4 MB/s  0:00:00
Downloading h11-0.16.0-py3-none-any.whl (37 kB)
Downloading jsonpointer-3.1.1-py3-none-any.whl (7.7 kB)
Downloading langchain_protocol-0.0.19-py3-none-any.whl (7.3 kB)
Downloading numpy-2.5.3-cp313-cp313-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl (16.7 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 16.7/16.7 MB 375.1 MB/s  0:00:00
Downloading orjson-3.12.0-cp313-cp313-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (131 kB)
Downloading ormsgpack-1.12.2-cp313-cp313-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (212 kB)
Downloading packaging-26.3-py3-none-any.whl (129 kB)
Downloading propcache-0.5.2-cp313-cp313-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl (61 kB)
Downloading python_dotenv-1.2.3-py3-none-any.whl (22 kB)
Downloading requests_toolbelt-1.0.0-py2.py3-none-any.whl (54 kB)
Downloading sniffio-1.3.1-py3-none-any.whl (10 kB)
Downloading truststore-0.10.4-py3-none-any.whl (18 kB)
Downloading typing_inspection-0.4.4-py3-none-any.whl (14 kB)
Downloading xxhash-4.0.1-cp313-cp313-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl (268 kB)
Downloading zstandard-0.25.0-cp313-cp313-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (5.5 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.5/5.5 MB 622.7 MB/s  0:00:00
Installing collected packages: zstandard, xxhash, websockets, uuid-utils, urllib3, typing-extensions, truststore, tenacity, sniffio, pyyaml, python-dotenv, propcache, packaging, ormsgpack, orjson, numpy, multidict, jsonpointer, idna, httpx-sse, h11, greenlet, frozenlist, distro, charset_normalizer, certifi, attrs, annotated-types, aiohappyeyeballs, yarl, typing-inspection, sqlalchemy, requests, pydantic-core, langchain-protocol, jsonpatch, httpcore2, httpcore, anyio, aiosignal, requests-toolbelt, pydantic, httpx2, httpx, aiohttp, pydantic-settings, langsmith, langchain_core, langgraph-sdk, langgraph-checkpoint, langchain-text-splitters, langgraph-prebuilt, langchain-classic, langgraph, langchain_community, langchain
  Attempting uninstall: zstandard
    Found existing installation: zstandard 0.25.0
    Uninstalling zstandard-0.25.0:
      Successfully uninstalled zstandard-0.25.0
  Attempting uninstall: xxhash
    Found existing installation: xxhash 4.0.1
    Uninstalling xxhash-4.0.1:
      Successfully uninstalled xxhash-4.0.1
  Attempting uninstall: websockets
    Found existing installation: websockets 16.1.1
    Uninstalling websockets-16.1.1:
      Successfully uninstalled websockets-16.1.1
  Attempting uninstall: uuid-utils
    Found existing installation: uuid_utils 0.17.1
    Uninstalling uuid_utils-0.17.1:
      Successfully uninstalled uuid_utils-0.17.1
  Attempting uninstall: urllib3
    Found existing installation: urllib3 2.7.0
    Uninstalling urllib3-2.7.0:
      Successfully uninstalled urllib3-2.7.0
  Attempting uninstall: typing-extensions
    Found existing installation: typing_extensions 4.16.0
    Uninstalling typing_extensions-4.16.0:
      Successfully uninstalled typing_extensions-4.16.0
  Attempting uninstall: truststore
    Found existing installation: truststore 0.10.4
    Uninstalling truststore-0.10.4:
      Successfully uninstalled truststore-0.10.4
  Attempting uninstall: tenacity
    Found existing installation: tenacity 9.1.4
    Uninstalling tenacity-9.1.4:
      Successfully uninstalled tenacity-9.1.4
  Attempting uninstall: sniffio
    Found existing installation: sniffio 1.3.1
    Uninstalling sniffio-1.3.1:
      Successfully uninstalled sniffio-1.3.1
  Attempting uninstall: pyyaml
    Found existing installation: PyYAML 6.0.3
    Uninstalling PyYAML-6.0.3:
      Successfully uninstalled PyYAML-6.0.3
  Attempting uninstall: python-dotenv
    Found existing installation: python-dotenv 1.2.3
    Uninstalling python-dotenv-1.2.3:
      Successfully uninstalled python-dotenv-1.2.3
  Attempting uninstall: propcache
    Found existing installation: propcache 0.5.2
    Uninstalling propcache-0.5.2:
      Successfully uninstalled propcache-0.5.2
  Attempting uninstall: packaging
    Found existing installation: packaging 26.3
    Uninstalling packaging-26.3:
      Successfully uninstalled packaging-26.3
  Attempting uninstall: ormsgpack
    Found existing installation: ormsgpack 1.12.2
    Uninstalling ormsgpack-1.12.2:
      Successfully uninstalled ormsgpack-1.12.2
  Attempting uninstall: orjson
    Found existing installation: orjson 3.12.0
    Uninstalling orjson-3.12.0:
      Successfully uninstalled orjson-3.12.0
  Attempting uninstall: numpy
    Found existing installation: numpy 2.5.3
    Uninstalling numpy-2.5.3:
      Successfully uninstalled numpy-2.5.3
  Attempting uninstall: multidict
    Found existing installation: multidict 6.8.0
    Uninstalling multidict-6.8.0:
      Successfully uninstalled multidict-6.8.0
  Attempting uninstall: jsonpointer
    Found existing installation: jsonpointer 3.1.1
    Uninstalling jsonpointer-3.1.1:
      Successfully uninstalled jsonpointer-3.1.1
  Attempting uninstall: idna
    Found existing installation: idna 3.19
    Uninstalling idna-3.19:
      Successfully uninstalled idna-3.19
  Attempting uninstall: httpx-sse
    Found existing installation: httpx-sse 0.4.3
    Uninstalling httpx-sse-0.4.3:
      Successfully uninstalled httpx-sse-0.4.3
  Attempting uninstall: h11
    Found existing installation: h11 0.16.0
    Uninstalling h11-0.16.0:
      Successfully uninstalled h11-0.16.0
  Attempting uninstall: greenlet
    Found existing installation: greenlet 3.5.5
    Uninstalling greenlet-3.5.5:
      Successfully uninstalled greenlet-3.5.5
  Attempting uninstall: frozenlist
    Found existing installation: frozenlist 1.8.0
    Uninstalling frozenlist-1.8.0:
      Successfully uninstalled frozenlist-1.8.0
  Attempting uninstall: distro
    Found existing installation: distro 1.9.0
    Uninstalling distro-1.9.0:
      Successfully uninstalled distro-1.9.0
  Attempting uninstall: charset_normalizer
    Found existing installation: charset-normalizer 3.5.1
    Uninstalling charset-normalizer-3.5.1:
      Successfully uninstalled charset-normalizer-3.5.1
  Attempting uninstall: certifi
    Found existing installation: certifi 2026.7.22
    Uninstalling certifi-2026.7.22:
      Successfully uninstalled certifi-2026.7.22
  Attempting uninstall: attrs
    Found existing installation: attrs 26.1.0
    Uninstalling attrs-26.1.0:
      Successfully uninstalled attrs-26.1.0
  Attempting uninstall: annotated-types
    Found existing installation: annotated-types 0.8.0
    Uninstalling annotated-types-0.8.0:
      Successfully uninstalled annotated-types-0.8.0
  Attempting uninstall: aiohappyeyeballs
    Found existing installation: aiohappyeyeballs 2.7.1
    Uninstalling aiohappyeyeballs-2.7.1:
      Successfully uninstalled aiohappyeyeballs-2.7.1
  Attempting uninstall: yarl
    Found existing installation: yarl 1.24.5
    Uninstalling yarl-1.24.5:
      Successfully uninstalled yarl-1.24.5
  Attempting uninstall: typing-inspection
    Found existing installation: typing-inspection 0.4.4
    Uninstalling typing-inspection-0.4.4:
      Successfully uninstalled typing-inspection-0.4.4
  Attempting uninstall: sqlalchemy
    Found existing installation: SQLAlchemy 2.0.52
    Uninstalling SQLAlchemy-2.0.52:
      Successfully uninstalled SQLAlchemy-2.0.52
  Attempting uninstall: requests
    Found existing installation: requests 2.34.2
    Uninstalling requests-2.34.2:
      Successfully uninstalled requests-2.34.2
  Attempting uninstall: pydantic-core
    Found existing installation: pydantic_core 2.46.5
    Uninstalling pydantic_core-2.46.5:
      Successfully uninstalled pydantic_core-2.46.5
  Attempting uninstall: langchain-protocol
    Found existing installation: langchain-protocol 0.0.19
    Uninstalling langchain-protocol-0.0.19:

Documento 3: Paciente Carlos Pereira, 22 anos. Queixa principal: dor de garganta intensa, febre 38.5°C, tosse seca. Início dos sintomas há 3 dias. Exame físico: am...
Collecting langchain
  Downloading langchain-1.4.0-py3-none-any.whl.metadata (6.2 kB)
Collecting langchain_community
  Downloading langchain_community-0.4.2-py3-none-any.whl.metadata (3.4 kB)
Collecting langchain_core
  Downloading langchain_core-1.6.3-py3-none-any.whl.metadata (4.8 kB)
Collecting langgraph
  Downloading langgraph-1.2.11-py3-none-any.whl.metadata (4.9 kB)
Collecting langchain-text-splitters
  Downloading langchain_text_splitters-1.1.2-py3-none-any.whl.metadata (3.3 kB)
Collecting pydantic<3.0.0,>=2.7.4 (from langchain)
  Downloading pydantic-2.13.5-py3-none-any.whl.metadata (110 kB)
Collecting httpx<1.0.0,>=0.23.0 (from langchain_core)
  Downloading httpx-0.28.1-py3-none-any.whl.metadata (7.1 kB)
Collecting jsonpatch<2.0.0,>=1.33.0 (from langchain_core)
  Downloading jsonpatch-1.33-py2.py3-none-any.whl.metadata (3.0 kB)
Collecting langchain-protocol>=0.0.17 (from langchain_core)
  Downloading langchain_protocol-0.0.19-py3-none-any.whl.metadata (2.4 kB)
Collecting langsmith<1.0.0,>=0.3.45 (from langchain_core)
  Downloading langsmith-0.12.4-py3-none-any.whl.metadata (22 kB)
Collecting packaging>=23.2.0 (from langchain_core)
  Downloading packaging-26.3-py3-none-any.whl.metadata (3.5 kB)
Collecting pyyaml<7.0.0,>=5.3.0 (from langchain_core)
  Downloading pyyaml-6.0.3-cp313-cp313-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl.metadata (2.4 kB)
Collecting tenacity!=8.4.0,<10.0.0,>=8.1.0 (from langchain_core)
  Downloading tenacity-9.1.4-py3-none-any.whl.metadata (1.2 kB)
Collecting typing-extensions<5.0.0,>=4.7.0 (from langchain_core)
  Downloading typing_extensions-4.16.0-py3-none-any.whl.metadata (3.3 kB)
Collecting uuid-utils<1.0,>=0.12.0 (from langchain_core)
  Downloading uuid_utils-0.17.1-cp313-cp313-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (6.4 kB)
Collecting langgraph-checkpoint<5.0.0,>=4.1.0 (from langgraph)
  Downloading langgraph_checkpoint-4.2.0-py3-none-any.whl.metadata (6.7 kB)
Collecting langgraph-prebuilt<1.2.0,>=1.1.0 (from langgraph)
  Downloading langgraph_prebuilt-1.1.0-py3-none-any.whl.metadata (5.2 kB)
Collecting langgraph-sdk<0.5.0,>=0.4.2 (from langgraph)
  Downloading langgraph_sdk-0.4.4-py3-none-any.whl.metadata (5.1 kB)
Collecting xxhash>=3.5.0 (from langgraph)
  Downloading xxhash-4.0.1-cp313-cp313-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl.metadata (17 kB)
Collecting anyio (from httpx<1.0.0,>=0.23.0->langchain_core)
  Downloading anyio-4.15.1-py3-none-any.whl.metadata (4.7 kB)
Collecting certifi (from httpx<1.0.0,>=0.23.0->langchain_core)
  Downloading certifi-2026.7.22-py3-none-any.whl.metadata (2.5 kB)
Collecting httpcore==1.* (from httpx<1.0.0,>=0.23.0->langchain_core)
  Downloading httpcore-1.0.9-py3-none-any.whl.metadata (21 kB)
Collecting idna (from httpx<1.0.0,>=0.23.0->langchain_core)
  Downloading idna-3.19-py3-none-any.whl.metadata (9.2 kB)
Collecting h11>=0.16 (from httpcore==1.*->httpx<1.0.0,>=0.23.0->langchain_core)
  Downloading h11-0.16.0-py3-none-any.whl.metadata (8.3 kB)
Collecting jsonpointer>=1.9 (from jsonpatch<2.0.0,>=1.33.0->langchain_core)
  Downloading jsonpointer-3.1.1-py3-none-any.whl.metadata (2.4 kB)
Collecting ormsgpack>=1.12.0 (from langgraph-checkpoint<5.0.0,>=4.1.0->langgraph)
  Downloading ormsgpack-1.12.2-cp313-cp313-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (3.2 kB)
Collecting orjson>=3.11.5 (from langgraph-sdk<0.5.0,>=0.4.2->langgraph)
  Downloading orjson-3.12.0-cp313-cp313-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (41 kB)
Collecting websockets<17,>=14 (from langgraph-sdk<0.5.0,>=0.4.2->langgraph)
  Downloading websockets-16.1.1-cp313-cp313-manylinux1_x86_64.manylinux_2_28_x86_64.manylinux_2_5_x86_64.whl.metadata (6.8 kB)
Collecting distro>=1.7.0 (from langsmith<1.0.0,>=0.3.45->langchain_core)
  Downloading distro-1.9.0-py3-none-any.whl.metadata (6.8 kB)
Collecting httpx2<3,>=2 (from langsmith<1.0.0,>=0.3.45->langchain_core)
  Downloading httpx2-2.12.0-py3-none-any.whl.metadata (9.5 kB)
Collecting requests-toolbelt>=1.0.0 (from langsmith<1.0.0,>=0.3.45->langchain_core)
  Downloading requests_toolbelt-1.0.0-py2.py3-none-any.whl.metadata (14 kB)
Collecting requests>=2.0.0 (from langsmith<1.0.0,>=0.3.45->langchain_core)
  Downloading requests-2.34.2-py3-none-any.whl.metadata (4.8 kB)
Collecting sniffio>=1.1 (from langsmith<1.0.0,>=0.3.45->langchain_core)
  Downloading sniffio-1.3.1-py3-none-any.whl.metadata (3.9 kB)
Collecting zstandard>=0.23.0 (from langsmith<1.0.0,>=0.3.45->langchain_core)
  Downloading zstandard-0.25.0-cp313-cp313-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (3.3 kB)
Collecting httpcore2==2.12.0 (from httpx2<3,>=2->langsmith<1.0.0,>=0.3.45->langchain_core)
  Downloading httpcore2-2.12.0-py3-none-any.whl.metadata (25 kB)
Collecting truststore>=0.10 (from httpx2<3,>=2->langsmith<1.0.0,>=0.3.45->langchain_core)
  Downloading truststore-0.10.4-py3-none-any.whl.metadata (4.4 kB)
Collecting annotated-types>=0.6.0 (from pydantic<3.0.0,>=2.7.4->langchain)
  Downloading annotated_types-0.8.0-py3-none-any.whl.metadata (15 kB)
Collecting pydantic-core==2.46.5 (from pydantic<3.0.0,>=2.7.4->langchain)
  Downloading pydantic_core-2.46.5-cp313-cp313-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (6.6 kB)
Collecting typing-inspection>=0.4.2 (from pydantic<3.0.0,>=2.7.4->langchain)
  Downloading typing_inspection-0.4.4-py3-none-any.whl.metadata (2.6 kB)
Collecting aiohttp<4.0.0,>=3.8.3 (from langchain_community)
  Downloading aiohttp-3.14.3-cp313-cp313-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl.metadata (8.3 kB)
Collecting httpx-sse<1.0.0,>=0.4.0 (from langchain_community)
  Downloading httpx_sse-0.4.3-py3-none-any.whl.metadata (9.7 kB)
Collecting langchain-classic<2.0.0,>=1.0.7 (from langchain_community)
  Downloading langchain_classic-1.0.8-py3-none-any.whl.metadata (5.1 kB)
Collecting numpy>=2.1.0 (from langchain_community)
  Downloading numpy-2.5.3-cp313-cp313-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl.metadata (6.6 kB)
Collecting pydantic-settings<3.0.0,>=2.10.1 (from langchain_community)
  Downloading pydantic_settings-2.15.0-py3-none-any.whl.metadata (3.9 kB)
Collecting sqlalchemy<3.0.0,>=1.4.0 (from langchain_community)
  Downloading sqlalchemy-2.0.52-cp313-cp313-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl.metadata (9.6 kB)
Collecting aiohappyeyeballs>=2.5.0 (from aiohttp<4.0.0,>=3.8.3->langchain_community)
  Downloading aiohappyeyeballs-2.7.1-py3-none-any.whl.metadata (5.9 kB)
Collecting aiosignal>=1.4.0 (from aiohttp<4.0.0,>=3.8.3->langchain_community)
  Downloading aiosignal-1.4.0-py3-none-any.whl.metadata (3.7 kB)
Collecting attrs>=17.3.0 (from aiohttp<4.0.0,>=3.8.3->langchain_community)
  Downloading attrs-26.1.0-py3-none-any.whl.metadata (8.8 kB)
Collecting frozenlist>=1.1.1 (from aiohttp<4.0.0,>=3.8.3->langchain_community)
  Downloading frozenlist-1.8.0-cp313-cp313-manylinux1_x86_64.manylinux_2_28_x86_64.manylinux_2_5_x86_64.whl.metadata (20 kB)
Collecting multidict<7.0,>=4.5 (from aiohttp<4.0.0,>=3.8.3->langchain_community)
  Downloading multidict-6.8.0-cp313-cp313-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl.metadata (5.3 kB)
Collecting propcache>=0.2.0 (from aiohttp<4.0.0,>=3.8.3->langchain_community)
  Downloading propcache-0.5.2-cp313-cp313-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl.metadata (16 kB)
Collecting yarl<2.0,>=1.17.0 (from aiohttp<4.0.0,>=3.8.3->langchain_community)
  Downloading yarl-1.24.5-cp313-cp313-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl.metadata (103 kB)
Collecting python-dotenv>=0.21.0 (from pydantic-settings<3.0.0,>=2.10.1->langchain_community)
  Downloading python_dotenv-1.2.3-py3-none-any.whl.metadata (29 kB)
Collecting charset_normalizer<4,>=2 (from requests>=2.0.0->langsmith<1.0.0,>=0.3.45->langchain_core)
  Downloading charset_normalizer-3.5.1-cp313-cp313-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl.metadata (45 kB)
Collecting urllib3<3,>=1.26 (from requests>=2.0.0->langsmith<1.0.0,>=0.3.45->langchain_core)
  Downloading urllib3-2.7.0-py3-none-any.whl.metadata (6.9 kB)
Collecting greenlet>=1 (from sqlalchemy<3.0.0,>=1.4.0->langchain_community)
  Downloading greenlet-3.5.5-cp313-cp313-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl.metadata (3.8 kB)
Downloading langchain-1.4.0-py3-none-any.whl (161 kB)
Downloading langchain_core-1.6.3-py3-none-any.whl (571 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 571.8/571.8 kB 301.0 MB/s  0:00:00
Downloading langgraph-1.2.11-py3-none-any.whl (248 kB)
Downloading httpx-0.28.1-py3-none-any.whl (73 kB)
Downloading httpcore-1.0.9-py3-none-any.whl (78 kB)
Downloading jsonpatch-1.33-py2.py3-none-any.whl (12 kB)
Downloading langgraph_checkpoint-4.2.0-py3-none-any.whl (56 kB)
Downloading langgraph_prebuilt-1.1.0-py3-none-any.whl (41 kB)
Downloading langgraph_sdk-0.4.4-py3-none-any.whl (162 kB)
Downloading langsmith-0.12.4-py3-none-any.whl (767 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 767.5/767.5 kB 747.1 MB/s  0:00:00
Downloading httpx2-2.12.0-py3-none-any.whl (95 kB)
Downloading httpcore2-2.12.0-py3-none-any.whl (83 kB)
Downloading pydantic-2.13.5-py3-none-any.whl (472 kB)
Downloading pydantic_core-2.46.5-cp313-cp313-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (2.1 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.1/2.1 MB 705.6 MB/s  0:00:00
Downloading pyyaml-6.0.3-cp313-cp313-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl (801 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 801.6/801.6 kB 701.3 MB/s  0:00:00
Downloading tenacity-9.1.4-py3-none-any.whl (28 kB)
Downloading typing_extensions-4.16.0-py3-none-any.whl (45 kB)
Downloading uuid_utils-0.17.1-cp313-cp313-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (323 kB)
Downloading websockets-16.1.1-cp313-cp313-manylinux1_x86_64.manylinux_2_28_x86_64.manylinux_2_5_x86_64.whl (187 kB)
Downloading langchain_community-0.4.2-py3-none-any.whl (2.4 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.4/2.4 MB 707.4 MB/s  0:00:00
Downloading aiohttp-3.14.3-cp313-cp313-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl (1.8 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.8/1.8 MB 579.1 MB/s  0:00:00
Downloading httpx_sse-0.4.3-py3-none-any.whl (9.0 kB)
Downloading langchain_classic-1.0.8-py3-none-any.whl (1.0 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.0/1.0 MB 620.2 MB/s  0:00:00
Downloading langchain_text_splitters-1.1.2-py3-none-any.whl (35 kB)
Downloading multidict-6.8.0-cp313-cp313-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl (287 kB)
Downloading pydantic_settings-2.15.0-py3-none-any.whl (69 kB)
Downloading requests-2.34.2-py3-none-any.whl (73 kB)
Downloading charset_normalizer-3.5.1-cp313-cp313-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl (250 kB)
Downloading idna-3.19-py3-none-any.whl (68 kB)
Downloading sqlalchemy-2.0.52-cp313-cp313-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl (3.3 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.3/3.3 MB 257.9 MB/s  0:00:00
Downloading urllib3-2.7.0-py3-none-any.whl (131 kB)
Downloading yarl-1.24.5-cp313-cp313-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl (110 kB)
Downloading aiohappyeyeballs-2.7.1-py3-none-any.whl (15 kB)
Downloading aiosignal-1.4.0-py3-none-any.whl (7.5 kB)
Downloading annotated_types-0.8.0-py3-none-any.whl (13 kB)
Downloading anyio-4.15.1-py3-none-any.whl (132 kB)
Downloading attrs-26.1.0-py3-none-any.whl (67 kB)
Downloading certifi-2026.7.22-py3-none-any.whl (136 kB)
Downloading distro-1.9.0-py3-none-any.whl (20 kB)
Downloading frozenlist-1.8.0-cp313-cp313-manylinux1_x86_64.manylinux_2_28_x86_64.manylinux_2_5_x86_64.whl (234 kB)
Downloading greenlet-3.5.5-cp313-cp313-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl (623 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 623.9/623.9 kB 641.7 MB/s  0:00:00
Downloading h11-0.16.0-py3-none-any.whl (37 kB)
Downloading jsonpointer-3.1.1-py3-none-any.whl (7.7 kB)
Downloading langchain_protocol-0.0.19-py3-none-any.whl (7.3 kB)
Downloading numpy-2.5.3-cp313-cp313-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl (16.7 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 16.7/16.7 MB 416.4 MB/s  0:00:00
Downloading orjson-3.12.0-cp313-cp313-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (131 kB)
Downloading ormsgpack-1.12.2-cp313-cp313-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (212 kB)
Downloading packaging-26.3-py3-none-any.whl (129 kB)
Downloading propcache-0.5.2-cp313-cp313-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl (61 kB)
Downloading python_dotenv-1.2.3-py3-none-any.whl (22 kB)
Downloading requests_toolbelt-1.0.0-py2.py3-none-any.whl (54 kB)
Downloading sniffio-1.3.1-py3-none-any.whl (10 kB)
Downloading truststore-0.10.4-py3-none-any.whl (18 kB)
Downloading typing_inspection-0.4.4-py3-none-any.whl (14 kB)
Downloading xxhash-4.0.1-cp313-cp313-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl (268 kB)
Downloading zstandard-0.25.0-cp313-cp313-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (5.5 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.5/5.5 MB 188.6 MB/s  0:00:00
Installing collected packages: zstandard, xxhash, websockets, uuid-utils, urllib3, typing-extensions, truststore, tenacity, sniffio, pyyaml, python-dotenv, propcache, packaging, ormsgpack, orjson, numpy, multidict, jsonpointer, idna, httpx-sse, h11, greenlet, frozenlist, distro, charset_normalizer, certifi, attrs, annotated-types, aiohappyeyeballs, yarl, typing-inspection, sqlalchemy, requests, pydantic-core, langchain-protocol, jsonpatch, httpcore2, httpcore, anyio, aiosignal, requests-toolbelt, pydantic, httpx2, httpx, aiohttp, pydantic-settings, langsmith, langchain_core, langgraph-sdk, langgraph-checkpoint, langchain-text-splitters, langgraph-prebuilt, langchain-classic, langgraph, langchain_community, langchain
  Attempting uninstall: zstandard
    Found existing installation: zstandard 0.25.0
    Uninstalling zstandard-0.25.0:
      Successfully uninstalled zstandard-0.25.0
  Attempting uninstall: xxhash
    Found existing installation: xxhash 4.0.1
    Uninstalling xxhash-4.0.1:
      Successfully uninstalled xxhash-4.0.1
  Attempting uninstall: websockets
    Found existing installation: websockets 16.1.1
    Uninstalling websockets-16.1.1:
      Successfully uninstalled websockets-16.1.1
  Attempting uninstall: uuid-utils
    Found existing installation: uuid_utils 0.17.1
    Uninstalling uuid_utils-0.17.1:
      Successfully uninstalled uuid_utils-0.17.1
  Attempting uninstall: urllib3
    Found existing installation: urllib3 2.7.0
    Uninstalling urllib3-2.7.0:
      Successfully uninstalled urllib3-2.7.0
  Attempting uninstall: typing-extensions
    Found existing installation: typing_extensions 4.16.0
    Uninstalling typing_extensions-4.16.0:
      Successfully uninstalled typing_extensions-4.16.0
  Attempting uninstall: truststore
    Found existing installation: truststore 0.10.4
    Uninstalling truststore-0.10.4:
      Successfully uninstalled truststore-0.10.4
  Attempting uninstall: tenacity
    Found existing installation: tenacity 9.1.4
    Uninstalling tenacity-9.1.4:
      Successfully uninstalled tenacity-9.1.4
  Attempting uninstall: sniffio
    Found existing installation: sniffio 1.3.1
    Uninstalling sniffio-1.3.1:
      Successfully uninstalled sniffio-1.3.1
  Attempting uninstall: pyyaml
    Found existing installation: PyYAML 6.0.3
    Uninstalling PyYAML-6.0.3:
      Successfully uninstalled PyYAML-6.0.3
  Attempting uninstall: python-dotenv
    Found existing installation: python-dotenv 1.2.3
    Uninstalling python-dotenv-1.2.3:
      Successfully uninstalled python-dotenv-1.2.3
  Attempting uninstall: propcache
    Found existing installation: propcache 0.5.2
    Uninstalling propcache-0.5.2:
      Successfully uninstalled propcache-0.5.2
  Attempting uninstall: packaging
    Found existing installation: packaging 26.3
    Uninstalling packaging-26.3:
      Successfully uninstalled packaging-26.3
  Attempting uninstall: ormsgpack
    Found existing installation: ormsgpack 1.12.2
    Uninstalling ormsgpack-1.12.2:
      Successfully uninstalled ormsgpack-1.12.2
  Attempting uninstall: orjson
    Found existing installation: orjson 3.12.0
    Uninstalling orjson-3.12.0:
      Successfully uninstalled orjson-3.12.0
  Attempting uninstall: numpy
    Found existing installation: numpy 2.5.3
    Uninstalling numpy-2.5.3:
      Successfully uninstalled numpy-2.5.3
  Attempting uninstall: multidict
    Found existing installation: multidict 6.8.0
    Uninstalling multidict-6.8.0:
      Successfully uninstalled multidict-6.8.0
  Attempting uninstall: jsonpointer
    Found existing installation: jsonpointer 3.1.1
    Uninstalling jsonpointer-3.1.1:
      Successfully uninstalled jsonpointer-3.1.1
  Attempting uninstall: idna
    Found existing installation: idna 3.19
    Uninstalling idna-3.19:
      Successfully uninstalled idna-3.19
  Attempting uninstall: httpx-sse
    Found existing installation: httpx-sse 0.4.3
    Uninstalling httpx-sse-0.4.3:
      Successfully uninstalled httpx-sse-0.4.3
  Attempting uninstall: h11
    Found existing installation: h11 0.16.0
    Uninstalling h11-0.16.0:
      Successfully uninstalled h11-0.16.0
  Attempting uninstall: greenlet
    Found existing installation: greenlet 3.5.5
    Uninstalling greenlet-3.5.5:
      Successfully uninstalled greenlet-3.5.5
  Attempting uninstall: frozenlist
    Found existing installation: frozenlist 1.8.0
    Uninstalling frozenlist-1.8.0:
      Successfully uninstalled frozenlist-1.8.0
  Attempting uninstall: distro
    Found existing installation: distro 1.9.0
    Uninstalling distro-1.9.0:
      Successfully uninstalled distro-1.9.0
  Attempting uninstall: charset_normalizer
    Found existing installation: charset-normalizer 3.5.1
    Uninstalling charset-normalizer-3.5.1:
      Successfully uninstalled charset-normalizer-3.5.1
  Attempting uninstall: certifi
    Found existing installation: certifi 2026.7.22
    Uninstalling certifi-2026.7.22:
      Successfully uninstalled certifi-2026.7.22
  Attempting uninstall: attrs
    Found existing installation: attrs 26.1.0
    Uninstalling attrs-26.1.0:
      Successfully uninstalled attrs-26.1.0
  Attempting uninstall: annotated-types
    Found existing installation: annotated-types 0.8.0
    Uninstalling annotated-types-0.8.0:
      Successfully uninstalled annotated-types-0.8.0
  Attempting uninstall: aiohappyeyeballs
    Found existing installation: aiohappyeyeballs 2.7.1
    Uninstalling aiohappyeyeballs-2.7.1:
      Successfully uninstalled aiohappyeyeballs-2.7.1
  Attempting uninstall: yarl
    Found existing installation: yarl 1.24.5
    Uninstalling yarl-1.24.5:
      Successfully uninstalled yarl-1.24.5
  Attempting uninstall: typing-inspection
    Found existing installation: typing-inspection 0.4.4
    Uninstalling typing-inspection-0.4.4:
      Successfully uninstalled typing-inspection-0.4.4
  Attempting uninstall: sqlalchemy
    Found existing installation: SQLAlchemy 2.0.52
    Uninstalling SQLAlchemy-2.0.52:
      Successfully uninstalled SQLAlchemy-2.0.52
  Attempting uninstall: requests
    Found existing installation: requests 2.34.2
    Uninstalling requests-2.34.2:
      Successfully uninstalled requests-2.34.2
  Attempting uninstall: pydantic-core
    Found existing installation: pydantic_core 2.46.5
    Uninstalling pydantic_core-2.46.5:
      Successfully uninstalled pydantic_core-2.46.5
  Attempting uninstall: langchain-protocol
    Found existing installation: langchain-protocol 0.0.19
    Uninstalling langchain-protocol-0.0.19:

Documento 4: Paciente Maria Souza, 60 anos. Diagnóstico de hipertensão arterial há 5 anos. Medicação: Losartana 50mg/dia. Pressão arterial média: 140/90 mmHg. Diet...
Collecting langchain
  Downloading langchain-1.4.0-py3-none-any.whl.metadata (6.2 kB)
Collecting langchain_community
  Downloading langchain_community-0.4.2-py3-none-any.whl.metadata (3.4 kB)
Collecting langchain_core
  Downloading langchain_core-1.6.3-py3-none-any.whl.metadata (4.8 kB)
Collecting langgraph
  Downloading langgraph-1.2.11-py3-none-any.whl.metadata (4.9 kB)
Collecting langchain-text-splitters
  Downloading langchain_text_splitters-1.1.2-py3-none-any.whl.metadata (3.3 kB)
Collecting pydantic<3.0.0,>=2.7.4 (from langchain)
  Downloading pydantic-2.13.5-py3-none-any.whl.metadata (110 kB)
Collecting httpx<1.0.0,>=0.23.0 (from langchain_core)
  Downloading httpx-0.28.1-py3-none-any.whl.metadata (7.1 kB)
Collecting jsonpatch<2.0.0,>=1.33.0 (from langchain_core)
  Downloading jsonpatch-1.33-py2.py3-none-any.whl.metadata (3.0 kB)
Collecting langchain-protocol>=0.0.17 (from langchain_core)
  Downloading langchain_protocol-0.0.19-py3-none-any.whl.metadata (2.4 kB)
Collecting langsmith<1.0.0,>=0.3.45 (from langchain_core)
  Downloading langsmith-0.12.4-py3-none-any.whl.metadata (22 kB)
Collecting packaging>=23.2.0 (from langchain_core)
  Downloading packaging-26.3-py3-none-any.whl.metadata (3.5 kB)
Collecting pyyaml<7.0.0,>=5.3.0 (from langchain_core)
  Downloading pyyaml-6.0.3-cp313-cp313-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl.metadata (2.4 kB)
Collecting tenacity!=8.4.0,<10.0.0,>=8.1.0 (from langchain_core)
  Downloading tenacity-9.1.4-py3-none-any.whl.metadata (1.2 kB)
Collecting typing-extensions<5.0.0,>=4.7.0 (from langchain_core)
  Downloading typing_extensions-4.16.0-py3-none-any.whl.metadata (3.3 kB)
Collecting uuid-utils<1.0,>=0.12.0 (from langchain_core)
  Downloading uuid_utils-0.17.1-cp313-cp313-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (6.4 kB)
Collecting langgraph-checkpoint<5.0.0,>=4.1.0 (from langgraph)
  Downloading langgraph_checkpoint-4.2.0-py3-none-any.whl.metadata (6.7 kB)
Collecting langgraph-prebuilt<1.2.0,>=1.1.0 (from langgraph)
  Downloading langgraph_prebuilt-1.1.0-py3-none-any.whl.metadata (5.2 kB)
Collecting langgraph-sdk<0.5.0,>=0.4.2 (from langgraph)
  Downloading langgraph_sdk-0.4.4-py3-none-any.whl.metadata (5.1 kB)
Collecting xxhash>=3.5.0 (from langgraph)
  Downloading xxhash-4.0.1-cp313-cp313-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl.metadata (17 kB)
Collecting anyio (from httpx<1.0.0,>=0.23.0->langchain_core)
  Downloading anyio-4.15.1-py3-none-any.whl.metadata (4.7 kB)
Collecting certifi (from httpx<1.0.0,>=0.23.0->langchain_core)
  Downloading certifi-2026.7.22-py3-none-any.whl.metadata (2.5 kB)
Collecting httpcore==1.* (from httpx<1.0.0,>=0.23.0->langchain_core)
  Downloading httpcore-1.0.9-py3-none-any.whl.metadata (21 kB)
Collecting idna (from httpx<1.0.0,>=0.23.0->langchain_core)
  Downloading idna-3.19-py3-none-any.whl.metadata (9.2 kB)
Collecting h11>=0.16 (from httpcore==1.*->httpx<1.0.0,>=0.23.0->langchain_core)
  Downloading h11-0.16.0-py3-none-any.whl.metadata (8.3 kB)
Collecting jsonpointer>=1.9 (from jsonpatch<2.0.0,>=1.33.0->langchain_core)
  Downloading jsonpointer-3.1.1-py3-none-any.whl.metadata (2.4 kB)
Collecting ormsgpack>=1.12.0 (from langgraph-checkpoint<5.0.0,>=4.1.0->langgraph)
  Downloading ormsgpack-1.12.2-cp313-cp313-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (3.2 kB)
Collecting orjson>=3.11.5 (from langgraph-sdk<0.5.0,>=0.4.2->langgraph)
  Downloading orjson-3.12.0-cp313-cp313-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (41 kB)
Collecting websockets<17,>=14 (from langgraph-sdk<0.5.0,>=0.4.2->langgraph)
  Downloading websockets-16.1.1-cp313-cp313-manylinux1_x86_64.manylinux_2_28_x86_64.manylinux_2_5_x86_64.whl.metadata (6.8 kB)
Collecting distro>=1.7.0 (from langsmith<1.0.0,>=0.3.45->langchain_core)
  Downloading distro-1.9.0-py3-none-any.whl.metadata (6.8 kB)
Collecting httpx2<3,>=2 (from langsmith<1.0.0,>=0.3.45->langchain_core)
  Downloading httpx2-2.12.0-py3-none-any.whl.metadata (9.5 kB)
Collecting requests-toolbelt>=1.0.0 (from langsmith<1.0.0,>=0.3.45->langchain_core)
  Downloading requests_toolbelt-1.0.0-py2.py3-none-any.whl.metadata (14 kB)
Collecting requests>=2.0.0 (from langsmith<1.0.0,>=0.3.45->langchain_core)
  Downloading requests-2.34.2-py3-none-any.whl.metadata (4.8 kB)
Collecting sniffio>=1.1 (from langsmith<1.0.0,>=0.3.45->langchain_core)
  Downloading sniffio-1.3.1-py3-none-any.whl.metadata (3.9 kB)
Collecting zstandard>=0.23.0 (from langsmith<1.0.0,>=0.3.45->langchain_core)
  Downloading zstandard-0.25.0-cp313-cp313-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (3.3 kB)
Collecting httpcore2==2.12.0 (from httpx2<3,>=2->langsmith<1.0.0,>=0.3.45->langchain_core)
  Downloading httpcore2-2.12.0-py3-none-any.whl.metadata (25 kB)
Collecting truststore>=0.10 (from httpx2<3,>=2->langsmith<1.0.0,>=0.3.45->langchain_core)
  Downloading truststore-0.10.4-py3-none-any.whl.metadata (4.4 kB)
Collecting annotated-types>=0.6.0 (from pydantic<3.0.0,>=2.7.4->langchain)
  Downloading annotated_types-0.8.0-py3-none-any.whl.metadata (15 kB)
Collecting pydantic-core==2.46.5 (from pydantic<3.0.0,>=2.7.4->langchain)
  Downloading pydantic_core-2.46.5-cp313-cp313-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (6.6 kB)
Collecting typing-inspection>=0.4.2 (from pydantic<3.0.0,>=2.7.4->langchain)
  Downloading typing_inspection-0.4.4-py3-none-any.whl.metadata (2.6 kB)
Collecting aiohttp<4.0.0,>=3.8.3 (from langchain_community)
  Downloading aiohttp-3.14.3-cp313-cp313-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl.metadata (8.3 kB)
Collecting httpx-sse<1.0.0,>=0.4.0 (from langchain_community)
  Downloading httpx_sse-0.4.3-py3-none-any.whl.metadata (9.7 kB)
Collecting langchain-classic<2.0.0,>=1.0.7 (from langchain_community)
  Downloading langchain_classic-1.0.8-py3-none-any.whl.metadata (5.1 kB)
Collecting numpy>=2.1.0 (from langchain_community)
  Downloading numpy-2.5.3-cp313-cp313-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl.metadata (6.6 kB)
Collecting pydantic-settings<3.0.0,>=2.10.1 (from langchain_community)
  Downloading pydantic_settings-2.15.0-py3-none-any.whl.metadata (3.9 kB)
Collecting sqlalchemy<3.0.0,>=1.4.0 (from langchain_community)
  Downloading sqlalchemy-2.0.52-cp313-cp313-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl.metadata (9.6 kB)
Collecting aiohappyeyeballs>=2.5.0 (from aiohttp<4.0.0,>=3.8.3->langchain_community)
  Downloading aiohappyeyeballs-2.7.1-py3-none-any.whl.metadata (5.9 kB)
Collecting aiosignal>=1.4.0 (from aiohttp<4.0.0,>=3.8.3->langchain_community)
  Downloading aiosignal-1.4.0-py3-none-any.whl.metadata (3.7 kB)
Collecting attrs>=17.3.0 (from aiohttp<4.0.0,>=3.8.3->langchain_community)
  Downloading attrs-26.1.0-py3-none-any.whl.metadata (8.8 kB)
Collecting frozenlist>=1.1.1 (from aiohttp<4.0.0,>=3.8.3->langchain_community)
  Downloading frozenlist-1.8.0-cp313-cp313-manylinux1_x86_64.manylinux_2_28_x86_64.manylinux_2_5_x86_64.whl.metadata (20 kB)
Collecting multidict<7.0,>=4.5 (from aiohttp<4.0.0,>=3.8.3->langchain_community)
  Downloading multidict-6.8.0-cp313-cp313-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl.metadata (5.3 kB)
Collecting propcache>=0.2.0 (from aiohttp<4.0.0,>=3.8.3->langchain_community)
  Downloading propcache-0.5.2-cp313-cp313-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl.metadata (16 kB)
Collecting yarl<2.0,>=1.17.0 (from aiohttp<4.0.0,>=3.8.3->langchain_community)
  Downloading yarl-1.24.5-cp313-cp313-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl.metadata (103 kB)
Collecting python-dotenv>=0.21.0 (from pydantic-settings<3.0.0,>=2.10.1->langchain_community)
  Downloading python_dotenv-1.2.3-py3-none-any.whl.metadata (29 kB)
Collecting charset_normalizer<4,>=2 (from requests>=2.0.0->langsmith<1.0.0,>=0.3.45->langchain_core)
  Downloading charset_normalizer-3.5.1-cp313-cp313-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl.metadata (45 kB)
Collecting urllib3<3,>=1.26 (from requests>=2.0.0->langsmith<1.0.0,>=0.3.45->langchain_core)
  Downloading urllib3-2.7.0-py3-none-any.whl.metadata (6.9 kB)
Collecting greenlet>=1 (from sqlalchemy<3.0.0,>=1.4.0->langchain_community)
  Downloading greenlet-3.5.5-cp313-cp313-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl.metadata (3.8 kB)
Downloading langchain-1.4.0-py3-none-any.whl (161 kB)
Downloading langchain_core-1.6.3-py3-none-any.whl (571 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 571.8/571.8 kB 248.0 MB/s  0:00:00
Downloading langgraph-1.2.11-py3-none-any.whl (248 kB)
Downloading httpx-0.28.1-py3-none-any.whl (73 kB)
Downloading httpcore-1.0.9-py3-none-any.whl (78 kB)
Downloading jsonpatch-1.33-py2.py3-none-any.whl (12 kB)
Downloading langgraph_checkpoint-4.2.0-py3-none-any.whl (56 kB)
Downloading langgraph_prebuilt-1.1.0-py3-none-any.whl (41 kB)
Downloading langgraph_sdk-0.4.4-py3-none-any.whl (162 kB)
Downloading langsmith-0.12.4-py3-none-any.whl (767 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 767.5/767.5 kB 700.4 MB/s  0:00:00
Downloading httpx2-2.12.0-py3-none-any.whl (95 kB)
Downloading httpcore2-2.12.0-py3-none-any.whl (83 kB)
Downloading pydantic-2.13.5-py3-none-any.whl (472 kB)
Downloading pydantic_core-2.46.5-cp313-cp313-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (2.1 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.1/2.1 MB 590.5 MB/s  0:00:00
Downloading pyyaml-6.0.3-cp313-cp313-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl (801 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 801.6/801.6 kB 588.0 MB/s  0:00:00
Downloading tenacity-9.1.4-py3-none-any.whl (28 kB)
Downloading typing_extensions-4.16.0-py3-none-any.whl (45 kB)
Downloading uuid_utils-0.17.1-cp313-cp313-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (323 kB)
Downloading websockets-16.1.1-cp313-cp313-manylinux1_x86_64.manylinux_2_28_x86_64.manylinux_2_5_x86_64.whl (187 kB)
Downloading langchain_community-0.4.2-py3-none-any.whl (2.4 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.4/2.4 MB 603.1 MB/s  0:00:00
Downloading aiohttp-3.14.3-cp313-cp313-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl (1.8 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.8/1.8 MB 653.4 MB/s  0:00:00
Downloading httpx_sse-0.4.3-py3-none-any.whl (9.0 kB)
Downloading langchain_classic-1.0.8-py3-none-any.whl (1.0 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.0/1.0 MB 739.5 MB/s  0:00:00
Downloading langchain_text_splitters-1.1.2-py3-none-any.whl (35 kB)
Downloading multidict-6.8.0-cp313-cp313-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl (287 kB)
Downloading pydantic_settings-2.15.0-py3-none-any.whl (69 kB)
Downloading requests-2.34.2-py3-none-any.whl (73 kB)
Downloading charset_normalizer-3.5.1-cp313-cp313-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl (250 kB)
Downloading idna-3.19-py3-none-any.whl (68 kB)
Downloading sqlalchemy-2.0.52-cp313-cp313-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl (3.3 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.3/3.3 MB 451.4 MB/s  0:00:00
Downloading urllib3-2.7.0-py3-none-any.whl (131 kB)
Downloading yarl-1.24.5-cp313-cp313-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl (110 kB)
Downloading aiohappyeyeballs-2.7.1-py3-none-any.whl (15 kB)
Downloading aiosignal-1.4.0-py3-none-any.whl (7.5 kB)
Downloading annotated_types-0.8.0-py3-none-any.whl (13 kB)
Downloading anyio-4.15.1-py3-none-any.whl (132 kB)
Downloading attrs-26.1.0-py3-none-any.whl (67 kB)
Downloading certifi-2026.7.22-py3-none-any.whl (136 kB)
Downloading distro-1.9.0-py3-none-any.whl (20 kB)
Downloading frozenlist-1.8.0-cp313-cp313-manylinux1_x86_64.manylinux_2_28_x86_64.manylinux_2_5_x86_64.whl (234 kB)
Downloading greenlet-3.5.5-cp313-cp313-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl (623 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 623.9/623.9 kB 668.2 MB/s  0:00:00
Downloading h11-0.16.0-py3-none-any.whl (37 kB)
Downloading jsonpointer-3.1.1-py3-none-any.whl (7.7 kB)
Downloading langchain_protocol-0.0.19-py3-none-any.whl (7.3 kB)
Downloading numpy-2.5.3-cp313-cp313-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl (16.7 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 16.7/16.7 MB 405.9 MB/s  0:00:00
Downloading orjson-3.12.0-cp313-cp313-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (131 kB)
Downloading ormsgpack-1.12.2-cp313-cp313-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (212 kB)
Downloading packaging-26.3-py3-none-any.whl (129 kB)
Downloading propcache-0.5.2-cp313-cp313-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl (61 kB)
Downloading python_dotenv-1.2.3-py3-none-any.whl (22 kB)
Downloading requests_toolbelt-1.0.0-py2.py3-none-any.whl (54 kB)
Downloading sniffio-1.3.1-py3-none-any.whl (10 kB)
Downloading truststore-0.10.4-py3-none-any.whl (18 kB)
Downloading typing_inspection-0.4.4-py3-none-any.whl (14 kB)
Downloading xxhash-4.0.1-cp313-cp313-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl (268 kB)
Downloading zstandard-0.25.0-cp313-cp313-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (5.5 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.5/5.5 MB 406.2 MB/s  0:00:00
Installing collected packages: zstandard, xxhash, websockets, uuid-utils, urllib3, typing-extensions, truststore, tenacity, sniffio, pyyaml, python-dotenv, propcache, packaging, ormsgpack, orjson, numpy, multidict, jsonpointer, idna, httpx-sse, h11, greenlet, frozenlist, distro, charset_normalizer, certifi, attrs, annotated-types, aiohappyeyeballs, yarl, typing-inspection, sqlalchemy, requests, pydantic-core, langchain-protocol, jsonpatch, httpcore2, httpcore, anyio, aiosignal, requests-toolbelt, pydantic, httpx2, httpx, aiohttp, pydantic-settings, langsmith, langchain_core, langgraph-sdk, langgraph-checkpoint, langchain-text-splitters, langgraph-prebuilt, langchain-classic, langgraph, langchain_community, langchain
  Attempting uninstall: zstandard
    Found existing installation: zstandard 0.25.0
    Uninstalling zstandard-0.25.0:
      Successfully uninstalled zstandard-0.25.0
  Attempting uninstall: xxhash
    Found existing installation: xxhash 4.0.1
    Uninstalling xxhash-4.0.1:
      Successfully uninstalled xxhash-4.0.1
  Attempting uninstall: websockets
    Found existing installation: websockets 16.1.1
    Uninstalling websockets-16.1.1:
      Successfully uninstalled websockets-16.1.1
  Attempting uninstall: uuid-utils
    Found existing installation: uuid_utils 0.17.1
    Uninstalling uuid_utils-0.17.1:
      Successfully uninstalled uuid_utils-0.17.1
  Attempting uninstall: urllib3
    Found existing installation: urllib3 2.7.0
    Uninstalling urllib3-2.7.0:
      Successfully uninstalled urllib3-2.7.0
  Attempting uninstall: typing-extensions
    Found existing installation: typing_extensions 4.16.0
    Uninstalling typing_extensions-4.16.0:
      Successfully uninstalled typing_extensions-4.16.0
  Attempting uninstall: truststore
    Found existing installation: truststore 0.10.4
    Uninstalling truststore-0.10.4:
      Successfully uninstalled truststore-0.10.4
  Attempting uninstall: tenacity
    Found existing installation: tenacity 9.1.4
    Uninstalling tenacity-9.1.4:
      Successfully uninstalled tenacity-9.1.4
  Attempting uninstall: sniffio
    Found existing installation: sniffio 1.3.1
    Uninstalling sniffio-1.3.1:
      Successfully uninstalled sniffio-1.3.1
  Attempting uninstall: pyyaml
    Found existing installation: PyYAML 6.0.3
    Uninstalling PyYAML-6.0.3:
      Successfully uninstalled PyYAML-6.0.3
  Attempting uninstall: python-dotenv
    Found existing installation: python-dotenv 1.2.3
    Uninstalling python-dotenv-1.2.3:
      Successfully uninstalled python-dotenv-1.2.3
  Attempting uninstall: propcache
    Found existing installation: propcache 0.5.2
    Uninstalling propcache-0.5.2:
      Successfully uninstalled propcache-0.5.2
  Attempting uninstall: packaging
    Found existing installation: packaging 26.3
    Uninstalling packaging-26.3:
      Successfully uninstalled packaging-26.3
  Attempting uninstall: ormsgpack
    Found existing installation: ormsgpack 1.12.2
    Uninstalling ormsgpack-1.12.2:
      Successfully uninstalled ormsgpack-1.12.2
  Attempting uninstall: orjson
    Found existing installation: orjson 3.12.0
    Uninstalling orjson-3.12.0:
      Successfully uninstalled orjson-3.12.0
  Attempting uninstall: numpy
    Found existing installation: numpy 2.5.3
    Uninstalling numpy-2.5.3:
      Successfully uninstalled numpy-2.5.3
  Attempting uninstall: multidict
    Found existing installation: multidict 6.8.0
    Uninstalling multidict-6.8.0:
      Successfully uninstalled multidict-6.8.0
  Attempting uninstall: jsonpointer
    Found existing installation: jsonpointer 3.1.1
    Uninstalling jsonpointer-3.1.1:
      Successfully uninstalled jsonpointer-3.1.1
  Attempting uninstall: idna
    Found existing installation: idna 3.19
    Uninstalling idna-3.19:
      Successfully uninstalled idna-3.19
  Attempting uninstall: httpx-sse
    Found existing installation: httpx-sse 0.4.3
    Uninstalling httpx-sse-0.4.3:
      Successfully uninstalled httpx-sse-0.4.3
  Attempting uninstall: h11
    Found existing installation: h11 0.16.0
    Uninstalling h11-0.16.0:
      Successfully uninstalled h11-0.16.0
  Attempting uninstall: greenlet
    Found existing installation: greenlet 3.5.5
    Uninstalling greenlet-3.5.5:
      Successfully uninstalled greenlet-3.5.5
  Attempting uninstall: frozenlist
    Found existing installation: frozenlist 1.8.0
    Uninstalling frozenlist-1.8.0:
      Successfully uninstalled frozenlist-1.8.0
  Attempting uninstall: distro
    Found existing installation: distro 1.9.0
    Uninstalling distro-1.9.0:
      Successfully uninstalled distro-1.9.0
  Attempting uninstall: charset_normalizer
    Found existing installation: charset-normalizer 3.5.1
    Uninstalling charset-normalizer-3.5.1:
      Successfully uninstalled charset-normalizer-3.5.1
  Attempting uninstall: certifi
    Found existing installation: certifi 2026.7.22
    Uninstalling certifi-2026.7.22:
      Successfully uninstalled certifi-2026.7.22
  Attempting uninstall: attrs
    Found existing installation: attrs 26.1.0
    Uninstalling attrs-26.1.0:
      Successfully uninstalled attrs-26.1.0
  Attempting uninstall: annotated-types
    Found existing installation: annotated-types 0.8.0
    Uninstalling annotated-types-0.8.0:
      Successfully uninstalled annotated-types-0.8.0
  Attempting uninstall: aiohappyeyeballs
    Found existing installation: aiohappyeyeballs 2.7.1
    Uninstalling aiohappyeyeballs-2.7.1:
      Successfully uninstalled aiohappyeyeballs-2.7.1
  Attempting uninstall: yarl
    Found existing installation: yarl 1.24.5
    Uninstalling yarl-1.24.5:
      Successfully uninstalled yarl-1.24.5
  Attempting uninstall: typing-inspection
    Found existing installation: typing-inspection 0.4.4
    Uninstalling typing-inspection-0.4.4:
      Successfully uninstalled typing-inspection-0.4.4
  Attempting uninstall: sqlalchemy
    Found existing installation: SQLAlchemy 2.0.52
    Uninstalling SQLAlchemy-2.0.52:
      Successfully uninstalled SQLAlchemy-2.0.52
  Attempting uninstall: requests
    Found existing installation: requests 2.34.2
    Uninstalling requests-2.34.2:
      Successfully uninstalled requests-2.34.2
  Attempting uninstall: pydantic-core
    Found existing installation: pydantic_core 2.46.5
    Uninstalling pydantic_core-2.46.5:
      Successfully uninstalled pydantic_core-2.46.5
  Attempting uninstall: langchain-protocol
    Found existing installation: langchain-protocol 0.0.19
    Uninstalling langchain-protocol-0.0.19:



```
# Isto está formatado como código
```

### 4.3 Construção do Pipeline LangChain para Contextualização

Agora, vamos combinar o LLM customizado e o retriever em um pipeline LangChain. Isso nos permitirá contextualizar as respostas da LLM com as informações recuperadas da nossa base de dados simulada, de forma semelhante ao funcionamento de um agente RAG.

In [20]:
import os
import sys
import site
import importlib

# Primeiro, tenta as importações padrão. Se funcionarem, ótimo.
try:
    from langchain.chains.combine_documents import create_stuff_documents_chain
    from langchain_core.prompts import ChatPromptTemplate
    from langchain.chains import create_retrieval_chain
    print("Importações do LangChain.chains realizadas com sucesso!")

except ImportError as e_standard:
    print(f"Importação padrão de LangChain.chains falhou: {e_standard}")
    print("Realizando diagnóstico aprofundado e tentando workaround...")

    # --- Início do Diagnóstico e Workaround ---
    langchain_path = None
    try:
        import langchain
        langchain_path = langchain.__path__[0]
        print(f"Pacote 'langchain' importado de: {langchain_path}")
    except ImportError:
        print("Erro: O pacote 'langchain' principal não pôde ser importado. Instalação básica falhou.")
        raise  # Re-raise se o pacote principal nem estiver lá

    chains_dir = os.path.join(langchain_path, 'chains')
    print(f"Caminho esperado para 'langchain.chains': {chains_dir}")
    chains_init_exists = os.path.exists(os.path.join(chains_dir, '__init__.py'))
    chains_dir_exists = os.path.isdir(chains_dir)

    print(f"Diretório 'chains' existe em {langchain_path}: {chains_dir_exists}")
    print(f"'__init__.py' existe em {chains_dir}: {chains_init_exists}")

    if not chains_dir_exists or not chains_init_exists:
        print("ERRO CRÍTICO: DIRETÓRIO 'langchain.chains' OU '__init__.py' AUSENTE.")
        print("A instalação do LangChain está CORROMPIDA no disco. Nenhuma solução programática pode resolver isso sem uma reinstalação completa e limpa.")
        print("A única solução *confiável* é uma REINICIALIZAÇÃO DE FÁBRICA do ambiente de execução (Runtime -> Factory reset runtime), seguida da execução de todas as células.")
        raise ImportError(f"Instalação do LangChain corrompida: módulo 'langchain.chains' não encontrado fisicamente. Detalhes: dir_exists={chains_dir_exists}, init_exists={chains_init_exists}")

    print("Diretório 'langchain.chains' e '__init__.py' encontrados fisicamente.")
    print("Parece que o problema é a resolução de módulos do Python. Tentando um workaround agressivo...")

    # Adicionar o diretório 'chains' ao sys.path para tentar forçar a resolução.
    # Isso é um hack agressivo e normalmente não é necessário para subpacotes.
    if chains_dir not in sys.path:
        sys.path.insert(0, chains_dir)
        print(f"Adicionando {chains_dir} ao sys.path para forçar a resolução.")

    # Invalida os caches do importlib para que o Python tente novamente a resolução
    importlib.invalidate_caches()

    # Tenta as importações novamente após a manipulação do sys.path e caches
    try:
        from langchain.chains.combine_documents import create_stuff_documents_chain
        from langchain_core.prompts import ChatPromptTemplate
        from langchain.chains import create_retrieval_chain
        print("Importações do LangChain.chains realizadas com sucesso após workaround de sys.path!")

    except ImportError as e_workaround:
        print(f"Importação de LangChain.chains AINDA FALHOU após workaround de sys.path: {e_workaround}")
        print("Nenhuma solução programática para este ambiente corrompido. Uma REINICIALIZAÇÃO DE FÁBRICA é estritamente necessária.")
        raise  # Re-raise se ainda falhar

    # --- Fim do Diagnóstico e Workaround ---

# 1. Definir um template de prompt para RAG (Retrieval Augmented Generation)
rag_prompt = ChatPromptTemplate.from_messages([
    ("system", "Você é um assistente médico prestativo. Use as seguintes informações de contexto para responder à pergunta do usuário. Se você não souber a resposta, diga 'Não consigo encontrar essa informação nos prontuários fornecidos.'\n\nContexto:\n{context}"),
    ("user", "{input}")
])

# 2. Criar uma cadeia para combinar os documentos (stuff documents chain)
# Esta cadeia pega os documentos recuperados e os "coloca" no prompt como contexto.
document_chain = create_stuff_documents_chain(custom_llm, rag_prompt)

# 3. Criar a cadeia de recuperação completa (retrieval chain)
# Esta cadeia combina o retriever e a document_chain.
retrieval_chain = create_retrieval_chain(retriever, document_chain)

print("Pipeline LangChain RAG configurado.")

# 4. Demonstrar uma consulta com contextualização
print("\nDemonstrando uma consulta contextualizada:")

# Pergunta que se beneficia do contexto dos prontuários
question_1 = "Qual a medicação de manutenção do paciente João Silva para asma e quando é a próxima consulta?"
response_rag_1 = retrieval_chain.invoke({"input": question_1})
print(f"Pergunta: {question_1}")
print(f"Resposta: {response_rag_1['answer']}")

print("\n--- Exemplo 2 ---")
# Pergunta que não tem resposta direta no contexto
question_2 = "Qual a dosagem recomendada de Ibuprofeno para adultos?"
response_rag_2 = retrieval_chain.invoke({"input": question_2})
print(f"Pergunta: {question_2}")
print(f"Resposta: {response_rag_2['answer']}")

Importação padrão de LangChain.chains falhou: No module named 'langchain.chains'
Realizando diagnóstico aprofundado e tentando workaround...
Pacote 'langchain' importado de: /usr/local/lib/python3.13/dist-packages/langchain
Caminho esperado para 'langchain.chains': /usr/local/lib/python3.13/dist-packages/langchain/chains
Diretório 'chains' existe em /usr/local/lib/python3.13/dist-packages/langchain: False
'__init__.py' existe em /usr/local/lib/python3.13/dist-packages/langchain/chains: False
ERRO CRÍTICO: DIRETÓRIO 'langchain.chains' OU '__init__.py' AUSENTE.
A instalação do LangChain está CORROMPIDA no disco. Nenhuma solução programática pode resolver isso sem uma reinstalação completa e limpa.
A única solução *confiável* é uma REINICIALIZAÇÃO DE FÁBRICA do ambiente de execução (Runtime -> Factory reset runtime), seguida da execução de todas as células.

ImportError: Instalação do LangChain corrompida: módulo 'langchain.chains' não encontrado fisicamente. Detalhes: dir_exists=False, init_exists=False